package main

import (
	"flag"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/pluginpb"
)

const generatedCodeVersion = "0.1.0"

func main() {
	var flags flag.FlagSet
	opts := protogen.Options{
		ParamFunc: flags.Set,
	}

	opts.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, file := range gen.Files {
			if file.Generate {
				generateFile(gen, file)
			}
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + ".protojsonx.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	helperPackage := protogen.GoImportPath("github.com/sudorandom/protojsonx/protojsonxgen")

	g.P("// Code generated by protoc-gen-go-protojsonx. DO NOT EDIT.")
	g.P("// versions:")
	g.P("// \tprotoc-gen-go-protojsonx v", generatedCodeVersion)
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("// This file is a placeholder for schema-specific protojsonx code.")
	g.P("// The generator is wired through protogen.Options so it follows the same")
	g.P("// module= and import-path behavior as protoc-gen-go.")
	g.P("const _ = ", strconvQuote("protojsonx generated scaffold "+generatedCodeVersion))
	g.P()

	for _, message := range file.Messages {
		generateMessage(g, helperPackage, message)
	}
}

func generateMessage(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, message *protogen.Message) {
	if message.Desc.IsMapEntry() {
		return
	}

	g.P("func (x *", message.GoIdent, ") MarshalProtoJSONX() ([]byte, error) {")
	if supportsGeneratedMarshal(message) {
		g.P("e := ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "NewEncoder"}), "()")
		g.P("if err := x.marshalProtoJSONXTo(e); err != nil {")
		g.P("return nil, err")
		g.P("}")
		g.P("return e.Bytes(), nil")
	} else {
		g.P("return ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "Marshal"}), "(x)")
	}
	g.P("}")
	g.P()
	g.P("func (x *", message.GoIdent, ") UnmarshalProtoJSONX(data []byte) error {")
	if supportsGeneratedUnmarshal(message) {
		decoderIdent := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "NewDecoder"})
		g.P("d := ", decoderIdent, "(data)")
		g.P("*x = ", message.GoIdent, "{}")
		if len(message.Fields) > 0 {
			// C: peek the first key so we skip the fast-path attempt entirely
			// when the input is shuffled, saving a Mark/Reset/re-zero roundtrip.
			field0JSON := message.Fields[0].Desc.JSONName()
			g.P("firstKey, savedOff, savedDepth, _, peekErr := d.PeekObjectFieldName()")
			g.P("if peekErr != nil { return peekErr }")
			g.P("if firstKey == ", strconvQuote(field0JSON), " || firstKey == \"\" {")
			g.P("d.Reset(savedOff, savedDepth)")
			g.P("if ok, err := x.unmarshalProtoJSONXFast(d); err != nil {")
			g.P("return err")
			g.P("} else if ok {")
			g.P("return d.Finish()")
			g.P("}")
			g.P("*x = ", message.GoIdent, "{}")
			g.P("}")
			g.P("d.Reset(savedOff, savedDepth)")
		} else {
			// No fields: fast path handles empty objects; just try it directly.
			g.P("off, depth := d.Mark()")
			g.P("if ok, err := x.unmarshalProtoJSONXFast(d); err != nil {")
			g.P("return err")
			g.P("} else if ok {")
			g.P("return d.Finish()")
			g.P("}")
			g.P("d.Reset(off, depth)")
		}
		g.P("if err := x.unmarshalProtoJSONXFrom(d); err != nil {")
		g.P("return err")
		g.P("}")
		g.P("return d.Finish()")
	} else {
		g.P("return ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "Unmarshal"}), "(data, x)")
	}
	g.P("}") 
	g.P()

	if supportsGeneratedMarshal(message) {
		generateMessageMarshalTo(g, helperPackage, message)
	}
	if supportsGeneratedUnmarshal(message) {
		generateMessageUnmarshalFast(g, helperPackage, message)
		if len(message.Fields) >= mapDispatchThreshold {
			generateFieldIndexMap(g, message)
		}
		generateMessageUnmarshalFrom(g, helperPackage, message)
	}

	for _, nested := range message.Messages {
		generateMessage(g, helperPackage, nested)
	}
}

func generateMessageUnmarshalFast(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, message *protogen.Message) {
	decoderIdent := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "Decoder"})
	g.P("func (x *", message.GoIdent, ") unmarshalProtoJSONXFast(d *", decoderIdent, ") (bool, error) {")
	g.P("if err := d.BeginObject(); err != nil {")
	g.P("return false, err")
	g.P("}")
	g.P("fastFirst := true")
	for _, field := range message.Fields {
		g.P("{")
		g.P("matched, done, err := d.TryObjectFieldFast(&fastFirst, ", strconvQuote(field.Desc.JSONName()), ")")
		g.P("if err != nil {")
		g.P("return false, err")
		g.P("}")
		g.P("if done {")
		g.P("return true, nil")
		g.P("}")
		g.P("if !matched {")
		g.P("return false, nil")
		g.P("}")
		generateFieldUnmarshalFast(g, helperPackage, field)
		g.P("}")
	}
	g.P("done, err := d.TryEndObject()")
	g.P("if err != nil {")
	g.P("return false, err")
	g.P("}")
	g.P("if !done {")
	g.P("return false, nil")
	g.P("}")
	g.P("return true, nil")
	g.P("}")
	g.P()
}

func generateFieldUnmarshalFast(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, field *protogen.Field) {
	access := "x." + field.GoName
	if field.Desc.IsMap() {
		g.P("if d.ReadNull() {")
		g.P(access, " = nil")
		g.P("} else {")
		g.P("m := make(map[string]string)")
		g.P("if err := d.BeginObject(); err != nil { return false, err }")
		g.P("mapFirst := true")
		g.P("for {")
		g.P("k, mapOK, err := d.NextObjectKey(&mapFirst)")
		g.P("if err != nil { return false, err }")
		g.P("if !mapOK { break }")
		g.P("v, err := d.ReadString()")
		g.P("if err != nil { return false, err }")
		g.P("m[k] = v")
		g.P("}")
		g.P(access, " = m")
		g.P("}")
		return
	}
	if field.Desc.IsList() {
		g.P("if d.ReadNull() {")
		g.P(access, " = nil")
		g.P("} else {")
		generateListValuesInit(g, field, access)
		g.P("if err := d.BeginArray(); err != nil { return false, err }")
		g.P("arrayFirst := true")
		g.P("for {")
		g.P("elemOK, err := d.NextArrayElement(&arrayFirst)")
		g.P("if err != nil { return false, err }")
		g.P("if !elemOK { break }")
		if field.Desc.Kind() == protoreflect.MessageKind {
			g.P("if d.ReadNull() { return false, ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "NullRepeatedMessage"}), "() }")
		}
		generateScalarOrMessageReadFast(g, helperPackage, field, "v", true)
		g.P("values = append(values, v)")
		g.P("}")
		g.P(access, " = values")
		g.P("}")
		return
	}
	g.P("if d.ReadNull() {")
	g.P(access, " = ", zeroValue(field))
	g.P("} else {")
	generateScalarOrMessageReadFast(g, helperPackage, field, access, false)
	g.P("}")
}

func generateScalarOrMessageReadFast(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, field *protogen.Field, target string, declare bool) {
	readTarget := target
	if !declare && field.Desc.Kind() != protoreflect.MessageKind {
		readTarget = "v"
	}
	switch field.Desc.Kind() {
	case protoreflect.StringKind:
		g.P(readTarget, ", err := d.ReadString()")
		g.P("if err != nil { return false, err }")
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		g.P(readTarget, ", err := d.ReadInt32()")
		g.P("if err != nil { return false, err }")
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		g.P(readTarget, ", err := d.ReadInt64()")
		g.P("if err != nil { return false, err }")
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		g.P(readTarget, ", err := d.ReadUint32()")
		g.P("if err != nil { return false, err }")
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		g.P(readTarget, ", err := d.ReadUint64()")
		g.P("if err != nil { return false, err }")
	case protoreflect.FloatKind:
		g.P(readTarget, ", err := d.ReadFloat32()")
		g.P("if err != nil { return false, err }")
	case protoreflect.DoubleKind:
		g.P(readTarget, ", err := d.ReadFloat64()")
		g.P("if err != nil { return false, err }")
	case protoreflect.BoolKind:
		g.P(readTarget, ", err := d.ReadBool()")
		g.P("if err != nil { return false, err }")
	case protoreflect.BytesKind:
		g.P(readTarget, ", err := d.ReadBytes()")
		g.P("if err != nil { return false, err }")
	case protoreflect.EnumKind:
		generateEnumUnmarshalFast(g, helperPackage, field, target, declare)
	case protoreflect.MessageKind:
		generateMessageUnmarshalFastField(g, field, target, declare)
	}
	if !declare && field.Desc.Kind() != protoreflect.MessageKind && field.Desc.Kind() != protoreflect.EnumKind {
		g.P(target, " = v")
	}
}

func generateEnumUnmarshalFast(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, field *protogen.Field, target string, declare bool) {
	readTarget := target
	if !declare {
		readTarget = "v"
	}
	matchStringBytes := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "MatchStringBytes"})
	g.P("var ", readTarget, " ", field.Enum.GoIdent)
	g.P("if d.IsString() {")
	g.P("s, err := d.ReadStringBytes()")
	g.P("if err != nil { return false, err }")
	for _, enumValue := range field.Enum.Values {
		g.P("if ", matchStringBytes, "(s, ", strconvQuote(string(enumValue.Desc.Name())), ") {")
		g.P(readTarget, " = ", enumValue.GoIdent)
		g.P("} else ")
	}
	g.P("{")
	g.P("return false, ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "UnknownEnumValue"}), "(string(s))")
	g.P("}")
	g.P("} else {")
	g.P("n, err := d.ReadInt32()")
	g.P("if err != nil { return false, err }")
	g.P(readTarget, " = ", field.Enum.GoIdent, "(n)")
	g.P("}")
	if !declare {
		g.P(target, " = ", readTarget)
	}
}

func generateMessageUnmarshalFastField(g *protogen.GeneratedFile, field *protogen.Field, target string, declare bool) {
	fullName := field.Message.Desc.FullName()
	if fullName == "google.protobuf.Timestamp" || fullName == "google.protobuf.Duration" {
		if declare {
			g.P("var ", target, " *", field.Message.GoIdent)
		}
		if fullName == "google.protobuf.Timestamp" {
			g.P("secs, nanos, err := d.ReadTimestamp()")
		} else {
			g.P("secs, nanos, err := d.ReadDuration()")
		}
		g.P("if err != nil { return false, err }")
		g.P(target, " = &", field.Message.GoIdent, "{Seconds: secs, Nanos: nanos}")
		return
	}
	if declare {
		g.P(target, " := &", field.Message.GoIdent, "{}")
	} else {
		g.P(target, " = &", field.Message.GoIdent, "{}")
	}
	g.P("if ok, err := ", target, ".unmarshalProtoJSONXFast(d); err != nil {")
	g.P("return false, err")
	g.P("} else if !ok {")
	g.P("return false, nil")
	g.P("}")
}

// mapDispatchThreshold is the minimum number of fields at which we switch
// from a linear switch-string fallback to a map[string]int + switch-int
// dispatch. The map gives O(1) key lookup; the integer switch compiles to a
// CPU jump table so field handling stays fully inlined (no indirect calls,
// no *uint64 pointer aliasing). Below the threshold the switch-string is
// faster due to cache effects and zero hash overhead.
// mapDispatchThreshold is the minimum number of fields at which we switch
// from a linear switch-string fallback to a map[string]int + switch-int
// dispatch. The map gives O(1) key lookup; the integer switch compiles to a
// CPU jump table so field handling stays fully inlined (no indirect calls,
// no *uint64 pointer aliasing).
//
// Benchmarks on arm64 (M1 Pro) showed that the Go runtime's map hash overhead
// exceeds the SIMD string comparison savings for messages up to ~22 fields.
// The threshold is set conservatively high; lower it when messages with
// 30+ fields are benchmarked and confirmed to improve.
const mapDispatchThreshold = 32

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var buf [20]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte(n%10) + '0'
		n /= 10
	}
	return string(buf[i:])
}

// generateFieldIndexMap emits a package-level map[string]int that maps every
// known JSON key (camelCase and proto snake_case) to its zero-based field
// index. The index drives an integer switch in unmarshalProtoJSONXFrom, which
// the Go compiler lowers to a jump table — giving O(1) dispatch without any
// indirect function calls.
func generateFieldIndexMap(g *protogen.GeneratedFile, message *protogen.Message) {
	g.P("var _", message.GoIdent.GoName, "FieldIndex = map[string]int{")
	for i, field := range message.Fields {
		jsonName := field.Desc.JSONName()
		protoName := string(field.Desc.Name())
		g.P(strconvQuote(jsonName), ": ", i, ",")
		if jsonName != protoName {
			g.P(strconvQuote(protoName), ": ", i, ",")
		}
	}
	g.P("}")
	g.P()
}

func generateMessageUnmarshalFrom(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, message *protogen.Message) {
	decoderIdent := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "Decoder"})
	g.P("func (x *", message.GoIdent, ") unmarshalProtoJSONXFrom(d *", decoderIdent, ") error {")
	g.P("if err := d.BeginObject(); err != nil {")
	g.P("return err")
	g.P("}")
	g.P("var seen uint64")
	g.P("first := true")
	g.P("for {")
	g.P("key, ok, err := d.NextObjectKey(&first)")
	g.P("if err != nil {")
	g.P("return err")
	g.P("}")
	g.P("if !ok {")
	g.P("return nil")
	g.P("}")
	unknownField := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "UnknownField"})
	if len(message.Fields) >= mapDispatchThreshold {
		// A: O(1) map lookup drives an integer jump table. Field handling is
		// emitted inline inside the switch so the compiler can optimise each
		// case independently — no indirect calls, no *uint64 aliasing.
		g.P("idx, hit := _", message.GoIdent.GoName, "FieldIndex[key]")
		g.P("if !hit { return ", unknownField, "(key) }")
		g.P("switch idx {")
		for i, field := range message.Fields {
			g.P("case ", i, ":")
			generateSeenCheck(g, helperPackage, i)
			generateFieldUnmarshal(g, helperPackage, field)
			g.P("continue")
		}
		g.P("}")
	} else {
		// Narrow messages: ordered hint + switch-string (better cache behaviour
		// than a map at low field counts).
		g.P("expected := 0")
		generateOrderedFieldFastPath(g, helperPackage, message)
		g.P("switch key {")
		for i, field := range message.Fields {
			jsonName := field.Desc.JSONName()
			protoName := string(field.Desc.Name())
			if jsonName == protoName {
				g.P("case ", strconvQuote(jsonName), ":")
			} else {
				g.P("case ", strconvQuote(jsonName), ", ", strconvQuote(protoName), ":")
			}
			generateSeenCheck(g, helperPackage, i)
			generateFieldUnmarshal(g, helperPackage, field)
			g.P("continue")
		}
		g.P("default:")
		g.P("return ", unknownField, "(key)")
		g.P("}")
	}
	g.P("}")
	g.P("}")
	g.P()
}

func generateOrderedFieldFastPath(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, message *protogen.Message) {
	if len(message.Fields) == 0 {
		return
	}
	g.P("switch expected {")
	for i, field := range message.Fields {
		g.P("case ", i, ":")
		g.P("if key == ", strconvQuote(field.Desc.JSONName()), " {")
		g.P("expected = ", i+1)
		generateSeenCheck(g, helperPackage, i)
		generateFieldUnmarshal(g, helperPackage, field)
		g.P("continue")
		g.P("}")
	}
	g.P("}")
}

func generateSeenCheck(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, index int) {
	duplicate := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "DuplicateField"})
	g.P("const bit = uint64(1) << ", index)
	g.P("if seen&bit != 0 {")
	g.P("return ", duplicate, "(key)")
	g.P("}")
	g.P("seen |= bit")
}

func generateFieldUnmarshal(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, field *protogen.Field) {
	access := "x." + field.GoName
	if field.Desc.IsMap() {
		g.P("if d.ReadNull() {")
		g.P(access, " = nil")
		g.P("return nil")
		g.P("}")
		g.P("m := make(map[string]string)")
		g.P("if err := d.BeginObject(); err != nil {")
		g.P("return err")
		g.P("}")
		g.P("mapFirst := true")
		g.P("for {")
		g.P("k, mapOK, err := d.NextObjectKey(&mapFirst)")
		g.P("if err != nil {")
		g.P("return err")
		g.P("}")
		g.P("if !mapOK {")
		g.P("break")
		g.P("}")
		g.P("v, err := d.ReadString()")
		g.P("if err != nil {")
		g.P("return err")
		g.P("}")
		g.P("m[k] = v")
		g.P("}")
		g.P(access, " = m")
		return
	}
	if field.Desc.IsList() {
		generateListUnmarshal(g, helperPackage, field, access)
		return
	}
	g.P("if d.ReadNull() {")
	g.P(access, " = ", zeroValue(field))
	g.P("return nil")
	g.P("}")
	generateScalarOrMessageRead(g, helperPackage, field, access, false)
}

func generateListUnmarshal(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, field *protogen.Field, access string) {
	g.P("if d.ReadNull() {")
	g.P(access, " = nil")
	g.P("return nil")
	g.P("}")
	generateListValuesInit(g, field, access)
	g.P("if err := d.BeginArray(); err != nil {")
	g.P("return err")
	g.P("}")
	g.P("arrayFirst := true")
	g.P("for {")
	g.P("elemOK, err := d.NextArrayElement(&arrayFirst)")
	g.P("if err != nil {")
	g.P("return err")
	g.P("}")
	g.P("if !elemOK {")
	g.P("break")
	g.P("}")
	if field.Desc.Kind() == protoreflect.MessageKind {
		g.P("if d.ReadNull() {")
		g.P("return ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "NullRepeatedMessage"}), "()")
		g.P("}")
	}
	generateScalarOrMessageRead(g, helperPackage, field, "v", true)
	g.P("values = append(values, v)")
	g.P("}")
	g.P(access, " = values")
}

func generateListValuesInit(g *protogen.GeneratedFile, field *protogen.Field, access string) {
	g.P("values := ", access, "[:0]")
	g.P("if values == nil {")
	g.P("values = make([]", listElementGoType(g, field), ", 0, 4)")
	g.P("}")
}

func listElementGoType(g *protogen.GeneratedFile, field *protogen.Field) string {
	switch field.Desc.Kind() {
	case protoreflect.BoolKind:
		return "bool"
	case protoreflect.StringKind:
		return "string"
	case protoreflect.BytesKind:
		return "[]byte"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "int32"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "int64"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "uint32"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "uint64"
	case protoreflect.FloatKind:
		return "float32"
	case protoreflect.DoubleKind:
		return "float64"
	case protoreflect.EnumKind:
		return g.QualifiedGoIdent(field.Enum.GoIdent)
	case protoreflect.MessageKind:
		return "*" + g.QualifiedGoIdent(field.Message.GoIdent)
	default:
		return "any"
	}
}

func generateScalarOrMessageRead(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, field *protogen.Field, target string, declare bool) {
	readTarget := target
	if !declare && field.Desc.Kind() != protoreflect.MessageKind {
		readTarget = "v"
	}
	switch field.Desc.Kind() {
	case protoreflect.StringKind:
		g.P(readTarget, ", err := d.ReadString()")
		g.P("if err != nil { return err }")
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		g.P(readTarget, ", err := d.ReadInt32()")
		g.P("if err != nil { return err }")
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		g.P(readTarget, ", err := d.ReadInt64()")
		g.P("if err != nil { return err }")
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		g.P(readTarget, ", err := d.ReadUint32()")
		g.P("if err != nil { return err }")
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		g.P(readTarget, ", err := d.ReadUint64()")
		g.P("if err != nil { return err }")
	case protoreflect.FloatKind:
		g.P(readTarget, ", err := d.ReadFloat32()")
		g.P("if err != nil { return err }")
	case protoreflect.DoubleKind:
		g.P(readTarget, ", err := d.ReadFloat64()")
		g.P("if err != nil { return err }")
	case protoreflect.BoolKind:
		g.P(readTarget, ", err := d.ReadBool()")
		g.P("if err != nil { return err }")
	case protoreflect.BytesKind:
		g.P(readTarget, ", err := d.ReadBytes()")
		g.P("if err != nil { return err }")
	case protoreflect.EnumKind:
		generateEnumUnmarshal(g, helperPackage, field, target, declare)
	case protoreflect.MessageKind:
		generateMessageUnmarshal(g, field, target, declare)
	}
	if !declare && field.Desc.Kind() != protoreflect.MessageKind && field.Desc.Kind() != protoreflect.EnumKind {
		g.P(target, " = v")
	}
}

func generateEnumUnmarshal(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, field *protogen.Field, target string, declare bool) {
	readTarget := target
	if !declare {
		readTarget = "v"
	}
	matchStringBytes := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "MatchStringBytes"})
	g.P("var ", readTarget, " ", field.Enum.GoIdent)
	g.P("if d.IsString() {")
	g.P("s, err := d.ReadStringBytes()")
	g.P("if err != nil { return err }")
	for _, enumValue := range field.Enum.Values {
		g.P("if ", matchStringBytes, "(s, ", strconvQuote(string(enumValue.Desc.Name())), ") {")
		g.P(readTarget, " = ", enumValue.GoIdent)
		g.P("} else ")
	}
	g.P("{")
	g.P("return ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "UnknownEnumValue"}), "(string(s))")
	g.P("}")
	g.P("} else {")
	g.P("n, err := d.ReadInt32()")
	g.P("if err != nil { return err }")
	g.P(readTarget, " = ", field.Enum.GoIdent, "(n)")
	g.P("}")
	if !declare {
		g.P(target, " = ", readTarget)
	}
}

func generateMessageUnmarshal(g *protogen.GeneratedFile, field *protogen.Field, target string, declare bool) {
	fullName := field.Message.Desc.FullName()
	if fullName == "google.protobuf.Timestamp" || fullName == "google.protobuf.Duration" {
		if declare {
			g.P("var ", target, " *", field.Message.GoIdent)
		}
		if fullName == "google.protobuf.Timestamp" {
			g.P("secs, nanos, err := d.ReadTimestamp()")
		} else {
			g.P("secs, nanos, err := d.ReadDuration()")
		}
		g.P("if err != nil { return err }")
		g.P(target, " = &", field.Message.GoIdent, "{Seconds: secs, Nanos: nanos}")
		return
	}
	if declare {
		g.P(target, " := &", field.Message.GoIdent, "{}")
	} else {
		g.P(target, " = &", field.Message.GoIdent, "{}")
	}
	g.P("if err := ", target, ".unmarshalProtoJSONXFrom(d); err != nil {")
	g.P("return err")
	g.P("}")
}

func zeroValue(field *protogen.Field) string {
	if field.Desc.IsList() || field.Desc.IsMap() {
		return "nil"
	}
	switch field.Desc.Kind() {
	case protoreflect.StringKind:
		return "\"\""
	case protoreflect.BoolKind:
		return "false"
	case protoreflect.BytesKind, protoreflect.MessageKind:
		return "nil"
	default:
		return "0"
	}
}

func generateMessageMarshalTo(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, message *protogen.Message) {
	encoderIdent := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "Encoder"})
	g.P("func (x *", message.GoIdent, ") marshalProtoJSONXTo(e *", encoderIdent, ") error {")
	g.P("e.Byte('{')")
	g.P("wrote := false")
	for _, field := range message.Fields {
		generateFieldMarshal(g, helperPackage, field)
	}
	g.P("e.Byte('}')")
	g.P("return nil")
	g.P("}")
	g.P()
}

func generateFieldMarshal(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, field *protogen.Field) {
	name := field.Desc.JSONName()
	access := "x." + field.GoName

	if field.Desc.IsMap() {
		g.P("if len(", access, ") > 0 {")
		g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
		g.P("e.StringMap(", access, ")")
		g.P("}")
		return
	}

	if field.Desc.IsList() {
		generateListMarshal(g, helperPackage, field, access, name)
		return
	}

	switch field.Desc.Kind() {
	case protoreflect.StringKind:
		g.P("if ", access, " != \"\" {")
		g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
		g.P("e.String(", access, ")")
		g.P("}")
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		g.P("if ", access, " != 0 {")
		g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
		g.P("e.Int32(", access, ")")
		g.P("}")
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		g.P("if ", access, " != 0 {")
		g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
		g.P("e.Int64String(", access, ")")
		g.P("}")
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		g.P("if ", access, " != 0 {")
		g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
		g.P("e.Uint32(", access, ")")
		g.P("}")
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		g.P("if ", access, " != 0 {")
		g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
		g.P("e.Uint64String(", access, ")")
		g.P("}")
	case protoreflect.FloatKind:
		g.P("if ", access, " != 0 {")
		g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
		g.P("e.Float32(", access, ")")
		g.P("}")
	case protoreflect.DoubleKind:
		g.P("if ", access, " != 0 {")
		g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
		g.P("e.Float64(", access, ")")
		g.P("}")
	case protoreflect.BoolKind:
		g.P("if ", access, " {")
		g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
		g.P("e.Bool(", access, ")")
		g.P("}")
	case protoreflect.BytesKind:
		g.P("if len(", access, ") > 0 {")
		g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
		g.P("e.BytesField(", access, ")")
		g.P("}")
	case protoreflect.EnumKind:
		g.P("if ", access, " != 0 {")
		g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
		generateEnumMarshal(g, field, access)
		g.P("}")
	case protoreflect.MessageKind:
		generateMessageFieldMarshal(g, field, access, name)
	}
}

func generateListMarshal(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, field *protogen.Field, access, name string) {
	g.P("if len(", access, ") > 0 {")
	g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
	g.P("e.Byte('[')")
	g.P("for i, v := range ", access, " {")
	g.P("if i > 0 {")
	g.P("e.Byte(',')")
	g.P("}")
	switch field.Desc.Kind() {
	case protoreflect.StringKind:
		g.P("e.String(v)")
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		g.P("e.Int32(v)")
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		g.P("e.Int64String(v)")
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		g.P("e.Uint32(v)")
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		g.P("e.Uint64String(v)")
	case protoreflect.FloatKind:
		g.P("e.Float32(v)")
	case protoreflect.DoubleKind:
		g.P("e.Float64(v)")
	case protoreflect.BoolKind:
		g.P("e.Bool(v)")
	case protoreflect.BytesKind:
		g.P("e.BytesField(v)")
	case protoreflect.EnumKind:
		generateEnumMarshal(g, field, "v")
	case protoreflect.MessageKind:
		g.P("if v == nil {")
		g.P("e.Raw(\"null\")")
		g.P("} else if err := v.marshalProtoJSONXTo(e); err != nil {")
		g.P("return err")
		g.P("}")
	}
	g.P("}")
	g.P("e.Byte(']')")
	g.P("}")
}

func generateMessageFieldMarshal(g *protogen.GeneratedFile, field *protogen.Field, access, name string) {
	fullName := field.Message.Desc.FullName()
	g.P("if ", access, " != nil {")
	g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
	switch fullName {
	case "google.protobuf.Timestamp":
		g.P("if err := e.Timestamp(", access, ".GetSeconds(), ", access, ".GetNanos()); err != nil {")
		g.P("return err")
		g.P("}")
	case "google.protobuf.Duration":
		g.P("if err := e.Duration(", access, ".GetSeconds(), ", access, ".GetNanos()); err != nil {")
		g.P("return err")
		g.P("}")
	default:
		g.P("if err := ", access, ".marshalProtoJSONXTo(e); err != nil {")
		g.P("return err")
		g.P("}")
	}
	g.P("}")
}

func generateEnumMarshal(g *protogen.GeneratedFile, field *protogen.Field, value string) {
	g.P("switch ", value, " {")
	for _, enumValue := range field.Enum.Values {
		g.P("case ", enumValue.GoIdent, ":")
		g.P("e.String(", strconvQuote(string(enumValue.Desc.Name())), ")")
	}
	g.P("default:")
	g.P("e.Int32(int32(", value, "))")
	g.P("}")
}

func supportsGeneratedMarshal(message *protogen.Message) bool {
	for _, field := range message.Fields {
		if field.Oneof != nil {
			return false
		}
		if field.Desc.IsMap() {
			if field.Desc.MapKey().Kind() != protoreflect.StringKind || field.Desc.MapValue().Kind() != protoreflect.StringKind {
				return false
			}
			continue
		}
		if field.Desc.Kind() == protoreflect.MessageKind {
			fullName := field.Message.Desc.FullName()
			if fullName == "google.protobuf.Timestamp" || fullName == "google.protobuf.Duration" {
				continue
			}
			if field.Message.GoIdent.GoImportPath != message.GoIdent.GoImportPath {
				return false
			}
			if !supportsGeneratedMarshal(field.Message) {
				return false
			}
		}
	}
	return true
}

func supportsGeneratedUnmarshal(message *protogen.Message) bool {
	return supportsGeneratedMarshal(message)
}

func strconvQuote(s string) string {
	b := make([]byte, 0, len(s)+2)
	b = append(b, '"')
	for i := 0; i < len(s); i++ {
		switch c := s[i]; c {
		case '\\', '"':
			b = append(b, '\\', c)
		case '\n':
			b = append(b, '\\', 'n')
		case '\r':
			b = append(b, '\\', 'r')
		case '\t':
			b = append(b, '\\', 't')
		default:
			b = append(b, c)
		}
	}
	b = append(b, '"')
	return string(b)
}
