package main

import (
	"flag"
	"fmt"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/pluginpb"
)

const generatedCodeVersion = "0.1.0"

func main() {
	var flags flag.FlagSet
	opts := protogen.Options{
		ParamFunc: flags.Set,
	}

	opts.Run(func(gen *protogen.Plugin) error {
		currentPlugin = gen
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, file := range gen.Files {
			if file.Generate {
				generateFile(gen, file)
			}
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + ".protojsonx.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	helperPackage := protogen.GoImportPath("github.com/sudorandom/protojsonx/protojsonxgen")

	g.P("// Code generated by protoc-gen-go-protojsonx. DO NOT EDIT.")
	g.P("// versions:")
	g.P("// \tprotoc-gen-go-protojsonx v", generatedCodeVersion)
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.P("// This file is a placeholder for schema-specific protojsonx code.")
	g.P("// The generator is wired through protogen.Options so it follows the same")
	g.P("// module= and import-path behavior as protoc-gen-go.")
	g.P("const _ = ", strconvQuote("protojsonx generated scaffold "+generatedCodeVersion))
	g.P()

	for _, message := range file.Messages {
		generateMessage(g, helperPackage, message)
	}

	for _, enum := range collectEnums(file) {
		generateEnumHelper(g, helperPackage, enum)
	}
}

func generateMessage(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, message *protogen.Message) {
	if message.Desc.IsMapEntry() {
		return
	}

	if supportsGeneratedMarshal(message) {
		g.P("func (x *", message.GoIdent, ") ProtoJSONXFastPath() {}")
		g.P()
	}

	g.P("func (x *", message.GoIdent, ") MarshalProtoJSONX() ([]byte, error) {")
	if supportsGeneratedMarshal(message) {
		g.P("e := ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "NewEncoder"}), "()")
		g.P("if err := x.marshalProtoJSONXTo(e); err != nil {")
		g.P("return nil, err")
		g.P("}")
		g.P("return e.Bytes(), nil")
	} else {
		g.P("return ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "Marshal"}), "(x)")
	}
	g.P("}")
	g.P()
	g.P("func (x *", message.GoIdent, ") UnmarshalProtoJSONX(data []byte) error {")
	g.P("return x.UnmarshalProtoJSONXWithOptions(data, false)")
	g.P("}")
	g.P()
	g.P("func (x *", message.GoIdent, ") UnmarshalProtoJSONXWithOptions(data []byte, discardUnknown bool) error {")
	if supportsGeneratedUnmarshal(message) {
		decoderIdent := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "NewDecoder"})
		g.P("d := ", decoderIdent, "(data)")
		g.P("*x = ", message.GoIdent, "{}")
		if len(message.Fields) > 0 {
			// C: peek the first key so we skip the fast-path attempt entirely
			// when the input is shuffled, saving a Mark/Reset/re-zero roundtrip.
			field0JSON := message.Fields[0].Desc.JSONName()
			g.P("firstKey, savedOff, savedDepth, _, peekErr := d.PeekObjectFieldName()")
			g.P("if peekErr != nil { return peekErr }")
			g.P("if firstKey == ", strconvQuote(field0JSON), " || firstKey == \"\" {")
			g.P("d.Reset(savedOff, savedDepth)")
			g.P("if ok, err := x.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {")
			g.P("return err")
			g.P("} else if ok {")
			g.P("return d.Finish()")
			g.P("}")
			g.P("*x = ", message.GoIdent, "{}")
			g.P("}")
			g.P("d.Reset(savedOff, savedDepth)")
		} else {
			// No fields: fast path handles empty objects; just try it directly.
			g.P("off, depth := d.Mark()")
			g.P("if ok, err := x.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {")
			g.P("return err")
			g.P("} else if ok {")
			g.P("return d.Finish()")
			g.P("}")
			g.P("d.Reset(off, depth)")
		}
		g.P("if err := x.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {")
		g.P("return err")
		g.P("}")
		g.P("return d.Finish()")
	} else {
		g.P("return ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "Unmarshal"}), "(data, x)")
	}
	g.P("}") 
	g.P()

	if supportsGeneratedMarshal(message) {
		generateMessageMarshalTo(g, helperPackage, message)
	}
	if supportsGeneratedUnmarshal(message) {
		generateMessageUnmarshalFast(g, helperPackage, message)
		if len(message.Fields) >= mapDispatchThreshold {
			generateFieldIndexMap(g, message)
		}
		generateMessageUnmarshalFrom(g, helperPackage, message)
	}

	for _, nested := range message.Messages {
		generateMessage(g, helperPackage, nested)
	}
}

func generateMessageUnmarshalFast(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, message *protogen.Message) {
	decoderIdent := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "Decoder"})
	g.P("func (x *", message.GoIdent, ") unmarshalProtoJSONXFast(d *", decoderIdent, ", discardUnknown bool) (bool, error) {")
	g.P("if err := d.BeginObject(); err != nil {")
	g.P("return false, err")
	g.P("}")
	hasNonSyntheticOneof := false
	for _, oo := range message.Oneofs {
		if !oo.Desc.IsSynthetic() {
			hasNonSyntheticOneof = true
			break
		}
	}
	if hasNonSyntheticOneof {
		if len(message.Oneofs) > 64 {
			g.P("seenOneofs := make([]bool, ", len(message.Oneofs), ")")
		} else {
			g.P("var seenOneofs uint64")
		}
	}
	if len(message.Fields) > 0 {
		g.P("fastFirst := true")
	}
	for _, field := range message.Fields {
		g.P("{")
		g.P("status, err := d.MatchFast(&fastFirst, ", strconvQuote(field.Desc.JSONName()), ")")
		g.P("if err != nil { return false, err }")
		g.P("if status == 0 { return true, nil }")
		g.P("if status < 0 { return false, nil }")
		generateFieldUnmarshalFast(g, helperPackage, field)
		g.P("}")
	}
	g.P("done, err := d.TryEndObject()")
	g.P("if err != nil {")
	g.P("return false, err")
	g.P("}")
	g.P("if !done {")
	g.P("return false, nil")
	g.P("}")
	g.P("return true, nil")
	g.P("}")
	g.P()
}

func generateFieldUnmarshalFast(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, field *protogen.Field) {
	access := "x." + field.GoName
	if field.Desc.IsMap() {
		g.P("if d.ReadNull() {")
		g.P(access, " = nil")
		g.P("} else {")
		keyKind := field.Desc.MapKey().Kind()
		valKind := field.Desc.MapValue().Kind()
		if keyKind == protoreflect.StringKind && valKind == protoreflect.StringKind {
			g.P("m := make(map[string]string)")
			g.P("if err := d.BeginObject(); err != nil { return false, err }")
			g.P("mapFirst := true")
			g.P("for {")
			g.P("k, mapOK, err := d.NextObjectKey(&mapFirst)")
			g.P("if err != nil { return false, err }")
			g.P("if !mapOK { break }")
			g.P("v, err := d.ReadString()")
			g.P("if err != nil { return false, err }")
			g.P("if _, exists := m[k]; exists { return false, ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "DuplicateField"}), "(k) }")
			g.P("m[k] = v")
			g.P("}")
			g.P(access, " = m")
		} else {
			keyType := mapKeyGoType(keyKind)
			valType := mapValueGoType(g, field)
			g.P("m := make(map[", keyType, "]", valType, ")")
			g.P("if err := ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "ReadMap"}), "(d, m,")
			g.P(mapKeyParseExpr(g, keyKind), ",")
			g.P(mapValueDecoderExpr(g, field.Desc.MapValue()), "); err != nil { return false, err }")
			g.P(access, " = m")
		}
		g.P("}")
		return
	}
	if field.Desc.IsList() {
		g.P("if d.ReadNull() {")
		g.P(access, " = nil")
		g.P("} else {")
		generateListValuesInit(g, field, access)
		g.P("if err := d.BeginArray(); err != nil { return false, err }")
		g.P("arrayFirst := true")
		g.P("for {")
		g.P("elemOK, err := d.NextArrayElement(&arrayFirst)")
		g.P("if err != nil { return false, err }")
		g.P("if !elemOK { break }")
		if field.Desc.Kind() == protoreflect.MessageKind {
			g.P("if d.ReadNull() { return false, ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "NullRepeatedMessage"}), "() }")
		}
		if field.Desc.Kind() == protoreflect.EnumKind {
			g.P("val, err := unmarshalEnum_", field.Enum.GoIdent.GoName, "(d)")
			g.P("if err != nil {")
			g.P("if err == ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "ErrUnknownEnum"}), " && discardUnknown {")
			g.P("} else {")
			g.P("return false, err")
			g.P("}")
			g.P("} else {")
			g.P("values = append(values, val)")
			g.P("}")
		} else {
			generateScalarOrMessageReadFast(g, helperPackage, field, "v", true)
			g.P("values = append(values, v)")
		}
		g.P("}")
		g.P(access, " = values")
		g.P("}")
		return
	}
	if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
		g.P("if d.ReadNull() {")
		if isWKTValue(field) {
			nullValueIdent := protogen.GoIdent{
				GoImportPath: "google.golang.org/protobuf/types/known/structpb",
				GoName:       "NewNullValue",
			}
			g.P("x.", field.Oneof.GoName, " = &", field.GoIdent, "{", field.GoName, ": ", g.QualifiedGoIdent(nullValueIdent), "()}")
		} else if isWKTNullValue(field) {
			g.P("x.", field.Oneof.GoName, " = &", field.GoIdent, "{", field.GoName, ": 0}")
		} else {
			g.P("if _, ok := x.", field.Oneof.GoName, ".(*", field.GoIdent, "); ok {")
			g.P("x.", field.Oneof.GoName, " = nil")
			g.P("}")
		}
		g.P("} else {")
		oneofIndex := -1
		for idx, oo := range field.Parent.Oneofs {
			if oo == field.Oneof {
				oneofIndex = idx
				break
			}
		}
		if len(field.Parent.Oneofs) > 64 {
			g.P("if seenOneofs[", oneofIndex, "] {")
			g.P("return false, ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "DuplicateField"}), "(", strconvQuote(field.Desc.JSONName()), ")")
			g.P("}")
			g.P("seenOneofs[", oneofIndex, "] = true")
		} else {
			g.P("if seenOneofs & (1 << ", oneofIndex, ") != 0 {")
			g.P("return false, ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "DuplicateField"}), "(", strconvQuote(field.Desc.JSONName()), ")")
			g.P("}")
			g.P("seenOneofs |= (1 << ", oneofIndex, ")")
		}
		generateScalarOrMessageReadFast(g, helperPackage, field, "v", true)
		g.P("x.", field.Oneof.GoName, " = &", field.GoIdent, "{", field.GoName, ": v}")
		g.P("}")
		return
	}
	isProto3Optional := field.Oneof != nil && field.Oneof.Desc.IsSynthetic()
	g.P("if d.ReadNull() {")
	if isWKTValue(field) {
		nullValueIdent := protogen.GoIdent{
			GoImportPath: "google.golang.org/protobuf/types/known/structpb",
			GoName:       "NewNullValue",
		}
		g.P(access, " = ", g.QualifiedGoIdent(nullValueIdent), "()")
	} else {
		if isProto3Optional {
			g.P(access, " = nil")
		} else {
			g.P(access, " = ", zeroValue(field))
		}
	}
	g.P("} else {")
	generateScalarOrMessageReadFast(g, helperPackage, field, access, false)
	g.P("}")
}

func generateScalarOrMessageReadFast(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, field *protogen.Field, target string, declare bool) {
	readTarget := target
	if !declare && field.Desc.Kind() != protoreflect.MessageKind {
		readTarget = "v"
	}
	switch field.Desc.Kind() {
	case protoreflect.StringKind:
		g.P(readTarget, ", err := d.ReadString()")
		g.P("if err != nil { return false, err }")
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		g.P(readTarget, ", err := d.ReadInt32()")
		g.P("if err != nil { return false, err }")
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		g.P(readTarget, ", err := d.ReadInt64()")
		g.P("if err != nil { return false, err }")
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		g.P(readTarget, ", err := d.ReadUint32()")
		g.P("if err != nil { return false, err }")
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		g.P(readTarget, ", err := d.ReadUint64()")
		g.P("if err != nil { return false, err }")
	case protoreflect.FloatKind:
		g.P(readTarget, ", err := d.ReadFloat32()")
		g.P("if err != nil { return false, err }")
	case protoreflect.DoubleKind:
		g.P(readTarget, ", err := d.ReadFloat64()")
		g.P("if err != nil { return false, err }")
	case protoreflect.BoolKind:
		g.P(readTarget, ", err := d.ReadBool()")
		g.P("if err != nil { return false, err }")
	case protoreflect.BytesKind:
		g.P(readTarget, ", err := d.ReadBytes()")
		g.P("if err != nil { return false, err }")
	case protoreflect.EnumKind:
		generateEnumUnmarshalFast(g, helperPackage, field, target, declare)
	case protoreflect.MessageKind:
		generateMessageUnmarshalFastField(g, helperPackage, field, target, declare)
	}
	if !declare && field.Desc.Kind() != protoreflect.MessageKind && field.Desc.Kind() != protoreflect.EnumKind {
		if field.Oneof != nil && field.Oneof.Desc.IsSynthetic() {
			g.P(target, " = &v")
		} else {
			g.P(target, " = v")
		}
	}
}

func generateEnumUnmarshalFast(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, field *protogen.Field, target string, declare bool) {
	readTarget := target
	if !declare {
		readTarget = "v"
	}
	g.P("var ", readTarget, " ", field.Enum.GoIdent)
	g.P("val, err := unmarshalEnum_", field.Enum.GoIdent.GoName, "(d)")
	g.P("if err != nil {")
	g.P("if err == ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "ErrUnknownEnum"}), " && discardUnknown {")
	g.P("} else {")
	g.P("return false, err")
	g.P("}")
	g.P("} else {")
	g.P(readTarget, " = val")
	g.P("}")
	if !declare {
		if field.Oneof != nil && field.Oneof.Desc.IsSynthetic() {
			g.P(target, " = &", readTarget)
		} else {
			g.P(target, " = ", readTarget)
		}
	}
}

func generateMessageUnmarshalFastField(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, field *protogen.Field, target string, declare bool) {
	fullName := field.Message.Desc.FullName()
	if fullName == "google.protobuf.Timestamp" || fullName == "google.protobuf.Duration" {
		if declare {
			g.P("var ", target, " *", field.Message.GoIdent)
		}
		if fullName == "google.protobuf.Timestamp" {
			g.P("secs, nanos, err := d.ReadTimestamp()")
		} else {
			g.P("secs, nanos, err := d.ReadDuration()")
		}
		g.P("if err != nil { return false, err }")
		g.P(target, " = &", field.Message.GoIdent, "{Seconds: secs, Nanos: nanos}")
		return
	}
	if declare {
		g.P(target, " := &", field.Message.GoIdent, "{}")
	} else {
		g.P(target, " = &", field.Message.GoIdent, "{}")
	}
	g.P("if fast, ok := any(", target, ").(interface{ unmarshalProtoJSONXFast(*", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "Decoder"}), ", bool) (bool, error) }); ok {")
	g.P("if ok, err := fast.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {")
	g.P("return false, err")
	g.P("} else if !ok {")
	g.P("return false, nil")
	g.P("}")
	g.P("} else {")
	g.P("if err := ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "UnmarshalField"}), "(d, ", target, ", discardUnknown); err != nil { return false, err }")
	g.P("}")
}

// mapDispatchThreshold is the minimum number of fields at which we switch
// from a linear switch-string fallback to a map[string]int + switch-int
// dispatch. The map gives O(1) key lookup; the integer switch compiles to a
// CPU jump table so field handling stays fully inlined (no indirect calls,
// no *uint64 pointer aliasing). Below the threshold the switch-string is
// faster due to cache effects and zero hash overhead.
// mapDispatchThreshold is the minimum number of fields at which we switch
// from a linear switch-string fallback to a map[string]int + switch-int
// dispatch. The map gives O(1) key lookup; the integer switch compiles to a
// CPU jump table so field handling stays fully inlined (no indirect calls,
// no *uint64 pointer aliasing).
//
// Benchmarks on arm64 (M1 Pro) showed that the Go runtime's map hash overhead
// exceeds the SIMD string comparison savings for messages up to ~22 fields.
// The threshold is set conservatively high; lower it when messages with
// 30+ fields are benchmarked and confirmed to improve.
const mapDispatchThreshold = 32



// generateFieldIndexMap emits a package-level map[string]int that maps every
// known JSON key (camelCase and proto snake_case) to its zero-based field
// index. The index drives an integer switch in unmarshalProtoJSONXFrom, which
// the Go compiler lowers to a jump table — giving O(1) dispatch without any
// indirect function calls.
func generateFieldIndexMap(g *protogen.GeneratedFile, message *protogen.Message) {
	g.P("var _", message.GoIdent.GoName, "FieldIndex = map[string]int{")
	for i, field := range message.Fields {
		jsonName := field.Desc.JSONName()
		protoName := string(field.Desc.Name())
		g.P(strconvQuote(jsonName), ": ", i, ",")
		if jsonName != protoName {
			g.P(strconvQuote(protoName), ": ", i, ",")
		}
	}
	g.P("}")
	g.P()
}

func generateMessageUnmarshalFrom(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, message *protogen.Message) {
	decoderIdent := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "Decoder"})
	g.P("func (x *", message.GoIdent, ") unmarshalProtoJSONXFrom(d *", decoderIdent, ", discardUnknown bool) error {")
	g.P("if err := d.BeginObject(); err != nil {")
	g.P("return err")
	g.P("}")
	hasNonSyntheticOneof := false
	for _, oo := range message.Oneofs {
		if !oo.Desc.IsSynthetic() {
			hasNonSyntheticOneof = true
			break
		}
	}
	if hasNonSyntheticOneof {
		if len(message.Oneofs) > 64 {
			g.P("seenOneofs := make([]bool, ", len(message.Oneofs), ")")
		} else {
			g.P("var seenOneofs uint64")
		}
	}
	if len(message.Fields) > 0 {
		g.P("var seen [", len(message.Fields), "]bool")
	}
	g.P("first := true")
	g.P("for {")
	g.P("key, ok, err := d.NextObjectKey(&first)")
	g.P("if err != nil {")
	g.P("return err")
	g.P("}")
	g.P("if !ok {")
	g.P("return nil")
	g.P("}")
	unknownField := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "UnknownField"})
	if len(message.Fields) >= mapDispatchThreshold {
		// A: O(1) map lookup drives an integer jump table. Field handling is
		// emitted inline inside the switch so the compiler can optimise each
		// case independently — no indirect calls, no *uint64 aliasing.
		g.P("idx, hit := _", message.GoIdent.GoName, "FieldIndex[key]")
		g.P("if !hit {")
		g.P("if discardUnknown {")
		g.P("if err := d.SkipValue(); err != nil { return err }")
		g.P("continue")
		g.P("} else {")
		g.P("return ", unknownField, "(key)")
		g.P("}")
		g.P("}")
		g.P("switch idx {")
		for i, field := range message.Fields {
			g.P("case ", i, ":")
			generateSeenCheck(g, helperPackage, i)
			generateFieldUnmarshal(g, helperPackage, field)
			g.P("continue")
		}
		g.P("}")
	} else {
		// Narrow messages: switch-string (better cache behaviour
		// than a map at low field counts).
		g.P("switch key {")
		for i, field := range message.Fields {
			jsonName := field.Desc.JSONName()
			protoName := string(field.Desc.Name())
			if jsonName == protoName {
				g.P("case ", strconvQuote(jsonName), ":")
			} else {
				g.P("case ", strconvQuote(jsonName), ", ", strconvQuote(protoName), ":")
			}
			generateSeenCheck(g, helperPackage, i)
			generateFieldUnmarshal(g, helperPackage, field)
			g.P("continue")
		}
		g.P("default:")
		g.P("if discardUnknown {")
		g.P("if err := d.SkipValue(); err != nil { return err }")
		g.P("} else {")
		g.P("return ", unknownField, "(key)")
		g.P("}")
		g.P("}")
	}
	g.P("}")
	g.P("}")
	g.P()
}



func generateSeenCheck(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, index int) {
	duplicate := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "DuplicateField"})
	g.P("if seen[", index, "] {")
	g.P("return ", duplicate, "(key)")
	g.P("}")
	g.P("seen[", index, "] = true")
}

func generateFieldUnmarshal(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, field *protogen.Field) {
	access := "x." + field.GoName
	if field.Desc.IsMap() {
		g.P("if d.ReadNull() {")
		g.P(access, " = nil")
		g.P("} else {")
		keyKind := field.Desc.MapKey().Kind()
		valKind := field.Desc.MapValue().Kind()
		if keyKind == protoreflect.StringKind && valKind == protoreflect.StringKind {
			g.P("m := make(map[string]string)")
			g.P("if err := d.BeginObject(); err != nil {")
			g.P("return err")
			g.P("}")
			g.P("mapFirst := true")
			g.P("for {")
			g.P("k, mapOK, err := d.NextObjectKey(&mapFirst)")
			g.P("if err != nil {")
			g.P("return err")
			g.P("}")
			g.P("if !mapOK {")
			g.P("break")
			g.P("}")
			g.P("v, err := d.ReadString()")
			g.P("if err != nil {")
			g.P("return err")
			g.P("}")
			g.P("if _, exists := m[k]; exists {")
			g.P("return ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "DuplicateField"}), "(k)")
			g.P("}")
			g.P("m[k] = v")
			g.P("}")
			g.P(access, " = m")
		} else {
			keyType := mapKeyGoType(keyKind)
			valType := mapValueGoType(g, field)
			g.P("m := make(map[", keyType, "]", valType, ")")
			g.P("if err := ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "ReadMap"}), "(d, m,")
			g.P(mapKeyParseExpr(g, keyKind), ",")
			g.P(mapValueDecoderExpr(g, field.Desc.MapValue()), "); err != nil {")
			g.P("return err")
			g.P("}")
			g.P(access, " = m")
		}
		g.P("}")
		return
	}
	if field.Desc.IsList() {
		generateListUnmarshal(g, helperPackage, field, access)
		return
	}
	if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
		g.P("if d.ReadNull() {")
		if isWKTValue(field) {
			nullValueIdent := protogen.GoIdent{
				GoImportPath: "google.golang.org/protobuf/types/known/structpb",
				GoName:       "NewNullValue",
			}
			g.P("x.", field.Oneof.GoName, " = &", field.GoIdent, "{", field.GoName, ": ", g.QualifiedGoIdent(nullValueIdent), "()}")
		} else if isWKTNullValue(field) {
			g.P("x.", field.Oneof.GoName, " = &", field.GoIdent, "{", field.GoName, ": 0}")
		} else {
			g.P("if _, ok := x.", field.Oneof.GoName, ".(*", field.GoIdent, "); ok {")
			g.P("x.", field.Oneof.GoName, " = nil")
			g.P("}")
		}
		g.P("} else {")
		oneofIndex := -1
		for idx, oo := range field.Parent.Oneofs {
			if oo == field.Oneof {
				oneofIndex = idx
				break
			}
		}
		if len(field.Parent.Oneofs) > 64 {
			g.P("if seenOneofs[", oneofIndex, "] {")
			g.P("return ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "DuplicateField"}), "(key)")
			g.P("}")
			g.P("seenOneofs[", oneofIndex, "] = true")
		} else {
			g.P("if seenOneofs & (1 << ", oneofIndex, ") != 0 {")
			g.P("return ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "DuplicateField"}), "(key)")
			g.P("}")
			g.P("seenOneofs |= (1 << ", oneofIndex, ")")
		}
		generateScalarOrMessageRead(g, helperPackage, field, "v", true)
		g.P("x.", field.Oneof.GoName, " = &", field.GoIdent, "{", field.GoName, ": v}")
		g.P("}")
		return
	}
	isProto3Optional := field.Oneof != nil && field.Oneof.Desc.IsSynthetic()
	g.P("if d.ReadNull() {")
	if isWKTValue(field) {
		nullValueIdent := protogen.GoIdent{
			GoImportPath: "google.golang.org/protobuf/types/known/structpb",
			GoName:       "NewNullValue",
		}
		g.P(access, " = ", g.QualifiedGoIdent(nullValueIdent), "()")
	} else {
		if isProto3Optional {
			g.P(access, " = nil")
		} else {
			g.P(access, " = ", zeroValue(field))
		}
	}
	g.P("} else {")
	generateScalarOrMessageRead(g, helperPackage, field, access, false)
	g.P("}")
}

func generateListUnmarshal(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, field *protogen.Field, access string) {
	g.P("if d.ReadNull() {")
	g.P(access, " = nil")
	g.P("} else {")
	generateListValuesInit(g, field, access)
	g.P("if err := d.BeginArray(); err != nil {")
	g.P("return err")
	g.P("}")
	g.P("arrayFirst := true")
	g.P("for {")
	g.P("elemOK, err := d.NextArrayElement(&arrayFirst)")
	g.P("if err != nil {")
	g.P("return err")
	g.P("}")
	g.P("if !elemOK {")
	g.P("break")
	g.P("}")
	if field.Desc.Kind() == protoreflect.MessageKind {
		g.P("if d.ReadNull() {")
		g.P("return ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "NullRepeatedMessage"}), "()")
		g.P("}")
		generateScalarOrMessageRead(g, helperPackage, field, "v", true)
		g.P("values = append(values, v)")
	} else if field.Desc.Kind() == protoreflect.EnumKind {
		g.P("val, err := unmarshalEnum_", field.Enum.GoIdent.GoName, "(d)")
		g.P("if err != nil {")
		g.P("if err == ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "ErrUnknownEnum"}), " && discardUnknown {")
		g.P("} else {")
		g.P("return err")
		g.P("}")
		g.P("} else {")
		g.P("values = append(values, val)")
		g.P("}")
	} else {
		generateScalarOrMessageRead(g, helperPackage, field, "v", true)
		g.P("values = append(values, v)")
	}
	g.P("}")
	g.P(access, " = values")
	g.P("}")
}

func generateListValuesInit(g *protogen.GeneratedFile, field *protogen.Field, access string) {
	g.P("values := ", access, "[:0]")
	g.P("if values == nil {")
	g.P("values = make([]", listElementGoType(g, field), ", 0, 4)")
	g.P("}")
}

func listElementGoType(g *protogen.GeneratedFile, field *protogen.Field) string {
	switch field.Desc.Kind() {
	case protoreflect.BoolKind:
		return "bool"
	case protoreflect.StringKind:
		return "string"
	case protoreflect.BytesKind:
		return "[]byte"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "int32"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "int64"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "uint32"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "uint64"
	case protoreflect.FloatKind:
		return "float32"
	case protoreflect.DoubleKind:
		return "float64"
	case protoreflect.EnumKind:
		return g.QualifiedGoIdent(field.Enum.GoIdent)
	case protoreflect.MessageKind:
		return "*" + g.QualifiedGoIdent(field.Message.GoIdent)
	default:
		return "any"
	}
}

func generateScalarOrMessageRead(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, field *protogen.Field, target string, declare bool) {
	readTarget := target
	if !declare && field.Desc.Kind() != protoreflect.MessageKind {
		readTarget = "v"
	}
	switch field.Desc.Kind() {
	case protoreflect.StringKind:
		g.P(readTarget, ", err := d.ReadString()")
		g.P("if err != nil { return err }")
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		g.P(readTarget, ", err := d.ReadInt32()")
		g.P("if err != nil { return err }")
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		g.P(readTarget, ", err := d.ReadInt64()")
		g.P("if err != nil { return err }")
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		g.P(readTarget, ", err := d.ReadUint32()")
		g.P("if err != nil { return err }")
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		g.P(readTarget, ", err := d.ReadUint64()")
		g.P("if err != nil { return err }")
	case protoreflect.FloatKind:
		g.P(readTarget, ", err := d.ReadFloat32()")
		g.P("if err != nil { return err }")
	case protoreflect.DoubleKind:
		g.P(readTarget, ", err := d.ReadFloat64()")
		g.P("if err != nil { return err }")
	case protoreflect.BoolKind:
		g.P(readTarget, ", err := d.ReadBool()")
		g.P("if err != nil { return err }")
	case protoreflect.BytesKind:
		g.P(readTarget, ", err := d.ReadBytes()")
		g.P("if err != nil { return err }")
	case protoreflect.EnumKind:
		generateEnumUnmarshal(g, helperPackage, field, target, declare)
	case protoreflect.MessageKind:
		generateMessageUnmarshal(g, helperPackage, field, target, declare)
	}
	if !declare && field.Desc.Kind() != protoreflect.MessageKind && field.Desc.Kind() != protoreflect.EnumKind {
		if field.Oneof != nil && field.Oneof.Desc.IsSynthetic() {
			g.P(target, " = &v")
		} else {
			g.P(target, " = v")
		}
	}
}

func generateEnumUnmarshal(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, field *protogen.Field, target string, declare bool) {
	readTarget := target
	if !declare {
		readTarget = "v"
	}
	g.P("var ", readTarget, " ", field.Enum.GoIdent)
	g.P("val, err := unmarshalEnum_", field.Enum.GoIdent.GoName, "(d)")
	g.P("if err != nil {")
	g.P("if err == ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "ErrUnknownEnum"}), " && discardUnknown {")
	g.P("} else {")
	g.P("return err")
	g.P("}")
	g.P("} else {")
	g.P(readTarget, " = val")
	g.P("}")
	if !declare {
		if field.Oneof != nil && field.Oneof.Desc.IsSynthetic() {
			g.P(target, " = &", readTarget)
		} else {
			g.P(target, " = ", readTarget)
		}
	}
}

func generateMessageUnmarshal(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, field *protogen.Field, target string, declare bool) {
	fullName := field.Message.Desc.FullName()
	if fullName == "google.protobuf.Timestamp" || fullName == "google.protobuf.Duration" {
		if declare {
			g.P("var ", target, " *", field.Message.GoIdent)
		}
		if fullName == "google.protobuf.Timestamp" {
			g.P("secs, nanos, err := d.ReadTimestamp()")
		} else {
			g.P("secs, nanos, err := d.ReadDuration()")
		}
		g.P("if err != nil { return err }")
		g.P(target, " = &", field.Message.GoIdent, "{Seconds: secs, Nanos: nanos}")
		return
	}
	if declare {
		g.P(target, " := &", field.Message.GoIdent, "{}")
	} else {
		g.P(target, " = &", field.Message.GoIdent, "{}")
	}
	g.P("if slow, ok := any(", target, ").(interface{ unmarshalProtoJSONXFrom(*", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "Decoder"}), ", bool) error }); ok {")
	g.P("if err := slow.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {")
	g.P("return err")
	g.P("}")
	g.P("} else {")
	g.P("if err := ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "UnmarshalField"}), "(d, ", target, ", discardUnknown); err != nil { return err }")
	g.P("}")
}

func zeroValue(field *protogen.Field) string {
	if field.Desc.IsList() || field.Desc.IsMap() {
		return "nil"
	}
	switch field.Desc.Kind() {
	case protoreflect.StringKind:
		return "\"\""
	case protoreflect.BoolKind:
		return "false"
	case protoreflect.BytesKind, protoreflect.MessageKind:
		return "nil"
	default:
		return "0"
	}
}

func generateMessageMarshalTo(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, message *protogen.Message) {
	encoderIdent := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "Encoder"})
	g.P("func (x *", message.GoIdent, ") marshalProtoJSONXTo(e *", encoderIdent, ") error {")
	g.P("e.Byte('{')")
	if len(message.Fields) > 0 {
		g.P("wrote := false")
	}
	for _, field := range message.Fields {
		generateFieldMarshal(g, helperPackage, field)
	}
	g.P("e.Byte('}')")
	g.P("return nil")
	g.P("}")
	g.P()
}

func generateFieldMarshal(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, field *protogen.Field) {
	if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
		g.P("if w, ok := x.", field.Oneof.GoName, ".(*", field.GoIdent, "); ok {")
		g.P("_ = w")
		generateFieldMarshalBody(g, helperPackage, field, "w."+field.GoName, true)
		g.P("}")
		return
	}
	generateFieldMarshalBody(g, helperPackage, field, "x."+field.GoName, false)
}

func generateFieldMarshalBody(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, field *protogen.Field, access string, isOneof bool) {
	name := field.Desc.JSONName()

	if field.Desc.IsMap() {
		g.P("if len(", access, ") > 0 {")
		g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
		keyKind := field.Desc.MapKey().Kind()
		valKind := field.Desc.MapValue().Kind()
		if keyKind == protoreflect.StringKind && valKind == protoreflect.StringKind {
			g.P("e.StringMap(", access, ")")
		} else {
			g.P("if err := ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "WriteMap"}), "(e, ", access, ",")
			g.P(mapKeyToStringExpr(g, keyKind), ",")
			g.P(mapValueEncoderExpr(g, field.Desc.MapValue()), "); err != nil {")
			g.P("return err")
			g.P("}")
		}
		g.P("}")
		return
	}

	if field.Desc.IsList() {
		generateListMarshal(g, helperPackage, field, access, name)
		return
	}

	isProto3Optional := field.Oneof != nil && field.Oneof.Desc.IsSynthetic()
	valExpr := access
	if isProto3Optional {
		valExpr = "*" + access
	}

	switch field.Desc.Kind() {
	case protoreflect.StringKind:
		if !isOneof {
			if isProto3Optional {
				g.P("if ", access, " != nil {")
			} else {
				g.P("if ", access, " != \"\" {")
			}
		}
		g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
		g.P("e.String(", valExpr, ")")
		if !isOneof {
			g.P("}")
		}
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		if !isOneof {
			if isProto3Optional {
				g.P("if ", access, " != nil {")
			} else {
				g.P("if ", access, " != 0 {")
			}
		}
		g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
		g.P("e.Int32(", valExpr, ")")
		if !isOneof {
			g.P("}")
		}
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		if !isOneof {
			if isProto3Optional {
				g.P("if ", access, " != nil {")
			} else {
				g.P("if ", access, " != 0 {")
			}
		}
		g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
		g.P("e.Int64String(", valExpr, ")")
		if !isOneof {
			g.P("}")
		}
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		if !isOneof {
			if isProto3Optional {
				g.P("if ", access, " != nil {")
			} else {
				g.P("if ", access, " != 0 {")
			}
		}
		g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
		g.P("e.Uint32(", valExpr, ")")
		if !isOneof {
			g.P("}")
		}
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		if !isOneof {
			if isProto3Optional {
				g.P("if ", access, " != nil {")
			} else {
				g.P("if ", access, " != 0 {")
			}
		}
		g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
		g.P("e.Uint64String(", valExpr, ")")
		if !isOneof {
			g.P("}")
		}
	case protoreflect.FloatKind:
		if !isOneof {
			if isProto3Optional {
				g.P("if ", access, " != nil {")
			} else {
				g.P("if ", access, " != 0 {")
			}
		}
		g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
		g.P("e.Float32(", valExpr, ")")
		if !isOneof {
			g.P("}")
		}
	case protoreflect.DoubleKind:
		if !isOneof {
			if isProto3Optional {
				g.P("if ", access, " != nil {")
			} else {
				g.P("if ", access, " != 0 {")
			}
		}
		g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
		g.P("e.Float64(", valExpr, ")")
		if !isOneof {
			g.P("}")
		}
	case protoreflect.BoolKind:
		if !isOneof {
			if isProto3Optional {
				g.P("if ", access, " != nil {")
			} else {
				g.P("if ", access, " {")
			}
		}
		g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
		g.P("e.Bool(", valExpr, ")")
		if !isOneof {
			g.P("}")
		}
	case protoreflect.BytesKind:
		if !isOneof {
			g.P("if len(", access, ") > 0 {")
		}
		g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
		g.P("e.BytesField(", access, ")")
		if !isOneof {
			g.P("}")
		}
	case protoreflect.EnumKind:
		if isProto3Optional {
			g.P("if ", access, " != nil {")
			g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
			generateEnumMarshal(g, field, valExpr)
			g.P("}")
		} else {
			if !isOneof {
				g.P("if ", access, " != 0 {")
			}
			g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
			generateEnumMarshal(g, field, valExpr)
			if !isOneof {
				g.P("}")
			}
		}
	case protoreflect.MessageKind:
		generateMessageFieldMarshal(g, helperPackage, field, access, name)
	}
}

func generateListMarshal(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, field *protogen.Field, access, name string) {
	g.P("if len(", access, ") > 0 {")
	g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
	g.P("e.Byte('[')")
	g.P("for i, v := range ", access, " {")
	g.P("if i > 0 {")
	g.P("e.Byte(',')")
	g.P("}")
	switch field.Desc.Kind() {
	case protoreflect.StringKind:
		g.P("e.String(v)")
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		g.P("e.Int32(v)")
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		g.P("e.Int64String(v)")
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		g.P("e.Uint32(v)")
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		g.P("e.Uint64String(v)")
	case protoreflect.FloatKind:
		g.P("e.Float32(v)")
	case protoreflect.DoubleKind:
		g.P("e.Float64(v)")
	case protoreflect.BoolKind:
		g.P("e.Bool(v)")
	case protoreflect.BytesKind:
		g.P("e.BytesField(v)")
	case protoreflect.EnumKind:
		generateEnumMarshal(g, field, "v")
	case protoreflect.MessageKind:
		g.P("if v == nil {")
		g.P("e.Raw(\"null\")")
		g.P("} else {")
		g.P("if fast, ok := any(v).(interface{ marshalProtoJSONXTo(*", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "Encoder"}), ") error }); ok {")
		g.P("if err := fast.marshalProtoJSONXTo(e); err != nil { return err }")
		g.P("} else {")
		g.P("if err := ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "MarshalField"}), "(e, v); err != nil { return err }")
		g.P("}")
		g.P("}")
	}
	g.P("}")
	g.P("e.Byte(']')")
	g.P("}")
}

func generateMessageFieldMarshal(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, field *protogen.Field, access, name string) {
	fullName := field.Message.Desc.FullName()
	g.P("if ", access, " != nil {")
	g.P("e.FieldPrefix(&wrote, ", strconvQuote(name), ")")
	switch fullName {
	case "google.protobuf.Timestamp":
		g.P("if err := e.Timestamp(", access, ".GetSeconds(), ", access, ".GetNanos()); err != nil {")
		g.P("return err")
		g.P("}")
	case "google.protobuf.Duration":
		g.P("if err := e.Duration(", access, ".GetSeconds(), ", access, ".GetNanos()); err != nil {")
		g.P("return err")
		g.P("}")
	default:
		g.P("if fast, ok := any(", access, ").(interface{ marshalProtoJSONXTo(*", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "Encoder"}), ") error }); ok {")
		g.P("if err := fast.marshalProtoJSONXTo(e); err != nil { return err }")
		g.P("} else {")
		g.P("if err := ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "MarshalField"}), "(e, ", access, "); err != nil { return err }")
		g.P("}")
	}
	g.P("}")
}

func generateEnumMarshal(g *protogen.GeneratedFile, field *protogen.Field, value string) {
	if isWKTNullValue(field) {
		g.P("e.Raw(\"null\")")
		return
	}
	g.P("switch ", value, " {")
	seen := make(map[protoreflect.EnumNumber]bool)
	for _, enumValue := range field.Enum.Values {
		num := enumValue.Desc.Number()
		if seen[num] {
			continue
		}
		seen[num] = true
		g.P("case ", enumValue.GoIdent, ":")
		g.P("e.String(", strconvQuote(string(enumValue.Desc.Name())), ")")
	}
	g.P("default:")
	g.P("e.Int32(int32(", value, "))")
	g.P("}")
}

func supportsGeneratedMarshal(message *protogen.Message) bool {
	for _, field := range message.Fields {
		if field.Desc.IsMap() {
			keyKind := field.Desc.MapKey().Kind()
			if keyKind != protoreflect.StringKind &&
				keyKind != protoreflect.Int32Kind && keyKind != protoreflect.Int64Kind &&
				keyKind != protoreflect.Uint32Kind && keyKind != protoreflect.Uint64Kind &&
				keyKind != protoreflect.Sint32Kind && keyKind != protoreflect.Sint64Kind &&
				keyKind != protoreflect.Fixed32Kind && keyKind != protoreflect.Fixed64Kind &&
				keyKind != protoreflect.Sfixed32Kind && keyKind != protoreflect.Sfixed64Kind &&
				keyKind != protoreflect.BoolKind {
				return false
			}
			continue
		}
	}
	return true
}

func supportsGeneratedUnmarshal(message *protogen.Message) bool {
	return supportsGeneratedMarshal(message)
}

func strconvQuote(s string) string {
	b := make([]byte, 0, len(s)+2)
	b = append(b, '"')
	for i := 0; i < len(s); i++ {
		switch c := s[i]; c {
		case '\\', '"':
			b = append(b, '\\', c)
		case '\n':
			b = append(b, '\\', 'n')
		case '\r':
			b = append(b, '\\', 'r')
		case '\t':
			b = append(b, '\\', 't')
		default:
			b = append(b, c)
		}
	}
	b = append(b, '"')
	return string(b)
}

var currentPlugin *protogen.Plugin

func resolveEnumGoIdent(desc protoreflect.EnumDescriptor) protogen.GoIdent {
	if currentPlugin != nil {
		for _, f := range currentPlugin.Files {
			for _, e := range f.Enums {
				if e.Desc.FullName() == desc.FullName() {
					return e.GoIdent
				}
			}
			var searchMessages func([]*protogen.Message) *protogen.Enum
			searchMessages = func(messages []*protogen.Message) *protogen.Enum {
				for _, m := range messages {
					for _, e := range m.Enums {
						if e.Desc.FullName() == desc.FullName() {
							return e
						}
					}
					if found := searchMessages(m.Messages); found != nil {
						return found
					}
				}
				return nil
			}
			if e := searchMessages(f.Messages); e != nil {
				return e.GoIdent
			}
		}
	}
	return protogen.GoIdent{GoName: string(desc.Name())}
}

func resolveMessageGoIdent(desc protoreflect.MessageDescriptor) protogen.GoIdent {
	if currentPlugin != nil {
		for _, f := range currentPlugin.Files {
			var searchMessages func([]*protogen.Message) *protogen.Message
			searchMessages = func(messages []*protogen.Message) *protogen.Message {
				for _, m := range messages {
					if m.Desc.FullName() == desc.FullName() {
						return m
					}
					if found := searchMessages(m.Messages); found != nil {
						return found
					}
				}
				return nil
			}
			if m := searchMessages(f.Messages); m != nil {
				return m.GoIdent
			}
		}
	}
	return protogen.GoIdent{GoName: string(desc.Name())}
}



func mapValueGoType(g *protogen.GeneratedFile, field *protogen.Field) string {
	valDesc := field.Desc.MapValue()
	switch valDesc.Kind() {
	case protoreflect.BoolKind:
		return "bool"
	case protoreflect.StringKind:
		return "string"
	case protoreflect.BytesKind:
		return "[]byte"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "int32"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "int64"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "uint32"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "uint64"
	case protoreflect.FloatKind:
		return "float32"
	case protoreflect.DoubleKind:
		return "float64"
	case protoreflect.EnumKind:
		ident := resolveEnumGoIdent(valDesc.Enum())
		return g.QualifiedGoIdent(ident)
	case protoreflect.MessageKind:
		ident := resolveMessageGoIdent(valDesc.Message())
		return "*" + g.QualifiedGoIdent(ident)
	default:
		return "any"
	}
}

func mapKeyToStringExpr(g *protogen.GeneratedFile, keyKind protoreflect.Kind) string {
	strconvFormatInt := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "strconv", GoName: "FormatInt"})
	strconvFormatUint := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "strconv", GoName: "FormatUint"})
	strconvFormatBool := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "strconv", GoName: "FormatBool"})
	switch keyKind {
	case protoreflect.StringKind:
		return "func(k string) string { return k }"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return fmt.Sprintf("func(k int32) string { return %s(int64(k), 10) }", strconvFormatInt)
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return fmt.Sprintf("func(k int64) string { return %s(k, 10) }", strconvFormatInt)
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return fmt.Sprintf("func(k uint32) string { return %s(uint64(k), 10) }", strconvFormatUint)
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return fmt.Sprintf("func(k uint64) string { return %s(k, 10) }", strconvFormatUint)
	case protoreflect.BoolKind:
		return fmt.Sprintf("func(k bool) string { return %s(k) }", strconvFormatBool)
	default:
		return "nil"
	}
}

func mapValueEncoderExpr(g *protogen.GeneratedFile, valDesc protoreflect.FieldDescriptor) string {
	switch valDesc.Kind() {
	case protoreflect.StringKind:
		return "func(e *protojsonxgen.Encoder, v string) error { e.String(v); return nil }"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "func(e *protojsonxgen.Encoder, v int32) error { e.Int32(v); return nil }"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "func(e *protojsonxgen.Encoder, v int64) error { e.Int64String(v); return nil }"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "func(e *protojsonxgen.Encoder, v uint32) error { e.Uint32(v); return nil }"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "func(e *protojsonxgen.Encoder, v uint64) error { e.Uint64String(v); return nil }"
	case protoreflect.FloatKind:
		return "func(e *protojsonxgen.Encoder, v float32) error { e.Float32(v); return nil }"
	case protoreflect.DoubleKind:
		return "func(e *protojsonxgen.Encoder, v float64) error { e.Float64(v); return nil }"
	case protoreflect.BoolKind:
		return "func(e *protojsonxgen.Encoder, v bool) error { e.Bool(v); return nil }"
	case protoreflect.BytesKind:
		return "func(e *protojsonxgen.Encoder, v []byte) error { e.BytesField(v); return nil }"
	case protoreflect.EnumKind:
		enumIdent := resolveEnumGoIdent(valDesc.Enum())
		enumType := g.QualifiedGoIdent(enumIdent)
		if valDesc.Enum().FullName() == "google.protobuf.NullValue" {
			return "func(e *protojsonxgen.Encoder, v " + enumType + ") error { e.Raw(\"null\"); return nil }"
		}
		// We generate a switch to map enum values to strings
		switchBody := "switch v {\n"
		seen := make(map[protoreflect.EnumNumber]bool)
		for i := 0; i < valDesc.Enum().Values().Len(); i++ {
			ev := valDesc.Enum().Values().Get(i)
			num := ev.Number()
			if seen[num] {
				continue
			}
			seen[num] = true
			switchBody += fmt.Sprintf("\t\tcase %s:\n\t\t\te.String(%s)\n", g.QualifiedGoIdent(resolveEnumValueGoIdent(valDesc.Enum(), ev)), strconvQuote(string(ev.Name())))
		}
		switchBody += "\t\tdefault:\n\t\t\te.Int32(int32(v))\n\t\t}"
		return fmt.Sprintf("func(e *protojsonxgen.Encoder, v %s) error { %s; return nil }", enumType, switchBody)
	case protoreflect.MessageKind:
		msgFullName := valDesc.Message().FullName()
		msgIdent := resolveMessageGoIdent(valDesc.Message())
		msgType := "*" + g.QualifiedGoIdent(msgIdent)
		switch msgFullName {
		case "google.protobuf.Timestamp":
			return fmt.Sprintf("func(e *protojsonxgen.Encoder, v %s) error { if v == nil { e.Raw(\"null\"); return nil }; return e.Timestamp(v.GetSeconds(), v.GetNanos()) }", msgType)
		case "google.protobuf.Duration":
			return fmt.Sprintf("func(e *protojsonxgen.Encoder, v %s) error { if v == nil { e.Raw(\"null\"); return nil }; return e.Duration(v.GetSeconds(), v.GetNanos()) }", msgType)
		default:
			return fmt.Sprintf("protojsonxgen.MarshalMessageMapValue[%s]", msgType)
		}
	}
	return "nil"
}

func mapKeyGoType(keyKind protoreflect.Kind) string {
	switch keyKind {
	case protoreflect.StringKind:
		return "string"
	case protoreflect.BoolKind:
		return "bool"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "int32"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "int64"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "uint32"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "uint64"
	default:
		return "string"
	}
}

func mapKeyParseExpr(g *protogen.GeneratedFile, keyKind protoreflect.Kind) string {
	strconvParseBool := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "strconv", GoName: "ParseBool"})
	strconvParseInt := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "strconv", GoName: "ParseInt"})
	strconvParseUint := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: "strconv", GoName: "ParseUint"})
	switch keyKind {
	case protoreflect.StringKind:
		return "func(s string) (string, error) { return s, nil }"
	case protoreflect.BoolKind:
		return strconvParseBool
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return fmt.Sprintf("func(s string) (int32, error) { val, err := %s(s, 10, 32); return int32(val), err }", strconvParseInt)
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return fmt.Sprintf("func(s string) (int64, error) { return %s(s, 10, 64) }", strconvParseInt)
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return fmt.Sprintf("func(s string) (uint32, error) { val, err := %s(s, 10, 32); return uint32(val), err }", strconvParseUint)
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return fmt.Sprintf("func(s string) (uint64, error) { return %s(s, 10, 64) }", strconvParseUint)
	default:
		return "nil"
	}
}

func mapValueDecoderExpr(g *protogen.GeneratedFile, valDesc protoreflect.FieldDescriptor) string {
	switch valDesc.Kind() {
	case protoreflect.StringKind:
		return "func(d *protojsonxgen.Decoder) (string, error) { return d.ReadString() }"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "func(d *protojsonxgen.Decoder) (int32, error) { return d.ReadInt32() }"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "func(d *protojsonxgen.Decoder) (int64, error) { return d.ReadInt64() }"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "func(d *protojsonxgen.Decoder) (uint32, error) { return d.ReadUint32() }"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "func(d *protojsonxgen.Decoder) (uint64, error) { return d.ReadUint64() }"
	case protoreflect.FloatKind:
		return "func(d *protojsonxgen.Decoder) (float32, error) { return d.ReadFloat32() }"
	case protoreflect.DoubleKind:
		return "func(d *protojsonxgen.Decoder) (float64, error) { return d.ReadFloat64() }"
	case protoreflect.BoolKind:
		return "func(d *protojsonxgen.Decoder) (bool, error) { return d.ReadBool() }"
	case protoreflect.BytesKind:
		return "func(d *protojsonxgen.Decoder) ([]byte, error) { return d.ReadBytes() }"
	case protoreflect.EnumKind:
		enumIdent := resolveEnumGoIdent(valDesc.Enum())
		enumType := g.QualifiedGoIdent(enumIdent)
		matchStringBytes := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: protogen.GoImportPath("github.com/sudorandom/protojsonx/protojsonxgen"), GoName: "MatchStringBytes"})
		unknownEnumValue := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: protogen.GoImportPath("github.com/sudorandom/protojsonx/protojsonxgen"), GoName: "UnknownEnumValue"})
		
		body := "if d.IsString() {\n" +
			"\t\t\ts, err := d.ReadStringBytes()\n" +
			"\t\t\tif err != nil { return 0, err }\n"
		for i := 0; i < valDesc.Enum().Values().Len(); i++ {
			ev := valDesc.Enum().Values().Get(i)
			body += fmt.Sprintf("\t\t\tif %s(s, %s) {\n\t\t\t\treturn %s, nil\n\t\t\t} else ", matchStringBytes, strconvQuote(string(ev.Name())), g.QualifiedGoIdent(resolveEnumValueGoIdent(valDesc.Enum(), ev)))
		}
		errIgnoredMapEntry := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: protogen.GoImportPath("github.com/sudorandom/protojsonx/protojsonxgen"), GoName: "ErrIgnoredMapEntry"})
		body += "{\n\t\t\t\tif discardUnknown {\n\t\t\t\t\treturn 0, " + errIgnoredMapEntry + "\n\t\t\t\t}\n\t\t\t\treturn 0, " + unknownEnumValue + "(string(s))\n\t\t\t}\n"
		body += "\t\t} else {\n\t\t\tn, err := d.ReadInt32()\n\t\t\tif err != nil { return 0, err }\n\t\t\treturn " + enumType + "(n), nil\n\t\t}"
		
		return fmt.Sprintf("func(d *protojsonxgen.Decoder) (%s, error) {\n\t\t%s\n\t\t}", enumType, body)
	case protoreflect.MessageKind:
		msgFullName := valDesc.Message().FullName()
		msgIdent := resolveMessageGoIdent(valDesc.Message())
		msgType := "*" + g.QualifiedGoIdent(msgIdent)
		switch msgFullName {
		case "google.protobuf.Timestamp":
			return fmt.Sprintf("func(d *protojsonxgen.Decoder) (%s, error) { secs, nanos, err := d.ReadTimestamp(); if err != nil { return nil, err }; return &%s{Seconds: secs, Nanos: nanos}, nil }", msgType, g.QualifiedGoIdent(msgIdent))
		case "google.protobuf.Duration":
			return fmt.Sprintf("func(d *protojsonxgen.Decoder) (%s, error) { secs, nanos, err := d.ReadDuration(); if err != nil { return nil, err }; return &%s{Seconds: secs, Nanos: nanos}, nil }", msgType, g.QualifiedGoIdent(msgIdent))
		default:
			return fmt.Sprintf("func(d *protojsonxgen.Decoder) (%s, error) { return protojsonxgen.UnmarshalMessageMapValue[%s](d, discardUnknown) }", msgType, g.QualifiedGoIdent(msgIdent))
		}
	}
	return "nil"
}

func collectEnums(file *protogen.File) []*protogen.Enum {
	var enums []*protogen.Enum
	seen := make(map[string]bool)

	var collectMsg func(m *protogen.Message)
	collectMsg = func(m *protogen.Message) {
		if m.Desc.IsMapEntry() {
			return
		}
		for _, f := range m.Fields {
			if f.Desc.Kind() == protoreflect.EnumKind && f.Enum != nil {
				name := string(f.Enum.Desc.FullName())
				if !seen[name] {
					seen[name] = true
					enums = append(enums, f.Enum)
				}
			}
			if f.Desc.IsMap() && f.Desc.MapValue().Kind() == protoreflect.EnumKind && f.Enum != nil {
				name := string(f.Enum.Desc.FullName())
				if !seen[name] {
					seen[name] = true
					enums = append(enums, f.Enum)
				}
			}
		}
		for _, nested := range m.Messages {
			collectMsg(nested)
		}
	}
	for _, m := range file.Messages {
		collectMsg(m)
	}
	return enums
}

func generateEnumHelper(g *protogen.GeneratedFile, helperPackage protogen.GoImportPath, enum *protogen.Enum) {
	matchStringBytes := g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "MatchStringBytes"})

	g.P("func unmarshalEnum_", enum.GoIdent.GoName, "(d *", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "Decoder"}), ") (", g.QualifiedGoIdent(enum.GoIdent), ", error) {")
	g.P("var v ", g.QualifiedGoIdent(enum.GoIdent))
	g.P("if d.IsString() {")
	g.P("s, err := d.ReadStringBytes()")
	g.P("if err != nil { return 0, err }")
	for _, enumValue := range enum.Values {
		g.P("if ", matchStringBytes, "(s, ", strconvQuote(string(enumValue.Desc.Name())), ") {")
		g.P("v = ", g.QualifiedGoIdent(enumValue.GoIdent))
		g.P("} else ")
	}
	g.P("{")
	g.P("return 0, ", g.QualifiedGoIdent(protogen.GoIdent{GoImportPath: helperPackage, GoName: "ErrUnknownEnum"}))
	g.P("}")
	g.P("} else {")
	g.P("n, err := d.ReadInt32()")
	g.P("if err != nil { return 0, err }")
	g.P("v = ", g.QualifiedGoIdent(enum.GoIdent), "(n)")
	g.P("}")
	g.P("return v, nil")
	g.P("}")
	g.P()
}

func resolveEnumValueGoIdent(enumDesc protoreflect.EnumDescriptor, valDesc protoreflect.EnumValueDescriptor) protogen.GoIdent {
	if currentPlugin != nil {
		for _, f := range currentPlugin.Files {
			// Search top level enums
			for _, e := range f.Enums {
				if e.Desc.FullName() == enumDesc.FullName() {
					for _, ev := range e.Values {
						if ev.Desc.Name() == valDesc.Name() {
							return ev.GoIdent
						}
					}
				}
			}
			// Search nested enums
			var searchMessages func([]*protogen.Message) *protogen.EnumValue
			searchMessages = func(messages []*protogen.Message) *protogen.EnumValue {
				for _, m := range messages {
					for _, e := range m.Enums {
						if e.Desc.FullName() == enumDesc.FullName() {
							for _, ev := range e.Values {
								if ev.Desc.Name() == valDesc.Name() {
									return ev
								}
							}
						}
					}
					if found := searchMessages(m.Messages); found != nil {
						return found
					}
				}
				return nil
			}
			if ev := searchMessages(f.Messages); ev != nil {
				return ev.GoIdent
			}
		}
	}
	return protogen.GoIdent{GoName: string(enumDesc.Name()) + "_" + string(valDesc.Name())}
}

func isWKTValue(field *protogen.Field) bool {
	return field.Desc.Kind() == protoreflect.MessageKind && field.Message != nil && field.Message.Desc.FullName() == "google.protobuf.Value"
}

func isWKTNullValue(field *protogen.Field) bool {
	return field.Desc.Kind() == protoreflect.EnumKind && field.Enum != nil && field.Enum.Desc.FullName() == "google.protobuf.NullValue"
}
