// Code generated by protoc-gen-go-protojsonx. DO NOT EDIT.
// source: google/protobuf/test_messages_proto2.proto
// source: google/protobuf/test_messages_proto3.proto

package conformance

import protojsonxgen "github.com/sudorandom/protojsonx/protojsonxgen"

func (x *TestAllTypesProto2) MarshalProtoJSONX() ([]byte, error) {
	return protojsonxgen.Marshal(x)
}

func (x *TestAllTypesProto2) UnmarshalProtoJSONX(data []byte) error {
	return protojsonxgen.Unmarshal(data, x)
}

func (x *TestAllTypesProto3) MarshalProtoJSONX() ([]byte, error) {
	return protojsonxgen.Marshal(x)
}

func (x *TestAllTypesProto3) UnmarshalProtoJSONX(data []byte) error {
	return protojsonxgen.Unmarshal(data, x)
}
