// Code generated by protoc-gen-go-protojsonx. DO NOT EDIT.
// versions:
// 	protoc-gen-go-protojsonx v0.1.0
// source: test_shapes.proto

package testpb

import (
	protojsonxgen "github.com/sudorandom/protojsonx/protojsonxgen"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	strconv "strconv"
)

// This file is a placeholder for schema-specific protojsonx code.
// The generator is wired through protogen.Options so it follows the same
// module= and import-path behavior as protoc-gen-go.
const _ = "protojsonx generated scaffold 0.1.0"

func (x *ComplexMessage) ProtoJSONXFastPath() {}

func (x *ComplexMessage) MarshalProtoJSONX() ([]byte, error) {
	e := protojsonxgen.NewEncoder()
	if err := x.marshalProtoJSONXTo(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (x *ComplexMessage) UnmarshalProtoJSONX(data []byte) error {
	return x.UnmarshalProtoJSONXWithOptions(data, false)
}

func (x *ComplexMessage) UnmarshalProtoJSONXWithOptions(data []byte, discardUnknown bool) error {
	d := protojsonxgen.NewDecoder(data)
	*x = ComplexMessage{}
	firstKey, savedOff, savedDepth, _, peekErr := d.PeekObjectFieldName()
	if peekErr != nil {
		return peekErr
	}
	if firstKey == "doubleField" || firstKey == "" {
		d.Reset(savedOff, savedDepth)
		if ok, err := x.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
			return err
		} else if ok {
			return d.Finish()
		}
		*x = ComplexMessage{}
	}
	d.Reset(savedOff, savedDepth)
	if err := x.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
		return err
	}
	return d.Finish()
}

func (x *ComplexMessage) marshalProtoJSONXTo(e *protojsonxgen.Encoder) error {
	e.Byte('{')
	wrote := false
	if x.DoubleField != 0 {
		e.FieldPrefix(&wrote, "doubleField")
		e.Float64(x.DoubleField)
	}
	if x.FloatField != 0 {
		e.FieldPrefix(&wrote, "floatField")
		e.Float32(x.FloatField)
	}
	if x.Int32Field != 0 {
		e.FieldPrefix(&wrote, "int32Field")
		e.Int32(x.Int32Field)
	}
	if x.Int64Field != 0 {
		e.FieldPrefix(&wrote, "int64Field")
		e.Int64String(x.Int64Field)
	}
	if x.Uint32Field != 0 {
		e.FieldPrefix(&wrote, "uint32Field")
		e.Uint32(x.Uint32Field)
	}
	if x.Uint64Field != 0 {
		e.FieldPrefix(&wrote, "uint64Field")
		e.Uint64String(x.Uint64Field)
	}
	if x.Sint32Field != 0 {
		e.FieldPrefix(&wrote, "sint32Field")
		e.Int32(x.Sint32Field)
	}
	if x.Sint64Field != 0 {
		e.FieldPrefix(&wrote, "sint64Field")
		e.Int64String(x.Sint64Field)
	}
	if x.Fixed32Field != 0 {
		e.FieldPrefix(&wrote, "fixed32Field")
		e.Uint32(x.Fixed32Field)
	}
	if x.Fixed64Field != 0 {
		e.FieldPrefix(&wrote, "fixed64Field")
		e.Uint64String(x.Fixed64Field)
	}
	if x.Sfixed32Field != 0 {
		e.FieldPrefix(&wrote, "sfixed32Field")
		e.Int32(x.Sfixed32Field)
	}
	if x.Sfixed64Field != 0 {
		e.FieldPrefix(&wrote, "sfixed64Field")
		e.Int64String(x.Sfixed64Field)
	}
	if x.BoolField {
		e.FieldPrefix(&wrote, "boolField")
		e.Bool(x.BoolField)
	}
	if x.StringField != "" {
		e.FieldPrefix(&wrote, "stringField")
		e.String(x.StringField)
	}
	if len(x.BytesField) > 0 {
		e.FieldPrefix(&wrote, "bytesField")
		e.BytesField(x.BytesField)
	}
	if x.EnumField != 0 {
		e.FieldPrefix(&wrote, "enumField")
		switch x.EnumField {
		case TestEnum_TEST_ENUM_UNSPECIFIED:
			e.String("TEST_ENUM_UNSPECIFIED")
		case TestEnum_TEST_ENUM_FIRST:
			e.String("TEST_ENUM_FIRST")
		case TestEnum_TEST_ENUM_SECOND:
			e.String("TEST_ENUM_SECOND")
		default:
			e.Int32(int32(x.EnumField))
		}
	}
	if x.TimestampField != nil {
		e.FieldPrefix(&wrote, "timestampField")
		if err := e.Timestamp(x.TimestampField.GetSeconds(), x.TimestampField.GetNanos()); err != nil {
			return err
		}
	}
	if x.DurationField != nil {
		e.FieldPrefix(&wrote, "durationField")
		if err := e.Duration(x.DurationField.GetSeconds(), x.DurationField.GetNanos()); err != nil {
			return err
		}
	}
	if x.ChildField != nil {
		e.FieldPrefix(&wrote, "childField")
		if fast, ok := any(x.ChildField).(interface {
			marshalProtoJSONXTo(*protojsonxgen.Encoder) error
		}); ok {
			if err := fast.marshalProtoJSONXTo(e); err != nil {
				return err
			}
		} else {
			if err := protojsonxgen.MarshalField(e, x.ChildField); err != nil {
				return err
			}
		}
	}
	if len(x.RepeatedString) > 0 {
		e.FieldPrefix(&wrote, "repeatedString")
		e.Byte('[')
		for i, v := range x.RepeatedString {
			if i > 0 {
				e.Byte(',')
			}
			e.String(v)
		}
		e.Byte(']')
	}
	if len(x.RepeatedMessage) > 0 {
		e.FieldPrefix(&wrote, "repeatedMessage")
		e.Byte('[')
		for i, v := range x.RepeatedMessage {
			if i > 0 {
				e.Byte(',')
			}
			if v == nil {
				e.Raw("null")
			} else {
				if fast, ok := any(v).(interface {
					marshalProtoJSONXTo(*protojsonxgen.Encoder) error
				}); ok {
					if err := fast.marshalProtoJSONXTo(e); err != nil {
						return err
					}
				} else {
					if err := protojsonxgen.MarshalField(e, v); err != nil {
						return err
					}
				}
			}
		}
		e.Byte(']')
	}
	if len(x.MapStringString) > 0 {
		e.FieldPrefix(&wrote, "mapStringString")
		e.StringMap(x.MapStringString)
	}
	e.Byte('}')
	return nil
}

func (x *ComplexMessage) unmarshalProtoJSONXFast(d *protojsonxgen.Decoder, discardUnknown bool) (bool, error) {
	if err := d.BeginObject(); err != nil {
		return false, err
	}
	fastFirst := true
	{
		status, err := d.MatchFast(&fastFirst, "doubleField")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.DoubleField = 0
		} else {
			v, err := d.ReadFloat64()
			if err != nil {
				return false, err
			}
			x.DoubleField = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "floatField")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.FloatField = 0
		} else {
			v, err := d.ReadFloat32()
			if err != nil {
				return false, err
			}
			x.FloatField = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "int32Field")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Int32Field = 0
		} else {
			v, err := d.ReadInt32()
			if err != nil {
				return false, err
			}
			x.Int32Field = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "int64Field")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Int64Field = 0
		} else {
			v, err := d.ReadInt64()
			if err != nil {
				return false, err
			}
			x.Int64Field = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "uint32Field")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Uint32Field = 0
		} else {
			v, err := d.ReadUint32()
			if err != nil {
				return false, err
			}
			x.Uint32Field = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "uint64Field")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Uint64Field = 0
		} else {
			v, err := d.ReadUint64()
			if err != nil {
				return false, err
			}
			x.Uint64Field = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "sint32Field")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Sint32Field = 0
		} else {
			v, err := d.ReadInt32()
			if err != nil {
				return false, err
			}
			x.Sint32Field = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "sint64Field")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Sint64Field = 0
		} else {
			v, err := d.ReadInt64()
			if err != nil {
				return false, err
			}
			x.Sint64Field = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "fixed32Field")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Fixed32Field = 0
		} else {
			v, err := d.ReadUint32()
			if err != nil {
				return false, err
			}
			x.Fixed32Field = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "fixed64Field")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Fixed64Field = 0
		} else {
			v, err := d.ReadUint64()
			if err != nil {
				return false, err
			}
			x.Fixed64Field = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "sfixed32Field")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Sfixed32Field = 0
		} else {
			v, err := d.ReadInt32()
			if err != nil {
				return false, err
			}
			x.Sfixed32Field = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "sfixed64Field")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Sfixed64Field = 0
		} else {
			v, err := d.ReadInt64()
			if err != nil {
				return false, err
			}
			x.Sfixed64Field = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "boolField")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.BoolField = false
		} else {
			v, err := d.ReadBool()
			if err != nil {
				return false, err
			}
			x.BoolField = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "stringField")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.StringField = ""
		} else {
			v, err := d.ReadString()
			if err != nil {
				return false, err
			}
			x.StringField = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "bytesField")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.BytesField = nil
		} else {
			v, err := d.ReadBytes()
			if err != nil {
				return false, err
			}
			x.BytesField = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "enumField")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.EnumField = 0
		} else {
			var v TestEnum
			{
				val, err := unmarshalEnum_TestEnum(d, discardUnknown)
				if err != nil {
					return false, err
				}
				v = val
			}
			x.EnumField = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "timestampField")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.TimestampField = nil
		} else {
			secs, nanos, err := d.ReadTimestamp()
			if err != nil {
				return false, err
			}
			x.TimestampField = &timestamppb.Timestamp{Seconds: secs, Nanos: nanos}
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "durationField")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.DurationField = nil
		} else {
			secs, nanos, err := d.ReadDuration()
			if err != nil {
				return false, err
			}
			x.DurationField = &durationpb.Duration{Seconds: secs, Nanos: nanos}
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "childField")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.ChildField = nil
		} else {
			x.ChildField = &ChildMessage{}
			if fast, ok := any(x.ChildField).(interface {
				unmarshalProtoJSONXFast(*protojsonxgen.Decoder, bool) (bool, error)
			}); ok {
				if ok, err := fast.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
					return false, err
				} else if !ok {
					return false, nil
				}
			} else {
				if err := protojsonxgen.UnmarshalField(d, x.ChildField, discardUnknown); err != nil {
					return false, err
				}
			}
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "repeatedString")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.RepeatedString = nil
		} else {
			values := x.RepeatedString[:0]
			if values == nil {
				values = make([]string, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadString()
				if err != nil {
					return false, err
				}
				values = append(values, v)
			}
			x.RepeatedString = values
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "repeatedMessage")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.RepeatedMessage = nil
		} else {
			values := x.RepeatedMessage[:0]
			if values == nil {
				values = make([]*ChildMessage, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				if d.ReadNull() {
					return false, protojsonxgen.NullRepeatedMessage()
				}
				v := &ChildMessage{}
				if fast, ok := any(v).(interface {
					unmarshalProtoJSONXFast(*protojsonxgen.Decoder, bool) (bool, error)
				}); ok {
					if ok, err := fast.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
						return false, err
					} else if !ok {
						return false, nil
					}
				} else {
					if err := protojsonxgen.UnmarshalField(d, v, discardUnknown); err != nil {
						return false, err
					}
				}
				values = append(values, v)
			}
			x.RepeatedMessage = values
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "mapStringString")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.MapStringString = nil
		} else {
			m := make(map[string]string)
			if err := d.BeginObject(); err != nil {
				return false, err
			}
			mapFirst := true
			for {
				k, mapOK, err := d.NextObjectKey(&mapFirst)
				if err != nil {
					return false, err
				}
				if !mapOK {
					break
				}
				v, err := d.ReadString()
				if err != nil {
					return false, err
				}
				m[k] = v
			}
			x.MapStringString = m
		}
	}
	done, err := d.TryEndObject()
	if err != nil {
		return false, err
	}
	if !done {
		return false, nil
	}
	return true, nil
}

func (x *ComplexMessage) unmarshalProtoJSONXFrom(d *protojsonxgen.Decoder, discardUnknown bool) error {
	if err := d.BeginObject(); err != nil {
		return err
	}
	var seen [22]bool
	first := true
	for {
		key, ok, err := d.NextObjectKey(&first)
		if err != nil {
			return err
		}
		if !ok {
			return nil
		}
		switch key {
		case "doubleField", "double_field":
			if seen[0] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[0] = true
			if d.ReadNull() {
				x.DoubleField = 0
			} else {
				v, err := d.ReadFloat64()
				if err != nil {
					return err
				}
				x.DoubleField = v
			}
			continue
		case "floatField", "float_field":
			if seen[1] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[1] = true
			if d.ReadNull() {
				x.FloatField = 0
			} else {
				v, err := d.ReadFloat32()
				if err != nil {
					return err
				}
				x.FloatField = v
			}
			continue
		case "int32Field", "int32_field":
			if seen[2] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[2] = true
			if d.ReadNull() {
				x.Int32Field = 0
			} else {
				v, err := d.ReadInt32()
				if err != nil {
					return err
				}
				x.Int32Field = v
			}
			continue
		case "int64Field", "int64_field":
			if seen[3] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[3] = true
			if d.ReadNull() {
				x.Int64Field = 0
			} else {
				v, err := d.ReadInt64()
				if err != nil {
					return err
				}
				x.Int64Field = v
			}
			continue
		case "uint32Field", "uint32_field":
			if seen[4] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[4] = true
			if d.ReadNull() {
				x.Uint32Field = 0
			} else {
				v, err := d.ReadUint32()
				if err != nil {
					return err
				}
				x.Uint32Field = v
			}
			continue
		case "uint64Field", "uint64_field":
			if seen[5] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[5] = true
			if d.ReadNull() {
				x.Uint64Field = 0
			} else {
				v, err := d.ReadUint64()
				if err != nil {
					return err
				}
				x.Uint64Field = v
			}
			continue
		case "sint32Field", "sint32_field":
			if seen[6] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[6] = true
			if d.ReadNull() {
				x.Sint32Field = 0
			} else {
				v, err := d.ReadInt32()
				if err != nil {
					return err
				}
				x.Sint32Field = v
			}
			continue
		case "sint64Field", "sint64_field":
			if seen[7] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[7] = true
			if d.ReadNull() {
				x.Sint64Field = 0
			} else {
				v, err := d.ReadInt64()
				if err != nil {
					return err
				}
				x.Sint64Field = v
			}
			continue
		case "fixed32Field", "fixed32_field":
			if seen[8] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[8] = true
			if d.ReadNull() {
				x.Fixed32Field = 0
			} else {
				v, err := d.ReadUint32()
				if err != nil {
					return err
				}
				x.Fixed32Field = v
			}
			continue
		case "fixed64Field", "fixed64_field":
			if seen[9] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[9] = true
			if d.ReadNull() {
				x.Fixed64Field = 0
			} else {
				v, err := d.ReadUint64()
				if err != nil {
					return err
				}
				x.Fixed64Field = v
			}
			continue
		case "sfixed32Field", "sfixed32_field":
			if seen[10] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[10] = true
			if d.ReadNull() {
				x.Sfixed32Field = 0
			} else {
				v, err := d.ReadInt32()
				if err != nil {
					return err
				}
				x.Sfixed32Field = v
			}
			continue
		case "sfixed64Field", "sfixed64_field":
			if seen[11] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[11] = true
			if d.ReadNull() {
				x.Sfixed64Field = 0
			} else {
				v, err := d.ReadInt64()
				if err != nil {
					return err
				}
				x.Sfixed64Field = v
			}
			continue
		case "boolField", "bool_field":
			if seen[12] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[12] = true
			if d.ReadNull() {
				x.BoolField = false
			} else {
				v, err := d.ReadBool()
				if err != nil {
					return err
				}
				x.BoolField = v
			}
			continue
		case "stringField", "string_field":
			if seen[13] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[13] = true
			if d.ReadNull() {
				x.StringField = ""
			} else {
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				x.StringField = v
			}
			continue
		case "bytesField", "bytes_field":
			if seen[14] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[14] = true
			if d.ReadNull() {
				x.BytesField = nil
			} else {
				v, err := d.ReadBytes()
				if err != nil {
					return err
				}
				x.BytesField = v
			}
			continue
		case "enumField", "enum_field":
			if seen[15] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[15] = true
			if d.ReadNull() {
				x.EnumField = 0
			} else {
				var v TestEnum
				{
					val, err := unmarshalEnum_TestEnum(d, discardUnknown)
					if err != nil {
						return err
					}
					v = val
				}
				x.EnumField = v
			}
			continue
		case "timestampField", "timestamp_field":
			if seen[16] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[16] = true
			if d.ReadNull() {
				x.TimestampField = nil
			} else {
				secs, nanos, err := d.ReadTimestamp()
				if err != nil {
					return err
				}
				x.TimestampField = &timestamppb.Timestamp{Seconds: secs, Nanos: nanos}
			}
			continue
		case "durationField", "duration_field":
			if seen[17] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[17] = true
			if d.ReadNull() {
				x.DurationField = nil
			} else {
				secs, nanos, err := d.ReadDuration()
				if err != nil {
					return err
				}
				x.DurationField = &durationpb.Duration{Seconds: secs, Nanos: nanos}
			}
			continue
		case "childField", "child_field":
			if seen[18] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[18] = true
			if d.ReadNull() {
				x.ChildField = nil
			} else {
				x.ChildField = &ChildMessage{}
				if slow, ok := any(x.ChildField).(interface {
					unmarshalProtoJSONXFrom(*protojsonxgen.Decoder, bool) error
				}); ok {
					if err := slow.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
						return err
					}
				} else {
					if err := protojsonxgen.UnmarshalField(d, x.ChildField, discardUnknown); err != nil {
						return err
					}
				}
			}
			continue
		case "repeatedString", "repeated_string":
			if seen[19] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[19] = true
			if d.ReadNull() {
				x.RepeatedString = nil
			} else {
				values := x.RepeatedString[:0]
				if values == nil {
					values = make([]string, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					v, err := d.ReadString()
					if err != nil {
						return err
					}
					values = append(values, v)
				}
				x.RepeatedString = values
			}
			continue
		case "repeatedMessage", "repeated_message":
			if seen[20] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[20] = true
			if d.ReadNull() {
				x.RepeatedMessage = nil
			} else {
				values := x.RepeatedMessage[:0]
				if values == nil {
					values = make([]*ChildMessage, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					if d.ReadNull() {
						return protojsonxgen.NullRepeatedMessage()
					}
					v := &ChildMessage{}
					if slow, ok := any(v).(interface {
						unmarshalProtoJSONXFrom(*protojsonxgen.Decoder, bool) error
					}); ok {
						if err := slow.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
							return err
						}
					} else {
						if err := protojsonxgen.UnmarshalField(d, v, discardUnknown); err != nil {
							return err
						}
					}
					values = append(values, v)
				}
				x.RepeatedMessage = values
			}
			continue
		case "mapStringString", "map_string_string":
			if seen[21] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[21] = true
			if d.ReadNull() {
				x.MapStringString = nil
			} else {
				m := make(map[string]string)
				if err := d.BeginObject(); err != nil {
					return err
				}
				mapFirst := true
				for {
					k, mapOK, err := d.NextObjectKey(&mapFirst)
					if err != nil {
						return err
					}
					if !mapOK {
						break
					}
					v, err := d.ReadString()
					if err != nil {
						return err
					}
					m[k] = v
				}
				x.MapStringString = m
			}
			continue
		default:
			if discardUnknown {
				if err := d.SkipValue(); err != nil {
					return err
				}
			} else {
				return protojsonxgen.UnknownField(key)
			}
		}
	}
}

func (x *ChildMessage) ProtoJSONXFastPath() {}

func (x *ChildMessage) MarshalProtoJSONX() ([]byte, error) {
	e := protojsonxgen.NewEncoder()
	if err := x.marshalProtoJSONXTo(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (x *ChildMessage) UnmarshalProtoJSONX(data []byte) error {
	return x.UnmarshalProtoJSONXWithOptions(data, false)
}

func (x *ChildMessage) UnmarshalProtoJSONXWithOptions(data []byte, discardUnknown bool) error {
	d := protojsonxgen.NewDecoder(data)
	*x = ChildMessage{}
	firstKey, savedOff, savedDepth, _, peekErr := d.PeekObjectFieldName()
	if peekErr != nil {
		return peekErr
	}
	if firstKey == "name" || firstKey == "" {
		d.Reset(savedOff, savedDepth)
		if ok, err := x.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
			return err
		} else if ok {
			return d.Finish()
		}
		*x = ChildMessage{}
	}
	d.Reset(savedOff, savedDepth)
	if err := x.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
		return err
	}
	return d.Finish()
}

func (x *ChildMessage) marshalProtoJSONXTo(e *protojsonxgen.Encoder) error {
	e.Byte('{')
	wrote := false
	if x.Name != "" {
		e.FieldPrefix(&wrote, "name")
		e.String(x.Name)
	}
	if x.Value != 0 {
		e.FieldPrefix(&wrote, "value")
		e.Int32(x.Value)
	}
	e.Byte('}')
	return nil
}

func (x *ChildMessage) unmarshalProtoJSONXFast(d *protojsonxgen.Decoder, discardUnknown bool) (bool, error) {
	if err := d.BeginObject(); err != nil {
		return false, err
	}
	fastFirst := true
	{
		status, err := d.MatchFast(&fastFirst, "name")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Name = ""
		} else {
			v, err := d.ReadString()
			if err != nil {
				return false, err
			}
			x.Name = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "value")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Value = 0
		} else {
			v, err := d.ReadInt32()
			if err != nil {
				return false, err
			}
			x.Value = v
		}
	}
	done, err := d.TryEndObject()
	if err != nil {
		return false, err
	}
	if !done {
		return false, nil
	}
	return true, nil
}

func (x *ChildMessage) unmarshalProtoJSONXFrom(d *protojsonxgen.Decoder, discardUnknown bool) error {
	if err := d.BeginObject(); err != nil {
		return err
	}
	var seen [2]bool
	first := true
	for {
		key, ok, err := d.NextObjectKey(&first)
		if err != nil {
			return err
		}
		if !ok {
			return nil
		}
		switch key {
		case "name":
			if seen[0] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[0] = true
			if d.ReadNull() {
				x.Name = ""
			} else {
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				x.Name = v
			}
			continue
		case "value":
			if seen[1] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[1] = true
			if d.ReadNull() {
				x.Value = 0
			} else {
				v, err := d.ReadInt32()
				if err != nil {
					return err
				}
				x.Value = v
			}
			continue
		default:
			if discardUnknown {
				if err := d.SkipValue(); err != nil {
					return err
				}
			} else {
				return protojsonxgen.UnknownField(key)
			}
		}
	}
}

func (x *SpecMessage) ProtoJSONXFastPath() {}

func (x *SpecMessage) MarshalProtoJSONX() ([]byte, error) {
	e := protojsonxgen.NewEncoder()
	if err := x.marshalProtoJSONXTo(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (x *SpecMessage) UnmarshalProtoJSONX(data []byte) error {
	return x.UnmarshalProtoJSONXWithOptions(data, false)
}

func (x *SpecMessage) UnmarshalProtoJSONXWithOptions(data []byte, discardUnknown bool) error {
	d := protojsonxgen.NewDecoder(data)
	*x = SpecMessage{}
	firstKey, savedOff, savedDepth, _, peekErr := d.PeekObjectFieldName()
	if peekErr != nil {
		return peekErr
	}
	if firstKey == "anyField" || firstKey == "" {
		d.Reset(savedOff, savedDepth)
		if ok, err := x.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
			return err
		} else if ok {
			return d.Finish()
		}
		*x = SpecMessage{}
	}
	d.Reset(savedOff, savedDepth)
	if err := x.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
		return err
	}
	return d.Finish()
}

func (x *SpecMessage) marshalProtoJSONXTo(e *protojsonxgen.Encoder) error {
	e.Byte('{')
	wrote := false
	if x.AnyField != nil {
		e.FieldPrefix(&wrote, "anyField")
		if fast, ok := any(x.AnyField).(interface {
			marshalProtoJSONXTo(*protojsonxgen.Encoder) error
		}); ok {
			if err := fast.marshalProtoJSONXTo(e); err != nil {
				return err
			}
		} else {
			if err := protojsonxgen.MarshalField(e, x.AnyField); err != nil {
				return err
			}
		}
	}
	if x.EmptyField != nil {
		e.FieldPrefix(&wrote, "emptyField")
		if fast, ok := any(x.EmptyField).(interface {
			marshalProtoJSONXTo(*protojsonxgen.Encoder) error
		}); ok {
			if err := fast.marshalProtoJSONXTo(e); err != nil {
				return err
			}
		} else {
			if err := protojsonxgen.MarshalField(e, x.EmptyField); err != nil {
				return err
			}
		}
	}
	if x.FieldMaskField != nil {
		e.FieldPrefix(&wrote, "fieldMaskField")
		if fast, ok := any(x.FieldMaskField).(interface {
			marshalProtoJSONXTo(*protojsonxgen.Encoder) error
		}); ok {
			if err := fast.marshalProtoJSONXTo(e); err != nil {
				return err
			}
		} else {
			if err := protojsonxgen.MarshalField(e, x.FieldMaskField); err != nil {
				return err
			}
		}
	}
	if x.DoubleValueField != nil {
		e.FieldPrefix(&wrote, "doubleValueField")
		if fast, ok := any(x.DoubleValueField).(interface {
			marshalProtoJSONXTo(*protojsonxgen.Encoder) error
		}); ok {
			if err := fast.marshalProtoJSONXTo(e); err != nil {
				return err
			}
		} else {
			if err := protojsonxgen.MarshalField(e, x.DoubleValueField); err != nil {
				return err
			}
		}
	}
	if x.FloatValueField != nil {
		e.FieldPrefix(&wrote, "floatValueField")
		if fast, ok := any(x.FloatValueField).(interface {
			marshalProtoJSONXTo(*protojsonxgen.Encoder) error
		}); ok {
			if err := fast.marshalProtoJSONXTo(e); err != nil {
				return err
			}
		} else {
			if err := protojsonxgen.MarshalField(e, x.FloatValueField); err != nil {
				return err
			}
		}
	}
	if x.Int64ValueField != nil {
		e.FieldPrefix(&wrote, "int64ValueField")
		if fast, ok := any(x.Int64ValueField).(interface {
			marshalProtoJSONXTo(*protojsonxgen.Encoder) error
		}); ok {
			if err := fast.marshalProtoJSONXTo(e); err != nil {
				return err
			}
		} else {
			if err := protojsonxgen.MarshalField(e, x.Int64ValueField); err != nil {
				return err
			}
		}
	}
	if x.Uint64ValueField != nil {
		e.FieldPrefix(&wrote, "uint64ValueField")
		if fast, ok := any(x.Uint64ValueField).(interface {
			marshalProtoJSONXTo(*protojsonxgen.Encoder) error
		}); ok {
			if err := fast.marshalProtoJSONXTo(e); err != nil {
				return err
			}
		} else {
			if err := protojsonxgen.MarshalField(e, x.Uint64ValueField); err != nil {
				return err
			}
		}
	}
	if x.Int32ValueField != nil {
		e.FieldPrefix(&wrote, "int32ValueField")
		if fast, ok := any(x.Int32ValueField).(interface {
			marshalProtoJSONXTo(*protojsonxgen.Encoder) error
		}); ok {
			if err := fast.marshalProtoJSONXTo(e); err != nil {
				return err
			}
		} else {
			if err := protojsonxgen.MarshalField(e, x.Int32ValueField); err != nil {
				return err
			}
		}
	}
	if x.Uint32ValueField != nil {
		e.FieldPrefix(&wrote, "uint32ValueField")
		if fast, ok := any(x.Uint32ValueField).(interface {
			marshalProtoJSONXTo(*protojsonxgen.Encoder) error
		}); ok {
			if err := fast.marshalProtoJSONXTo(e); err != nil {
				return err
			}
		} else {
			if err := protojsonxgen.MarshalField(e, x.Uint32ValueField); err != nil {
				return err
			}
		}
	}
	if x.BoolValueField != nil {
		e.FieldPrefix(&wrote, "boolValueField")
		if fast, ok := any(x.BoolValueField).(interface {
			marshalProtoJSONXTo(*protojsonxgen.Encoder) error
		}); ok {
			if err := fast.marshalProtoJSONXTo(e); err != nil {
				return err
			}
		} else {
			if err := protojsonxgen.MarshalField(e, x.BoolValueField); err != nil {
				return err
			}
		}
	}
	if x.StringValueField != nil {
		e.FieldPrefix(&wrote, "stringValueField")
		if fast, ok := any(x.StringValueField).(interface {
			marshalProtoJSONXTo(*protojsonxgen.Encoder) error
		}); ok {
			if err := fast.marshalProtoJSONXTo(e); err != nil {
				return err
			}
		} else {
			if err := protojsonxgen.MarshalField(e, x.StringValueField); err != nil {
				return err
			}
		}
	}
	if x.BytesValueField != nil {
		e.FieldPrefix(&wrote, "bytesValueField")
		if fast, ok := any(x.BytesValueField).(interface {
			marshalProtoJSONXTo(*protojsonxgen.Encoder) error
		}); ok {
			if err := fast.marshalProtoJSONXTo(e); err != nil {
				return err
			}
		} else {
			if err := protojsonxgen.MarshalField(e, x.BytesValueField); err != nil {
				return err
			}
		}
	}
	e.Byte('}')
	return nil
}

func (x *SpecMessage) unmarshalProtoJSONXFast(d *protojsonxgen.Decoder, discardUnknown bool) (bool, error) {
	if err := d.BeginObject(); err != nil {
		return false, err
	}
	fastFirst := true
	{
		status, err := d.MatchFast(&fastFirst, "anyField")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.AnyField = nil
		} else {
			x.AnyField = &anypb.Any{}
			if fast, ok := any(x.AnyField).(interface {
				unmarshalProtoJSONXFast(*protojsonxgen.Decoder, bool) (bool, error)
			}); ok {
				if ok, err := fast.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
					return false, err
				} else if !ok {
					return false, nil
				}
			} else {
				if err := protojsonxgen.UnmarshalField(d, x.AnyField, discardUnknown); err != nil {
					return false, err
				}
			}
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "emptyField")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.EmptyField = nil
		} else {
			x.EmptyField = &emptypb.Empty{}
			if fast, ok := any(x.EmptyField).(interface {
				unmarshalProtoJSONXFast(*protojsonxgen.Decoder, bool) (bool, error)
			}); ok {
				if ok, err := fast.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
					return false, err
				} else if !ok {
					return false, nil
				}
			} else {
				if err := protojsonxgen.UnmarshalField(d, x.EmptyField, discardUnknown); err != nil {
					return false, err
				}
			}
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "fieldMaskField")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.FieldMaskField = nil
		} else {
			x.FieldMaskField = &fieldmaskpb.FieldMask{}
			if fast, ok := any(x.FieldMaskField).(interface {
				unmarshalProtoJSONXFast(*protojsonxgen.Decoder, bool) (bool, error)
			}); ok {
				if ok, err := fast.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
					return false, err
				} else if !ok {
					return false, nil
				}
			} else {
				if err := protojsonxgen.UnmarshalField(d, x.FieldMaskField, discardUnknown); err != nil {
					return false, err
				}
			}
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "doubleValueField")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.DoubleValueField = nil
		} else {
			x.DoubleValueField = &wrapperspb.DoubleValue{}
			if fast, ok := any(x.DoubleValueField).(interface {
				unmarshalProtoJSONXFast(*protojsonxgen.Decoder, bool) (bool, error)
			}); ok {
				if ok, err := fast.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
					return false, err
				} else if !ok {
					return false, nil
				}
			} else {
				if err := protojsonxgen.UnmarshalField(d, x.DoubleValueField, discardUnknown); err != nil {
					return false, err
				}
			}
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "floatValueField")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.FloatValueField = nil
		} else {
			x.FloatValueField = &wrapperspb.FloatValue{}
			if fast, ok := any(x.FloatValueField).(interface {
				unmarshalProtoJSONXFast(*protojsonxgen.Decoder, bool) (bool, error)
			}); ok {
				if ok, err := fast.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
					return false, err
				} else if !ok {
					return false, nil
				}
			} else {
				if err := protojsonxgen.UnmarshalField(d, x.FloatValueField, discardUnknown); err != nil {
					return false, err
				}
			}
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "int64ValueField")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Int64ValueField = nil
		} else {
			x.Int64ValueField = &wrapperspb.Int64Value{}
			if fast, ok := any(x.Int64ValueField).(interface {
				unmarshalProtoJSONXFast(*protojsonxgen.Decoder, bool) (bool, error)
			}); ok {
				if ok, err := fast.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
					return false, err
				} else if !ok {
					return false, nil
				}
			} else {
				if err := protojsonxgen.UnmarshalField(d, x.Int64ValueField, discardUnknown); err != nil {
					return false, err
				}
			}
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "uint64ValueField")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Uint64ValueField = nil
		} else {
			x.Uint64ValueField = &wrapperspb.UInt64Value{}
			if fast, ok := any(x.Uint64ValueField).(interface {
				unmarshalProtoJSONXFast(*protojsonxgen.Decoder, bool) (bool, error)
			}); ok {
				if ok, err := fast.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
					return false, err
				} else if !ok {
					return false, nil
				}
			} else {
				if err := protojsonxgen.UnmarshalField(d, x.Uint64ValueField, discardUnknown); err != nil {
					return false, err
				}
			}
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "int32ValueField")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Int32ValueField = nil
		} else {
			x.Int32ValueField = &wrapperspb.Int32Value{}
			if fast, ok := any(x.Int32ValueField).(interface {
				unmarshalProtoJSONXFast(*protojsonxgen.Decoder, bool) (bool, error)
			}); ok {
				if ok, err := fast.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
					return false, err
				} else if !ok {
					return false, nil
				}
			} else {
				if err := protojsonxgen.UnmarshalField(d, x.Int32ValueField, discardUnknown); err != nil {
					return false, err
				}
			}
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "uint32ValueField")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Uint32ValueField = nil
		} else {
			x.Uint32ValueField = &wrapperspb.UInt32Value{}
			if fast, ok := any(x.Uint32ValueField).(interface {
				unmarshalProtoJSONXFast(*protojsonxgen.Decoder, bool) (bool, error)
			}); ok {
				if ok, err := fast.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
					return false, err
				} else if !ok {
					return false, nil
				}
			} else {
				if err := protojsonxgen.UnmarshalField(d, x.Uint32ValueField, discardUnknown); err != nil {
					return false, err
				}
			}
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "boolValueField")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.BoolValueField = nil
		} else {
			x.BoolValueField = &wrapperspb.BoolValue{}
			if fast, ok := any(x.BoolValueField).(interface {
				unmarshalProtoJSONXFast(*protojsonxgen.Decoder, bool) (bool, error)
			}); ok {
				if ok, err := fast.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
					return false, err
				} else if !ok {
					return false, nil
				}
			} else {
				if err := protojsonxgen.UnmarshalField(d, x.BoolValueField, discardUnknown); err != nil {
					return false, err
				}
			}
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "stringValueField")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.StringValueField = nil
		} else {
			x.StringValueField = &wrapperspb.StringValue{}
			if fast, ok := any(x.StringValueField).(interface {
				unmarshalProtoJSONXFast(*protojsonxgen.Decoder, bool) (bool, error)
			}); ok {
				if ok, err := fast.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
					return false, err
				} else if !ok {
					return false, nil
				}
			} else {
				if err := protojsonxgen.UnmarshalField(d, x.StringValueField, discardUnknown); err != nil {
					return false, err
				}
			}
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "bytesValueField")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.BytesValueField = nil
		} else {
			x.BytesValueField = &wrapperspb.BytesValue{}
			if fast, ok := any(x.BytesValueField).(interface {
				unmarshalProtoJSONXFast(*protojsonxgen.Decoder, bool) (bool, error)
			}); ok {
				if ok, err := fast.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
					return false, err
				} else if !ok {
					return false, nil
				}
			} else {
				if err := protojsonxgen.UnmarshalField(d, x.BytesValueField, discardUnknown); err != nil {
					return false, err
				}
			}
		}
	}
	done, err := d.TryEndObject()
	if err != nil {
		return false, err
	}
	if !done {
		return false, nil
	}
	return true, nil
}

func (x *SpecMessage) unmarshalProtoJSONXFrom(d *protojsonxgen.Decoder, discardUnknown bool) error {
	if err := d.BeginObject(); err != nil {
		return err
	}
	var seen [12]bool
	first := true
	for {
		key, ok, err := d.NextObjectKey(&first)
		if err != nil {
			return err
		}
		if !ok {
			return nil
		}
		switch key {
		case "anyField", "any_field":
			if seen[0] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[0] = true
			if d.ReadNull() {
				x.AnyField = nil
			} else {
				x.AnyField = &anypb.Any{}
				if slow, ok := any(x.AnyField).(interface {
					unmarshalProtoJSONXFrom(*protojsonxgen.Decoder, bool) error
				}); ok {
					if err := slow.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
						return err
					}
				} else {
					if err := protojsonxgen.UnmarshalField(d, x.AnyField, discardUnknown); err != nil {
						return err
					}
				}
			}
			continue
		case "emptyField", "empty_field":
			if seen[1] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[1] = true
			if d.ReadNull() {
				x.EmptyField = nil
			} else {
				x.EmptyField = &emptypb.Empty{}
				if slow, ok := any(x.EmptyField).(interface {
					unmarshalProtoJSONXFrom(*protojsonxgen.Decoder, bool) error
				}); ok {
					if err := slow.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
						return err
					}
				} else {
					if err := protojsonxgen.UnmarshalField(d, x.EmptyField, discardUnknown); err != nil {
						return err
					}
				}
			}
			continue
		case "fieldMaskField", "field_mask_field":
			if seen[2] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[2] = true
			if d.ReadNull() {
				x.FieldMaskField = nil
			} else {
				x.FieldMaskField = &fieldmaskpb.FieldMask{}
				if slow, ok := any(x.FieldMaskField).(interface {
					unmarshalProtoJSONXFrom(*protojsonxgen.Decoder, bool) error
				}); ok {
					if err := slow.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
						return err
					}
				} else {
					if err := protojsonxgen.UnmarshalField(d, x.FieldMaskField, discardUnknown); err != nil {
						return err
					}
				}
			}
			continue
		case "doubleValueField", "double_value_field":
			if seen[3] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[3] = true
			if d.ReadNull() {
				x.DoubleValueField = nil
			} else {
				x.DoubleValueField = &wrapperspb.DoubleValue{}
				if slow, ok := any(x.DoubleValueField).(interface {
					unmarshalProtoJSONXFrom(*protojsonxgen.Decoder, bool) error
				}); ok {
					if err := slow.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
						return err
					}
				} else {
					if err := protojsonxgen.UnmarshalField(d, x.DoubleValueField, discardUnknown); err != nil {
						return err
					}
				}
			}
			continue
		case "floatValueField", "float_value_field":
			if seen[4] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[4] = true
			if d.ReadNull() {
				x.FloatValueField = nil
			} else {
				x.FloatValueField = &wrapperspb.FloatValue{}
				if slow, ok := any(x.FloatValueField).(interface {
					unmarshalProtoJSONXFrom(*protojsonxgen.Decoder, bool) error
				}); ok {
					if err := slow.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
						return err
					}
				} else {
					if err := protojsonxgen.UnmarshalField(d, x.FloatValueField, discardUnknown); err != nil {
						return err
					}
				}
			}
			continue
		case "int64ValueField", "int64_value_field":
			if seen[5] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[5] = true
			if d.ReadNull() {
				x.Int64ValueField = nil
			} else {
				x.Int64ValueField = &wrapperspb.Int64Value{}
				if slow, ok := any(x.Int64ValueField).(interface {
					unmarshalProtoJSONXFrom(*protojsonxgen.Decoder, bool) error
				}); ok {
					if err := slow.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
						return err
					}
				} else {
					if err := protojsonxgen.UnmarshalField(d, x.Int64ValueField, discardUnknown); err != nil {
						return err
					}
				}
			}
			continue
		case "uint64ValueField", "uint64_value_field":
			if seen[6] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[6] = true
			if d.ReadNull() {
				x.Uint64ValueField = nil
			} else {
				x.Uint64ValueField = &wrapperspb.UInt64Value{}
				if slow, ok := any(x.Uint64ValueField).(interface {
					unmarshalProtoJSONXFrom(*protojsonxgen.Decoder, bool) error
				}); ok {
					if err := slow.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
						return err
					}
				} else {
					if err := protojsonxgen.UnmarshalField(d, x.Uint64ValueField, discardUnknown); err != nil {
						return err
					}
				}
			}
			continue
		case "int32ValueField", "int32_value_field":
			if seen[7] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[7] = true
			if d.ReadNull() {
				x.Int32ValueField = nil
			} else {
				x.Int32ValueField = &wrapperspb.Int32Value{}
				if slow, ok := any(x.Int32ValueField).(interface {
					unmarshalProtoJSONXFrom(*protojsonxgen.Decoder, bool) error
				}); ok {
					if err := slow.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
						return err
					}
				} else {
					if err := protojsonxgen.UnmarshalField(d, x.Int32ValueField, discardUnknown); err != nil {
						return err
					}
				}
			}
			continue
		case "uint32ValueField", "uint32_value_field":
			if seen[8] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[8] = true
			if d.ReadNull() {
				x.Uint32ValueField = nil
			} else {
				x.Uint32ValueField = &wrapperspb.UInt32Value{}
				if slow, ok := any(x.Uint32ValueField).(interface {
					unmarshalProtoJSONXFrom(*protojsonxgen.Decoder, bool) error
				}); ok {
					if err := slow.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
						return err
					}
				} else {
					if err := protojsonxgen.UnmarshalField(d, x.Uint32ValueField, discardUnknown); err != nil {
						return err
					}
				}
			}
			continue
		case "boolValueField", "bool_value_field":
			if seen[9] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[9] = true
			if d.ReadNull() {
				x.BoolValueField = nil
			} else {
				x.BoolValueField = &wrapperspb.BoolValue{}
				if slow, ok := any(x.BoolValueField).(interface {
					unmarshalProtoJSONXFrom(*protojsonxgen.Decoder, bool) error
				}); ok {
					if err := slow.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
						return err
					}
				} else {
					if err := protojsonxgen.UnmarshalField(d, x.BoolValueField, discardUnknown); err != nil {
						return err
					}
				}
			}
			continue
		case "stringValueField", "string_value_field":
			if seen[10] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[10] = true
			if d.ReadNull() {
				x.StringValueField = nil
			} else {
				x.StringValueField = &wrapperspb.StringValue{}
				if slow, ok := any(x.StringValueField).(interface {
					unmarshalProtoJSONXFrom(*protojsonxgen.Decoder, bool) error
				}); ok {
					if err := slow.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
						return err
					}
				} else {
					if err := protojsonxgen.UnmarshalField(d, x.StringValueField, discardUnknown); err != nil {
						return err
					}
				}
			}
			continue
		case "bytesValueField", "bytes_value_field":
			if seen[11] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[11] = true
			if d.ReadNull() {
				x.BytesValueField = nil
			} else {
				x.BytesValueField = &wrapperspb.BytesValue{}
				if slow, ok := any(x.BytesValueField).(interface {
					unmarshalProtoJSONXFrom(*protojsonxgen.Decoder, bool) error
				}); ok {
					if err := slow.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
						return err
					}
				} else {
					if err := protojsonxgen.UnmarshalField(d, x.BytesValueField, discardUnknown); err != nil {
						return err
					}
				}
			}
			continue
		default:
			if discardUnknown {
				if err := d.SkipValue(); err != nil {
					return err
				}
			} else {
				return protojsonxgen.UnknownField(key)
			}
		}
	}
}

func (x *StructMessage) ProtoJSONXFastPath() {}

func (x *StructMessage) MarshalProtoJSONX() ([]byte, error) {
	e := protojsonxgen.NewEncoder()
	if err := x.marshalProtoJSONXTo(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (x *StructMessage) UnmarshalProtoJSONX(data []byte) error {
	return x.UnmarshalProtoJSONXWithOptions(data, false)
}

func (x *StructMessage) UnmarshalProtoJSONXWithOptions(data []byte, discardUnknown bool) error {
	d := protojsonxgen.NewDecoder(data)
	*x = StructMessage{}
	firstKey, savedOff, savedDepth, _, peekErr := d.PeekObjectFieldName()
	if peekErr != nil {
		return peekErr
	}
	if firstKey == "structField" || firstKey == "" {
		d.Reset(savedOff, savedDepth)
		if ok, err := x.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
			return err
		} else if ok {
			return d.Finish()
		}
		*x = StructMessage{}
	}
	d.Reset(savedOff, savedDepth)
	if err := x.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
		return err
	}
	return d.Finish()
}

func (x *StructMessage) marshalProtoJSONXTo(e *protojsonxgen.Encoder) error {
	e.Byte('{')
	wrote := false
	if x.StructField != nil {
		e.FieldPrefix(&wrote, "structField")
		if fast, ok := any(x.StructField).(interface {
			marshalProtoJSONXTo(*protojsonxgen.Encoder) error
		}); ok {
			if err := fast.marshalProtoJSONXTo(e); err != nil {
				return err
			}
		} else {
			if err := protojsonxgen.MarshalField(e, x.StructField); err != nil {
				return err
			}
		}
	}
	e.Byte('}')
	return nil
}

func (x *StructMessage) unmarshalProtoJSONXFast(d *protojsonxgen.Decoder, discardUnknown bool) (bool, error) {
	if err := d.BeginObject(); err != nil {
		return false, err
	}
	fastFirst := true
	{
		status, err := d.MatchFast(&fastFirst, "structField")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.StructField = nil
		} else {
			x.StructField = &structpb.Struct{}
			if fast, ok := any(x.StructField).(interface {
				unmarshalProtoJSONXFast(*protojsonxgen.Decoder, bool) (bool, error)
			}); ok {
				if ok, err := fast.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
					return false, err
				} else if !ok {
					return false, nil
				}
			} else {
				if err := protojsonxgen.UnmarshalField(d, x.StructField, discardUnknown); err != nil {
					return false, err
				}
			}
		}
	}
	done, err := d.TryEndObject()
	if err != nil {
		return false, err
	}
	if !done {
		return false, nil
	}
	return true, nil
}

func (x *StructMessage) unmarshalProtoJSONXFrom(d *protojsonxgen.Decoder, discardUnknown bool) error {
	if err := d.BeginObject(); err != nil {
		return err
	}
	var seen [1]bool
	first := true
	for {
		key, ok, err := d.NextObjectKey(&first)
		if err != nil {
			return err
		}
		if !ok {
			return nil
		}
		switch key {
		case "structField", "struct_field":
			if seen[0] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[0] = true
			if d.ReadNull() {
				x.StructField = nil
			} else {
				x.StructField = &structpb.Struct{}
				if slow, ok := any(x.StructField).(interface {
					unmarshalProtoJSONXFrom(*protojsonxgen.Decoder, bool) error
				}); ok {
					if err := slow.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
						return err
					}
				} else {
					if err := protojsonxgen.UnmarshalField(d, x.StructField, discardUnknown); err != nil {
						return err
					}
				}
			}
			continue
		default:
			if discardUnknown {
				if err := d.SkipValue(); err != nil {
					return err
				}
			} else {
				return protojsonxgen.UnknownField(key)
			}
		}
	}
}

func (x *ValueMessage) ProtoJSONXFastPath() {}

func (x *ValueMessage) MarshalProtoJSONX() ([]byte, error) {
	e := protojsonxgen.NewEncoder()
	if err := x.marshalProtoJSONXTo(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (x *ValueMessage) UnmarshalProtoJSONX(data []byte) error {
	return x.UnmarshalProtoJSONXWithOptions(data, false)
}

func (x *ValueMessage) UnmarshalProtoJSONXWithOptions(data []byte, discardUnknown bool) error {
	d := protojsonxgen.NewDecoder(data)
	*x = ValueMessage{}
	firstKey, savedOff, savedDepth, _, peekErr := d.PeekObjectFieldName()
	if peekErr != nil {
		return peekErr
	}
	if firstKey == "valueField" || firstKey == "" {
		d.Reset(savedOff, savedDepth)
		if ok, err := x.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
			return err
		} else if ok {
			return d.Finish()
		}
		*x = ValueMessage{}
	}
	d.Reset(savedOff, savedDepth)
	if err := x.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
		return err
	}
	return d.Finish()
}

func (x *ValueMessage) marshalProtoJSONXTo(e *protojsonxgen.Encoder) error {
	e.Byte('{')
	wrote := false
	if x.ValueField != nil {
		e.FieldPrefix(&wrote, "valueField")
		if fast, ok := any(x.ValueField).(interface {
			marshalProtoJSONXTo(*protojsonxgen.Encoder) error
		}); ok {
			if err := fast.marshalProtoJSONXTo(e); err != nil {
				return err
			}
		} else {
			if err := protojsonxgen.MarshalField(e, x.ValueField); err != nil {
				return err
			}
		}
	}
	e.Byte('}')
	return nil
}

func (x *ValueMessage) unmarshalProtoJSONXFast(d *protojsonxgen.Decoder, discardUnknown bool) (bool, error) {
	if err := d.BeginObject(); err != nil {
		return false, err
	}
	fastFirst := true
	{
		status, err := d.MatchFast(&fastFirst, "valueField")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.ValueField = structpb.NewNullValue()
		} else {
			x.ValueField = &structpb.Value{}
			if fast, ok := any(x.ValueField).(interface {
				unmarshalProtoJSONXFast(*protojsonxgen.Decoder, bool) (bool, error)
			}); ok {
				if ok, err := fast.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
					return false, err
				} else if !ok {
					return false, nil
				}
			} else {
				if err := protojsonxgen.UnmarshalField(d, x.ValueField, discardUnknown); err != nil {
					return false, err
				}
			}
		}
	}
	done, err := d.TryEndObject()
	if err != nil {
		return false, err
	}
	if !done {
		return false, nil
	}
	return true, nil
}

func (x *ValueMessage) unmarshalProtoJSONXFrom(d *protojsonxgen.Decoder, discardUnknown bool) error {
	if err := d.BeginObject(); err != nil {
		return err
	}
	var seen [1]bool
	first := true
	for {
		key, ok, err := d.NextObjectKey(&first)
		if err != nil {
			return err
		}
		if !ok {
			return nil
		}
		switch key {
		case "valueField", "value_field":
			if seen[0] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[0] = true
			if d.ReadNull() {
				x.ValueField = structpb.NewNullValue()
			} else {
				x.ValueField = &structpb.Value{}
				if slow, ok := any(x.ValueField).(interface {
					unmarshalProtoJSONXFrom(*protojsonxgen.Decoder, bool) error
				}); ok {
					if err := slow.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
						return err
					}
				} else {
					if err := protojsonxgen.UnmarshalField(d, x.ValueField, discardUnknown); err != nil {
						return err
					}
				}
			}
			continue
		default:
			if discardUnknown {
				if err := d.SkipValue(); err != nil {
					return err
				}
			} else {
				return protojsonxgen.UnknownField(key)
			}
		}
	}
}

func (x *ListValueMessage) ProtoJSONXFastPath() {}

func (x *ListValueMessage) MarshalProtoJSONX() ([]byte, error) {
	e := protojsonxgen.NewEncoder()
	if err := x.marshalProtoJSONXTo(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (x *ListValueMessage) UnmarshalProtoJSONX(data []byte) error {
	return x.UnmarshalProtoJSONXWithOptions(data, false)
}

func (x *ListValueMessage) UnmarshalProtoJSONXWithOptions(data []byte, discardUnknown bool) error {
	d := protojsonxgen.NewDecoder(data)
	*x = ListValueMessage{}
	firstKey, savedOff, savedDepth, _, peekErr := d.PeekObjectFieldName()
	if peekErr != nil {
		return peekErr
	}
	if firstKey == "listValueField" || firstKey == "" {
		d.Reset(savedOff, savedDepth)
		if ok, err := x.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
			return err
		} else if ok {
			return d.Finish()
		}
		*x = ListValueMessage{}
	}
	d.Reset(savedOff, savedDepth)
	if err := x.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
		return err
	}
	return d.Finish()
}

func (x *ListValueMessage) marshalProtoJSONXTo(e *protojsonxgen.Encoder) error {
	e.Byte('{')
	wrote := false
	if x.ListValueField != nil {
		e.FieldPrefix(&wrote, "listValueField")
		if fast, ok := any(x.ListValueField).(interface {
			marshalProtoJSONXTo(*protojsonxgen.Encoder) error
		}); ok {
			if err := fast.marshalProtoJSONXTo(e); err != nil {
				return err
			}
		} else {
			if err := protojsonxgen.MarshalField(e, x.ListValueField); err != nil {
				return err
			}
		}
	}
	e.Byte('}')
	return nil
}

func (x *ListValueMessage) unmarshalProtoJSONXFast(d *protojsonxgen.Decoder, discardUnknown bool) (bool, error) {
	if err := d.BeginObject(); err != nil {
		return false, err
	}
	fastFirst := true
	{
		status, err := d.MatchFast(&fastFirst, "listValueField")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.ListValueField = nil
		} else {
			x.ListValueField = &structpb.ListValue{}
			if fast, ok := any(x.ListValueField).(interface {
				unmarshalProtoJSONXFast(*protojsonxgen.Decoder, bool) (bool, error)
			}); ok {
				if ok, err := fast.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
					return false, err
				} else if !ok {
					return false, nil
				}
			} else {
				if err := protojsonxgen.UnmarshalField(d, x.ListValueField, discardUnknown); err != nil {
					return false, err
				}
			}
		}
	}
	done, err := d.TryEndObject()
	if err != nil {
		return false, err
	}
	if !done {
		return false, nil
	}
	return true, nil
}

func (x *ListValueMessage) unmarshalProtoJSONXFrom(d *protojsonxgen.Decoder, discardUnknown bool) error {
	if err := d.BeginObject(); err != nil {
		return err
	}
	var seen [1]bool
	first := true
	for {
		key, ok, err := d.NextObjectKey(&first)
		if err != nil {
			return err
		}
		if !ok {
			return nil
		}
		switch key {
		case "listValueField", "list_value_field":
			if seen[0] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[0] = true
			if d.ReadNull() {
				x.ListValueField = nil
			} else {
				x.ListValueField = &structpb.ListValue{}
				if slow, ok := any(x.ListValueField).(interface {
					unmarshalProtoJSONXFrom(*protojsonxgen.Decoder, bool) error
				}); ok {
					if err := slow.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
						return err
					}
				} else {
					if err := protojsonxgen.UnmarshalField(d, x.ListValueField, discardUnknown); err != nil {
						return err
					}
				}
			}
			continue
		default:
			if discardUnknown {
				if err := d.SkipValue(); err != nil {
					return err
				}
			} else {
				return protojsonxgen.UnknownField(key)
			}
		}
	}
}

func (x *RepeatedScalarsMessage) ProtoJSONXFastPath() {}

func (x *RepeatedScalarsMessage) MarshalProtoJSONX() ([]byte, error) {
	e := protojsonxgen.NewEncoder()
	if err := x.marshalProtoJSONXTo(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (x *RepeatedScalarsMessage) UnmarshalProtoJSONX(data []byte) error {
	return x.UnmarshalProtoJSONXWithOptions(data, false)
}

func (x *RepeatedScalarsMessage) UnmarshalProtoJSONXWithOptions(data []byte, discardUnknown bool) error {
	d := protojsonxgen.NewDecoder(data)
	*x = RepeatedScalarsMessage{}
	firstKey, savedOff, savedDepth, _, peekErr := d.PeekObjectFieldName()
	if peekErr != nil {
		return peekErr
	}
	if firstKey == "repeatedInt32" || firstKey == "" {
		d.Reset(savedOff, savedDepth)
		if ok, err := x.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
			return err
		} else if ok {
			return d.Finish()
		}
		*x = RepeatedScalarsMessage{}
	}
	d.Reset(savedOff, savedDepth)
	if err := x.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
		return err
	}
	return d.Finish()
}

func (x *RepeatedScalarsMessage) marshalProtoJSONXTo(e *protojsonxgen.Encoder) error {
	e.Byte('{')
	wrote := false
	if len(x.RepeatedInt32) > 0 {
		e.FieldPrefix(&wrote, "repeatedInt32")
		e.Byte('[')
		for i, v := range x.RepeatedInt32 {
			if i > 0 {
				e.Byte(',')
			}
			e.Int32(v)
		}
		e.Byte(']')
	}
	if len(x.RepeatedInt64) > 0 {
		e.FieldPrefix(&wrote, "repeatedInt64")
		e.Byte('[')
		for i, v := range x.RepeatedInt64 {
			if i > 0 {
				e.Byte(',')
			}
			e.Int64String(v)
		}
		e.Byte(']')
	}
	if len(x.RepeatedUint32) > 0 {
		e.FieldPrefix(&wrote, "repeatedUint32")
		e.Byte('[')
		for i, v := range x.RepeatedUint32 {
			if i > 0 {
				e.Byte(',')
			}
			e.Uint32(v)
		}
		e.Byte(']')
	}
	if len(x.RepeatedUint64) > 0 {
		e.FieldPrefix(&wrote, "repeatedUint64")
		e.Byte('[')
		for i, v := range x.RepeatedUint64 {
			if i > 0 {
				e.Byte(',')
			}
			e.Uint64String(v)
		}
		e.Byte(']')
	}
	if len(x.RepeatedFloat) > 0 {
		e.FieldPrefix(&wrote, "repeatedFloat")
		e.Byte('[')
		for i, v := range x.RepeatedFloat {
			if i > 0 {
				e.Byte(',')
			}
			e.Float32(v)
		}
		e.Byte(']')
	}
	if len(x.RepeatedDouble) > 0 {
		e.FieldPrefix(&wrote, "repeatedDouble")
		e.Byte('[')
		for i, v := range x.RepeatedDouble {
			if i > 0 {
				e.Byte(',')
			}
			e.Float64(v)
		}
		e.Byte(']')
	}
	if len(x.RepeatedBool) > 0 {
		e.FieldPrefix(&wrote, "repeatedBool")
		e.Byte('[')
		for i, v := range x.RepeatedBool {
			if i > 0 {
				e.Byte(',')
			}
			e.Bool(v)
		}
		e.Byte(']')
	}
	if len(x.RepeatedBytes) > 0 {
		e.FieldPrefix(&wrote, "repeatedBytes")
		e.Byte('[')
		for i, v := range x.RepeatedBytes {
			if i > 0 {
				e.Byte(',')
			}
			e.BytesField(v)
		}
		e.Byte(']')
	}
	if len(x.RepeatedEnum) > 0 {
		e.FieldPrefix(&wrote, "repeatedEnum")
		e.Byte('[')
		for i, v := range x.RepeatedEnum {
			if i > 0 {
				e.Byte(',')
			}
			switch v {
			case TestEnum_TEST_ENUM_UNSPECIFIED:
				e.String("TEST_ENUM_UNSPECIFIED")
			case TestEnum_TEST_ENUM_FIRST:
				e.String("TEST_ENUM_FIRST")
			case TestEnum_TEST_ENUM_SECOND:
				e.String("TEST_ENUM_SECOND")
			default:
				e.Int32(int32(v))
			}
		}
		e.Byte(']')
	}
	e.Byte('}')
	return nil
}

func (x *RepeatedScalarsMessage) unmarshalProtoJSONXFast(d *protojsonxgen.Decoder, discardUnknown bool) (bool, error) {
	if err := d.BeginObject(); err != nil {
		return false, err
	}
	fastFirst := true
	{
		status, err := d.MatchFast(&fastFirst, "repeatedInt32")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.RepeatedInt32 = nil
		} else {
			values := x.RepeatedInt32[:0]
			if values == nil {
				values = make([]int32, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadInt32()
				if err != nil {
					return false, err
				}
				values = append(values, v)
			}
			x.RepeatedInt32 = values
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "repeatedInt64")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.RepeatedInt64 = nil
		} else {
			values := x.RepeatedInt64[:0]
			if values == nil {
				values = make([]int64, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadInt64()
				if err != nil {
					return false, err
				}
				values = append(values, v)
			}
			x.RepeatedInt64 = values
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "repeatedUint32")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.RepeatedUint32 = nil
		} else {
			values := x.RepeatedUint32[:0]
			if values == nil {
				values = make([]uint32, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadUint32()
				if err != nil {
					return false, err
				}
				values = append(values, v)
			}
			x.RepeatedUint32 = values
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "repeatedUint64")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.RepeatedUint64 = nil
		} else {
			values := x.RepeatedUint64[:0]
			if values == nil {
				values = make([]uint64, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadUint64()
				if err != nil {
					return false, err
				}
				values = append(values, v)
			}
			x.RepeatedUint64 = values
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "repeatedFloat")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.RepeatedFloat = nil
		} else {
			values := x.RepeatedFloat[:0]
			if values == nil {
				values = make([]float32, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadFloat32()
				if err != nil {
					return false, err
				}
				values = append(values, v)
			}
			x.RepeatedFloat = values
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "repeatedDouble")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.RepeatedDouble = nil
		} else {
			values := x.RepeatedDouble[:0]
			if values == nil {
				values = make([]float64, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadFloat64()
				if err != nil {
					return false, err
				}
				values = append(values, v)
			}
			x.RepeatedDouble = values
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "repeatedBool")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.RepeatedBool = nil
		} else {
			values := x.RepeatedBool[:0]
			if values == nil {
				values = make([]bool, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadBool()
				if err != nil {
					return false, err
				}
				values = append(values, v)
			}
			x.RepeatedBool = values
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "repeatedBytes")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.RepeatedBytes = nil
		} else {
			values := x.RepeatedBytes[:0]
			if values == nil {
				values = make([][]byte, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadBytes()
				if err != nil {
					return false, err
				}
				values = append(values, v)
			}
			x.RepeatedBytes = values
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "repeatedEnum")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.RepeatedEnum = nil
		} else {
			values := x.RepeatedEnum[:0]
			if values == nil {
				values = make([]TestEnum, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				var v TestEnum
				{
					val, err := unmarshalEnum_TestEnum(d, discardUnknown)
					if err != nil {
						return false, err
					}
					v = val
				}
				values = append(values, v)
			}
			x.RepeatedEnum = values
		}
	}
	done, err := d.TryEndObject()
	if err != nil {
		return false, err
	}
	if !done {
		return false, nil
	}
	return true, nil
}

func (x *RepeatedScalarsMessage) unmarshalProtoJSONXFrom(d *protojsonxgen.Decoder, discardUnknown bool) error {
	if err := d.BeginObject(); err != nil {
		return err
	}
	var seen [9]bool
	first := true
	for {
		key, ok, err := d.NextObjectKey(&first)
		if err != nil {
			return err
		}
		if !ok {
			return nil
		}
		switch key {
		case "repeatedInt32", "repeated_int32":
			if seen[0] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[0] = true
			if d.ReadNull() {
				x.RepeatedInt32 = nil
			} else {
				values := x.RepeatedInt32[:0]
				if values == nil {
					values = make([]int32, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					v, err := d.ReadInt32()
					if err != nil {
						return err
					}
					values = append(values, v)
				}
				x.RepeatedInt32 = values
			}
			continue
		case "repeatedInt64", "repeated_int64":
			if seen[1] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[1] = true
			if d.ReadNull() {
				x.RepeatedInt64 = nil
			} else {
				values := x.RepeatedInt64[:0]
				if values == nil {
					values = make([]int64, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					v, err := d.ReadInt64()
					if err != nil {
						return err
					}
					values = append(values, v)
				}
				x.RepeatedInt64 = values
			}
			continue
		case "repeatedUint32", "repeated_uint32":
			if seen[2] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[2] = true
			if d.ReadNull() {
				x.RepeatedUint32 = nil
			} else {
				values := x.RepeatedUint32[:0]
				if values == nil {
					values = make([]uint32, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					v, err := d.ReadUint32()
					if err != nil {
						return err
					}
					values = append(values, v)
				}
				x.RepeatedUint32 = values
			}
			continue
		case "repeatedUint64", "repeated_uint64":
			if seen[3] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[3] = true
			if d.ReadNull() {
				x.RepeatedUint64 = nil
			} else {
				values := x.RepeatedUint64[:0]
				if values == nil {
					values = make([]uint64, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					v, err := d.ReadUint64()
					if err != nil {
						return err
					}
					values = append(values, v)
				}
				x.RepeatedUint64 = values
			}
			continue
		case "repeatedFloat", "repeated_float":
			if seen[4] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[4] = true
			if d.ReadNull() {
				x.RepeatedFloat = nil
			} else {
				values := x.RepeatedFloat[:0]
				if values == nil {
					values = make([]float32, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					v, err := d.ReadFloat32()
					if err != nil {
						return err
					}
					values = append(values, v)
				}
				x.RepeatedFloat = values
			}
			continue
		case "repeatedDouble", "repeated_double":
			if seen[5] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[5] = true
			if d.ReadNull() {
				x.RepeatedDouble = nil
			} else {
				values := x.RepeatedDouble[:0]
				if values == nil {
					values = make([]float64, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					v, err := d.ReadFloat64()
					if err != nil {
						return err
					}
					values = append(values, v)
				}
				x.RepeatedDouble = values
			}
			continue
		case "repeatedBool", "repeated_bool":
			if seen[6] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[6] = true
			if d.ReadNull() {
				x.RepeatedBool = nil
			} else {
				values := x.RepeatedBool[:0]
				if values == nil {
					values = make([]bool, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					v, err := d.ReadBool()
					if err != nil {
						return err
					}
					values = append(values, v)
				}
				x.RepeatedBool = values
			}
			continue
		case "repeatedBytes", "repeated_bytes":
			if seen[7] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[7] = true
			if d.ReadNull() {
				x.RepeatedBytes = nil
			} else {
				values := x.RepeatedBytes[:0]
				if values == nil {
					values = make([][]byte, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					v, err := d.ReadBytes()
					if err != nil {
						return err
					}
					values = append(values, v)
				}
				x.RepeatedBytes = values
			}
			continue
		case "repeatedEnum", "repeated_enum":
			if seen[8] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[8] = true
			if d.ReadNull() {
				x.RepeatedEnum = nil
			} else {
				values := x.RepeatedEnum[:0]
				if values == nil {
					values = make([]TestEnum, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					var v TestEnum
					{
						val, err := unmarshalEnum_TestEnum(d, discardUnknown)
						if err != nil {
							return err
						}
						v = val
					}
					values = append(values, v)
				}
				x.RepeatedEnum = values
			}
			continue
		default:
			if discardUnknown {
				if err := d.SkipValue(); err != nil {
					return err
				}
			} else {
				return protojsonxgen.UnknownField(key)
			}
		}
	}
}

func (x *CompatibilityMessage) ProtoJSONXFastPath() {}

func (x *CompatibilityMessage) MarshalProtoJSONX() ([]byte, error) {
	e := protojsonxgen.NewEncoder()
	if err := x.marshalProtoJSONXTo(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (x *CompatibilityMessage) UnmarshalProtoJSONX(data []byte) error {
	return x.UnmarshalProtoJSONXWithOptions(data, false)
}

func (x *CompatibilityMessage) UnmarshalProtoJSONXWithOptions(data []byte, discardUnknown bool) error {
	d := protojsonxgen.NewDecoder(data)
	*x = CompatibilityMessage{}
	firstKey, savedOff, savedDepth, _, peekErr := d.PeekObjectFieldName()
	if peekErr != nil {
		return peekErr
	}
	if firstKey == "nameChoice" || firstKey == "" {
		d.Reset(savedOff, savedDepth)
		if ok, err := x.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
			return err
		} else if ok {
			return d.Finish()
		}
		*x = CompatibilityMessage{}
	}
	d.Reset(savedOff, savedDepth)
	if err := x.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
		return err
	}
	return d.Finish()
}

func (x *CompatibilityMessage) marshalProtoJSONXTo(e *protojsonxgen.Encoder) error {
	e.Byte('{')
	wrote := false
	if w, ok := x.Choice.(*CompatibilityMessage_NameChoice); ok {
		e.FieldPrefix(&wrote, "nameChoice")
		e.String(w.NameChoice)
	}
	if w, ok := x.Choice.(*CompatibilityMessage_NumberChoice); ok {
		e.FieldPrefix(&wrote, "numberChoice")
		e.Int32(w.NumberChoice)
	}
	if w, ok := x.Choice.(*CompatibilityMessage_ChildChoice); ok {
		if w.ChildChoice != nil {
			e.FieldPrefix(&wrote, "childChoice")
			if fast, ok := any(w.ChildChoice).(interface {
				marshalProtoJSONXTo(*protojsonxgen.Encoder) error
			}); ok {
				if err := fast.marshalProtoJSONXTo(e); err != nil {
					return err
				}
			} else {
				if err := protojsonxgen.MarshalField(e, w.ChildChoice); err != nil {
					return err
				}
			}
		}
	}
	if x.OptionalString != nil {
		e.FieldPrefix(&wrote, "optionalString")
		e.String(*x.OptionalString)
	}
	if x.OptionalInt32 != nil {
		e.FieldPrefix(&wrote, "optionalInt32")
		e.Int32(*x.OptionalInt32)
	}
	if len(x.RepeatedInt32) > 0 {
		e.FieldPrefix(&wrote, "repeatedInt32")
		e.Byte('[')
		for i, v := range x.RepeatedInt32 {
			if i > 0 {
				e.Byte(',')
			}
			e.Int32(v)
		}
		e.Byte(']')
	}
	if len(x.RepeatedBool) > 0 {
		e.FieldPrefix(&wrote, "repeatedBool")
		e.Byte('[')
		for i, v := range x.RepeatedBool {
			if i > 0 {
				e.Byte(',')
			}
			e.Bool(v)
		}
		e.Byte(']')
	}
	if len(x.RepeatedBytes) > 0 {
		e.FieldPrefix(&wrote, "repeatedBytes")
		e.Byte('[')
		for i, v := range x.RepeatedBytes {
			if i > 0 {
				e.Byte(',')
			}
			e.BytesField(v)
		}
		e.Byte(']')
	}
	if len(x.RepeatedEnum) > 0 {
		e.FieldPrefix(&wrote, "repeatedEnum")
		e.Byte('[')
		for i, v := range x.RepeatedEnum {
			if i > 0 {
				e.Byte(',')
			}
			switch v {
			case TestEnum_TEST_ENUM_UNSPECIFIED:
				e.String("TEST_ENUM_UNSPECIFIED")
			case TestEnum_TEST_ENUM_FIRST:
				e.String("TEST_ENUM_FIRST")
			case TestEnum_TEST_ENUM_SECOND:
				e.String("TEST_ENUM_SECOND")
			default:
				e.Int32(int32(v))
			}
		}
		e.Byte(']')
	}
	if len(x.MapStringInt32) > 0 {
		e.FieldPrefix(&wrote, "mapStringInt32")
		if err := protojsonxgen.WriteMap(e, x.MapStringInt32,
			func(k string) string { return k },
			func(e *protojsonxgen.Encoder, v int32) error { e.Int32(v); return nil }); err != nil {
			return err
		}
	}
	if len(x.MapInt32String) > 0 {
		e.FieldPrefix(&wrote, "mapInt32String")
		if err := protojsonxgen.WriteMap(e, x.MapInt32String,
			func(k int32) string { return strconv.FormatInt(int64(k), 10) },
			func(e *protojsonxgen.Encoder, v string) error { e.String(v); return nil }); err != nil {
			return err
		}
	}
	if len(x.MapStringMessage) > 0 {
		e.FieldPrefix(&wrote, "mapStringMessage")
		if err := protojsonxgen.WriteMap(e, x.MapStringMessage,
			func(k string) string { return k },
			protojsonxgen.MarshalMessageMapValue[*ChildMessage]); err != nil {
			return err
		}
	}
	e.Byte('}')
	return nil
}

func (x *CompatibilityMessage) unmarshalProtoJSONXFast(d *protojsonxgen.Decoder, discardUnknown bool) (bool, error) {
	if err := d.BeginObject(); err != nil {
		return false, err
	}
	var seenOneofs uint64
	fastFirst := true
	{
		status, err := d.MatchFast(&fastFirst, "nameChoice")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			if _, ok := x.Choice.(*CompatibilityMessage_NameChoice); ok {
				x.Choice = nil
			}
		} else {
			if seenOneofs&(1<<0) != 0 {
				return false, protojsonxgen.DuplicateField("nameChoice")
			}
			seenOneofs |= (1 << 0)
			v, err := d.ReadString()
			if err != nil {
				return false, err
			}
			x.Choice = &CompatibilityMessage_NameChoice{NameChoice: v}
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "numberChoice")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			if _, ok := x.Choice.(*CompatibilityMessage_NumberChoice); ok {
				x.Choice = nil
			}
		} else {
			if seenOneofs&(1<<0) != 0 {
				return false, protojsonxgen.DuplicateField("numberChoice")
			}
			seenOneofs |= (1 << 0)
			v, err := d.ReadInt32()
			if err != nil {
				return false, err
			}
			x.Choice = &CompatibilityMessage_NumberChoice{NumberChoice: v}
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "childChoice")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			if _, ok := x.Choice.(*CompatibilityMessage_ChildChoice); ok {
				x.Choice = nil
			}
		} else {
			if seenOneofs&(1<<0) != 0 {
				return false, protojsonxgen.DuplicateField("childChoice")
			}
			seenOneofs |= (1 << 0)
			v := &ChildMessage{}
			if fast, ok := any(v).(interface {
				unmarshalProtoJSONXFast(*protojsonxgen.Decoder, bool) (bool, error)
			}); ok {
				if ok, err := fast.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
					return false, err
				} else if !ok {
					return false, nil
				}
			} else {
				if err := protojsonxgen.UnmarshalField(d, v, discardUnknown); err != nil {
					return false, err
				}
			}
			x.Choice = &CompatibilityMessage_ChildChoice{ChildChoice: v}
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "optionalString")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.OptionalString = nil
		} else {
			v, err := d.ReadString()
			if err != nil {
				return false, err
			}
			x.OptionalString = &v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "optionalInt32")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.OptionalInt32 = nil
		} else {
			v, err := d.ReadInt32()
			if err != nil {
				return false, err
			}
			x.OptionalInt32 = &v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "repeatedInt32")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.RepeatedInt32 = nil
		} else {
			values := x.RepeatedInt32[:0]
			if values == nil {
				values = make([]int32, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadInt32()
				if err != nil {
					return false, err
				}
				values = append(values, v)
			}
			x.RepeatedInt32 = values
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "repeatedBool")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.RepeatedBool = nil
		} else {
			values := x.RepeatedBool[:0]
			if values == nil {
				values = make([]bool, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadBool()
				if err != nil {
					return false, err
				}
				values = append(values, v)
			}
			x.RepeatedBool = values
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "repeatedBytes")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.RepeatedBytes = nil
		} else {
			values := x.RepeatedBytes[:0]
			if values == nil {
				values = make([][]byte, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadBytes()
				if err != nil {
					return false, err
				}
				values = append(values, v)
			}
			x.RepeatedBytes = values
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "repeatedEnum")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.RepeatedEnum = nil
		} else {
			values := x.RepeatedEnum[:0]
			if values == nil {
				values = make([]TestEnum, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				var v TestEnum
				{
					val, err := unmarshalEnum_TestEnum(d, discardUnknown)
					if err != nil {
						return false, err
					}
					v = val
				}
				values = append(values, v)
			}
			x.RepeatedEnum = values
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "mapStringInt32")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.MapStringInt32 = nil
		} else {
			m := make(map[string]int32)
			if err := protojsonxgen.ReadMap(d, m,
				func(s string) (string, error) { return s, nil },
				func(d *protojsonxgen.Decoder) (int32, error) { return d.ReadInt32() }); err != nil {
				return false, err
			}
			x.MapStringInt32 = m
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "mapInt32String")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.MapInt32String = nil
		} else {
			m := make(map[int32]string)
			if err := protojsonxgen.ReadMap(d, m,
				func(s string) (int32, error) { val, err := strconv.ParseInt(s, 10, 32); return int32(val), err },
				func(d *protojsonxgen.Decoder) (string, error) { return d.ReadString() }); err != nil {
				return false, err
			}
			x.MapInt32String = m
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "mapStringMessage")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.MapStringMessage = nil
		} else {
			m := make(map[string]*ChildMessage)
			if err := protojsonxgen.ReadMap(d, m,
				func(s string) (string, error) { return s, nil },
				func(d *protojsonxgen.Decoder) (*ChildMessage, error) {
					return protojsonxgen.UnmarshalMessageMapValue[ChildMessage](d, discardUnknown)
				}); err != nil {
				return false, err
			}
			x.MapStringMessage = m
		}
	}
	done, err := d.TryEndObject()
	if err != nil {
		return false, err
	}
	if !done {
		return false, nil
	}
	return true, nil
}

func (x *CompatibilityMessage) unmarshalProtoJSONXFrom(d *protojsonxgen.Decoder, discardUnknown bool) error {
	if err := d.BeginObject(); err != nil {
		return err
	}
	var seenOneofs uint64
	var seen [12]bool
	first := true
	for {
		key, ok, err := d.NextObjectKey(&first)
		if err != nil {
			return err
		}
		if !ok {
			return nil
		}
		switch key {
		case "nameChoice", "name_choice":
			if seen[0] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[0] = true
			if d.ReadNull() {
				if _, ok := x.Choice.(*CompatibilityMessage_NameChoice); ok {
					x.Choice = nil
				}
			} else {
				if seenOneofs&(1<<0) != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seenOneofs |= (1 << 0)
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				x.Choice = &CompatibilityMessage_NameChoice{NameChoice: v}
			}
			continue
		case "numberChoice", "number_choice":
			if seen[1] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[1] = true
			if d.ReadNull() {
				if _, ok := x.Choice.(*CompatibilityMessage_NumberChoice); ok {
					x.Choice = nil
				}
			} else {
				if seenOneofs&(1<<0) != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seenOneofs |= (1 << 0)
				v, err := d.ReadInt32()
				if err != nil {
					return err
				}
				x.Choice = &CompatibilityMessage_NumberChoice{NumberChoice: v}
			}
			continue
		case "childChoice", "child_choice":
			if seen[2] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[2] = true
			if d.ReadNull() {
				if _, ok := x.Choice.(*CompatibilityMessage_ChildChoice); ok {
					x.Choice = nil
				}
			} else {
				if seenOneofs&(1<<0) != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seenOneofs |= (1 << 0)
				v := &ChildMessage{}
				if slow, ok := any(v).(interface {
					unmarshalProtoJSONXFrom(*protojsonxgen.Decoder, bool) error
				}); ok {
					if err := slow.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
						return err
					}
				} else {
					if err := protojsonxgen.UnmarshalField(d, v, discardUnknown); err != nil {
						return err
					}
				}
				x.Choice = &CompatibilityMessage_ChildChoice{ChildChoice: v}
			}
			continue
		case "optionalString", "optional_string":
			if seen[3] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[3] = true
			if d.ReadNull() {
				x.OptionalString = nil
			} else {
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				x.OptionalString = &v
			}
			continue
		case "optionalInt32", "optional_int32":
			if seen[4] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[4] = true
			if d.ReadNull() {
				x.OptionalInt32 = nil
			} else {
				v, err := d.ReadInt32()
				if err != nil {
					return err
				}
				x.OptionalInt32 = &v
			}
			continue
		case "repeatedInt32", "repeated_int32":
			if seen[5] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[5] = true
			if d.ReadNull() {
				x.RepeatedInt32 = nil
			} else {
				values := x.RepeatedInt32[:0]
				if values == nil {
					values = make([]int32, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					v, err := d.ReadInt32()
					if err != nil {
						return err
					}
					values = append(values, v)
				}
				x.RepeatedInt32 = values
			}
			continue
		case "repeatedBool", "repeated_bool":
			if seen[6] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[6] = true
			if d.ReadNull() {
				x.RepeatedBool = nil
			} else {
				values := x.RepeatedBool[:0]
				if values == nil {
					values = make([]bool, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					v, err := d.ReadBool()
					if err != nil {
						return err
					}
					values = append(values, v)
				}
				x.RepeatedBool = values
			}
			continue
		case "repeatedBytes", "repeated_bytes":
			if seen[7] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[7] = true
			if d.ReadNull() {
				x.RepeatedBytes = nil
			} else {
				values := x.RepeatedBytes[:0]
				if values == nil {
					values = make([][]byte, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					v, err := d.ReadBytes()
					if err != nil {
						return err
					}
					values = append(values, v)
				}
				x.RepeatedBytes = values
			}
			continue
		case "repeatedEnum", "repeated_enum":
			if seen[8] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[8] = true
			if d.ReadNull() {
				x.RepeatedEnum = nil
			} else {
				values := x.RepeatedEnum[:0]
				if values == nil {
					values = make([]TestEnum, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					var v TestEnum
					{
						val, err := unmarshalEnum_TestEnum(d, discardUnknown)
						if err != nil {
							return err
						}
						v = val
					}
					values = append(values, v)
				}
				x.RepeatedEnum = values
			}
			continue
		case "mapStringInt32", "map_string_int32":
			if seen[9] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[9] = true
			if d.ReadNull() {
				x.MapStringInt32 = nil
			} else {
				m := make(map[string]int32)
				if err := protojsonxgen.ReadMap(d, m,
					func(s string) (string, error) { return s, nil },
					func(d *protojsonxgen.Decoder) (int32, error) { return d.ReadInt32() }); err != nil {
					return err
				}
				x.MapStringInt32 = m
			}
			continue
		case "mapInt32String", "map_int32_string":
			if seen[10] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[10] = true
			if d.ReadNull() {
				x.MapInt32String = nil
			} else {
				m := make(map[int32]string)
				if err := protojsonxgen.ReadMap(d, m,
					func(s string) (int32, error) { val, err := strconv.ParseInt(s, 10, 32); return int32(val), err },
					func(d *protojsonxgen.Decoder) (string, error) { return d.ReadString() }); err != nil {
					return err
				}
				x.MapInt32String = m
			}
			continue
		case "mapStringMessage", "map_string_message":
			if seen[11] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[11] = true
			if d.ReadNull() {
				x.MapStringMessage = nil
			} else {
				m := make(map[string]*ChildMessage)
				if err := protojsonxgen.ReadMap(d, m,
					func(s string) (string, error) { return s, nil },
					func(d *protojsonxgen.Decoder) (*ChildMessage, error) {
						return protojsonxgen.UnmarshalMessageMapValue[ChildMessage](d, discardUnknown)
					}); err != nil {
					return err
				}
				x.MapStringMessage = m
			}
			continue
		default:
			if discardUnknown {
				if err := d.SkipValue(); err != nil {
					return err
				}
			} else {
				return protojsonxgen.UnknownField(key)
			}
		}
	}
}

func unmarshalEnum_TestEnum(d *protojsonxgen.Decoder, discardUnknown bool) (TestEnum, error) {
	var v TestEnum
	if d.IsString() {
		s, err := d.ReadStringBytes()
		if err != nil {
			return 0, err
		}
		if protojsonxgen.MatchStringBytes(s, "TEST_ENUM_UNSPECIFIED") {
			v = TestEnum_TEST_ENUM_UNSPECIFIED
		} else if protojsonxgen.MatchStringBytes(s, "TEST_ENUM_FIRST") {
			v = TestEnum_TEST_ENUM_FIRST
		} else if protojsonxgen.MatchStringBytes(s, "TEST_ENUM_SECOND") {
			v = TestEnum_TEST_ENUM_SECOND
		} else {
			if discardUnknown {
				return 0, nil
			} else {
				return 0, protojsonxgen.UnknownEnumValue(string(s))
			}
		}
	} else {
		n, err := d.ReadInt32()
		if err != nil {
			return 0, err
		}
		v = TestEnum(n)
	}
	return v, nil
}
