// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: test_shapes.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestEnum int32

const (
	TestEnum_TEST_ENUM_UNSPECIFIED TestEnum = 0
	TestEnum_TEST_ENUM_FIRST       TestEnum = 1
	TestEnum_TEST_ENUM_SECOND      TestEnum = 2
)

// Enum value maps for TestEnum.
var (
	TestEnum_name = map[int32]string{
		0: "TEST_ENUM_UNSPECIFIED",
		1: "TEST_ENUM_FIRST",
		2: "TEST_ENUM_SECOND",
	}
	TestEnum_value = map[string]int32{
		"TEST_ENUM_UNSPECIFIED": 0,
		"TEST_ENUM_FIRST":       1,
		"TEST_ENUM_SECOND":      2,
	}
)

func (x TestEnum) Enum() *TestEnum {
	p := new(TestEnum)
	*p = x
	return p
}

func (x TestEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_test_shapes_proto_enumTypes[0].Descriptor()
}

func (TestEnum) Type() protoreflect.EnumType {
	return &file_test_shapes_proto_enumTypes[0]
}

func (x TestEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestEnum.Descriptor instead.
func (TestEnum) EnumDescriptor() ([]byte, []int) {
	return file_test_shapes_proto_rawDescGZIP(), []int{0}
}

type ComplexMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Primitives
	DoubleField   float64  `protobuf:"fixed64,1,opt,name=double_field,json=doubleField,proto3" json:"double_field,omitempty"`
	FloatField    float32  `protobuf:"fixed32,2,opt,name=float_field,json=floatField,proto3" json:"float_field,omitempty"`
	Int32Field    int32    `protobuf:"varint,3,opt,name=int32_field,json=int32Field,proto3" json:"int32_field,omitempty"`
	Int64Field    int64    `protobuf:"varint,4,opt,name=int64_field,json=int64Field,proto3" json:"int64_field,omitempty"`
	Uint32Field   uint32   `protobuf:"varint,5,opt,name=uint32_field,json=uint32Field,proto3" json:"uint32_field,omitempty"`
	Uint64Field   uint64   `protobuf:"varint,6,opt,name=uint64_field,json=uint64Field,proto3" json:"uint64_field,omitempty"`
	Sint32Field   int32    `protobuf:"zigzag32,7,opt,name=sint32_field,json=sint32Field,proto3" json:"sint32_field,omitempty"`
	Sint64Field   int64    `protobuf:"zigzag64,8,opt,name=sint64_field,json=sint64Field,proto3" json:"sint64_field,omitempty"`
	Fixed32Field  uint32   `protobuf:"fixed32,9,opt,name=fixed32_field,json=fixed32Field,proto3" json:"fixed32_field,omitempty"`
	Fixed64Field  uint64   `protobuf:"fixed64,10,opt,name=fixed64_field,json=fixed64Field,proto3" json:"fixed64_field,omitempty"`
	Sfixed32Field int32    `protobuf:"fixed32,11,opt,name=sfixed32_field,json=sfixed32Field,proto3" json:"sfixed32_field,omitempty"`
	Sfixed64Field int64    `protobuf:"fixed64,12,opt,name=sfixed64_field,json=sfixed64Field,proto3" json:"sfixed64_field,omitempty"`
	BoolField     bool     `protobuf:"varint,13,opt,name=bool_field,json=boolField,proto3" json:"bool_field,omitempty"`
	StringField   string   `protobuf:"bytes,14,opt,name=string_field,json=stringField,proto3" json:"string_field,omitempty"`
	BytesField    []byte   `protobuf:"bytes,15,opt,name=bytes_field,json=bytesField,proto3" json:"bytes_field,omitempty"`
	EnumField     TestEnum `protobuf:"varint,16,opt,name=enum_field,json=enumField,proto3,enum=testshapes.TestEnum" json:"enum_field,omitempty"`
	// Well-Known Types
	TimestampField *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=timestamp_field,json=timestampField,proto3" json:"timestamp_field,omitempty"`
	DurationField  *durationpb.Duration   `protobuf:"bytes,18,opt,name=duration_field,json=durationField,proto3" json:"duration_field,omitempty"`
	// Nested message
	ChildField *ChildMessage `protobuf:"bytes,19,opt,name=child_field,json=childField,proto3" json:"child_field,omitempty"`
	// Repeated
	RepeatedString  []string        `protobuf:"bytes,20,rep,name=repeated_string,json=repeatedString,proto3" json:"repeated_string,omitempty"`
	RepeatedMessage []*ChildMessage `protobuf:"bytes,21,rep,name=repeated_message,json=repeatedMessage,proto3" json:"repeated_message,omitempty"`
	// Map
	MapStringString map[string]string `protobuf:"bytes,22,rep,name=map_string_string,json=mapStringString,proto3" json:"map_string_string,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ComplexMessage) Reset() {
	*x = ComplexMessage{}
	mi := &file_test_shapes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplexMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexMessage) ProtoMessage() {}

func (x *ComplexMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_shapes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexMessage.ProtoReflect.Descriptor instead.
func (*ComplexMessage) Descriptor() ([]byte, []int) {
	return file_test_shapes_proto_rawDescGZIP(), []int{0}
}

func (x *ComplexMessage) GetDoubleField() float64 {
	if x != nil {
		return x.DoubleField
	}
	return 0
}

func (x *ComplexMessage) GetFloatField() float32 {
	if x != nil {
		return x.FloatField
	}
	return 0
}

func (x *ComplexMessage) GetInt32Field() int32 {
	if x != nil {
		return x.Int32Field
	}
	return 0
}

func (x *ComplexMessage) GetInt64Field() int64 {
	if x != nil {
		return x.Int64Field
	}
	return 0
}

func (x *ComplexMessage) GetUint32Field() uint32 {
	if x != nil {
		return x.Uint32Field
	}
	return 0
}

func (x *ComplexMessage) GetUint64Field() uint64 {
	if x != nil {
		return x.Uint64Field
	}
	return 0
}

func (x *ComplexMessage) GetSint32Field() int32 {
	if x != nil {
		return x.Sint32Field
	}
	return 0
}

func (x *ComplexMessage) GetSint64Field() int64 {
	if x != nil {
		return x.Sint64Field
	}
	return 0
}

func (x *ComplexMessage) GetFixed32Field() uint32 {
	if x != nil {
		return x.Fixed32Field
	}
	return 0
}

func (x *ComplexMessage) GetFixed64Field() uint64 {
	if x != nil {
		return x.Fixed64Field
	}
	return 0
}

func (x *ComplexMessage) GetSfixed32Field() int32 {
	if x != nil {
		return x.Sfixed32Field
	}
	return 0
}

func (x *ComplexMessage) GetSfixed64Field() int64 {
	if x != nil {
		return x.Sfixed64Field
	}
	return 0
}

func (x *ComplexMessage) GetBoolField() bool {
	if x != nil {
		return x.BoolField
	}
	return false
}

func (x *ComplexMessage) GetStringField() string {
	if x != nil {
		return x.StringField
	}
	return ""
}

func (x *ComplexMessage) GetBytesField() []byte {
	if x != nil {
		return x.BytesField
	}
	return nil
}

func (x *ComplexMessage) GetEnumField() TestEnum {
	if x != nil {
		return x.EnumField
	}
	return TestEnum_TEST_ENUM_UNSPECIFIED
}

func (x *ComplexMessage) GetTimestampField() *timestamppb.Timestamp {
	if x != nil {
		return x.TimestampField
	}
	return nil
}

func (x *ComplexMessage) GetDurationField() *durationpb.Duration {
	if x != nil {
		return x.DurationField
	}
	return nil
}

func (x *ComplexMessage) GetChildField() *ChildMessage {
	if x != nil {
		return x.ChildField
	}
	return nil
}

func (x *ComplexMessage) GetRepeatedString() []string {
	if x != nil {
		return x.RepeatedString
	}
	return nil
}

func (x *ComplexMessage) GetRepeatedMessage() []*ChildMessage {
	if x != nil {
		return x.RepeatedMessage
	}
	return nil
}

func (x *ComplexMessage) GetMapStringString() map[string]string {
	if x != nil {
		return x.MapStringString
	}
	return nil
}

type ChildMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChildMessage) Reset() {
	*x = ChildMessage{}
	mi := &file_test_shapes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChildMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildMessage) ProtoMessage() {}

func (x *ChildMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_shapes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChildMessage.ProtoReflect.Descriptor instead.
func (*ChildMessage) Descriptor() ([]byte, []int) {
	return file_test_shapes_proto_rawDescGZIP(), []int{1}
}

func (x *ChildMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChildMessage) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SpecMessage struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	AnyField         *anypb.Any              `protobuf:"bytes,1,opt,name=any_field,json=anyField,proto3" json:"any_field,omitempty"`
	EmptyField       *emptypb.Empty          `protobuf:"bytes,2,opt,name=empty_field,json=emptyField,proto3" json:"empty_field,omitempty"`
	FieldMaskField   *fieldmaskpb.FieldMask  `protobuf:"bytes,3,opt,name=field_mask_field,json=fieldMaskField,proto3" json:"field_mask_field,omitempty"`
	DoubleValueField *wrapperspb.DoubleValue `protobuf:"bytes,7,opt,name=double_value_field,json=doubleValueField,proto3" json:"double_value_field,omitempty"`
	FloatValueField  *wrapperspb.FloatValue  `protobuf:"bytes,8,opt,name=float_value_field,json=floatValueField,proto3" json:"float_value_field,omitempty"`
	Int64ValueField  *wrapperspb.Int64Value  `protobuf:"bytes,9,opt,name=int64_value_field,json=int64ValueField,proto3" json:"int64_value_field,omitempty"`
	Uint64ValueField *wrapperspb.UInt64Value `protobuf:"bytes,10,opt,name=uint64_value_field,json=uint64ValueField,proto3" json:"uint64_value_field,omitempty"`
	Int32ValueField  *wrapperspb.Int32Value  `protobuf:"bytes,11,opt,name=int32_value_field,json=int32ValueField,proto3" json:"int32_value_field,omitempty"`
	Uint32ValueField *wrapperspb.UInt32Value `protobuf:"bytes,12,opt,name=uint32_value_field,json=uint32ValueField,proto3" json:"uint32_value_field,omitempty"`
	BoolValueField   *wrapperspb.BoolValue   `protobuf:"bytes,13,opt,name=bool_value_field,json=boolValueField,proto3" json:"bool_value_field,omitempty"`
	StringValueField *wrapperspb.StringValue `protobuf:"bytes,14,opt,name=string_value_field,json=stringValueField,proto3" json:"string_value_field,omitempty"`
	BytesValueField  *wrapperspb.BytesValue  `protobuf:"bytes,15,opt,name=bytes_value_field,json=bytesValueField,proto3" json:"bytes_value_field,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SpecMessage) Reset() {
	*x = SpecMessage{}
	mi := &file_test_shapes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecMessage) ProtoMessage() {}

func (x *SpecMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_shapes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecMessage.ProtoReflect.Descriptor instead.
func (*SpecMessage) Descriptor() ([]byte, []int) {
	return file_test_shapes_proto_rawDescGZIP(), []int{2}
}

func (x *SpecMessage) GetAnyField() *anypb.Any {
	if x != nil {
		return x.AnyField
	}
	return nil
}

func (x *SpecMessage) GetEmptyField() *emptypb.Empty {
	if x != nil {
		return x.EmptyField
	}
	return nil
}

func (x *SpecMessage) GetFieldMaskField() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMaskField
	}
	return nil
}

func (x *SpecMessage) GetDoubleValueField() *wrapperspb.DoubleValue {
	if x != nil {
		return x.DoubleValueField
	}
	return nil
}

func (x *SpecMessage) GetFloatValueField() *wrapperspb.FloatValue {
	if x != nil {
		return x.FloatValueField
	}
	return nil
}

func (x *SpecMessage) GetInt64ValueField() *wrapperspb.Int64Value {
	if x != nil {
		return x.Int64ValueField
	}
	return nil
}

func (x *SpecMessage) GetUint64ValueField() *wrapperspb.UInt64Value {
	if x != nil {
		return x.Uint64ValueField
	}
	return nil
}

func (x *SpecMessage) GetInt32ValueField() *wrapperspb.Int32Value {
	if x != nil {
		return x.Int32ValueField
	}
	return nil
}

func (x *SpecMessage) GetUint32ValueField() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Uint32ValueField
	}
	return nil
}

func (x *SpecMessage) GetBoolValueField() *wrapperspb.BoolValue {
	if x != nil {
		return x.BoolValueField
	}
	return nil
}

func (x *SpecMessage) GetStringValueField() *wrapperspb.StringValue {
	if x != nil {
		return x.StringValueField
	}
	return nil
}

func (x *SpecMessage) GetBytesValueField() *wrapperspb.BytesValue {
	if x != nil {
		return x.BytesValueField
	}
	return nil
}

type StructMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StructField   *structpb.Struct       `protobuf:"bytes,1,opt,name=struct_field,json=structField,proto3" json:"struct_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructMessage) Reset() {
	*x = StructMessage{}
	mi := &file_test_shapes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructMessage) ProtoMessage() {}

func (x *StructMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_shapes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructMessage.ProtoReflect.Descriptor instead.
func (*StructMessage) Descriptor() ([]byte, []int) {
	return file_test_shapes_proto_rawDescGZIP(), []int{3}
}

func (x *StructMessage) GetStructField() *structpb.Struct {
	if x != nil {
		return x.StructField
	}
	return nil
}

type ValueMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ValueField    *structpb.Value        `protobuf:"bytes,1,opt,name=value_field,json=valueField,proto3" json:"value_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueMessage) Reset() {
	*x = ValueMessage{}
	mi := &file_test_shapes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueMessage) ProtoMessage() {}

func (x *ValueMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_shapes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueMessage.ProtoReflect.Descriptor instead.
func (*ValueMessage) Descriptor() ([]byte, []int) {
	return file_test_shapes_proto_rawDescGZIP(), []int{4}
}

func (x *ValueMessage) GetValueField() *structpb.Value {
	if x != nil {
		return x.ValueField
	}
	return nil
}

type ListValueMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ListValueField *structpb.ListValue    `protobuf:"bytes,1,opt,name=list_value_field,json=listValueField,proto3" json:"list_value_field,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListValueMessage) Reset() {
	*x = ListValueMessage{}
	mi := &file_test_shapes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValueMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValueMessage) ProtoMessage() {}

func (x *ListValueMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_shapes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValueMessage.ProtoReflect.Descriptor instead.
func (*ListValueMessage) Descriptor() ([]byte, []int) {
	return file_test_shapes_proto_rawDescGZIP(), []int{5}
}

func (x *ListValueMessage) GetListValueField() *structpb.ListValue {
	if x != nil {
		return x.ListValueField
	}
	return nil
}

type RepeatedScalarsMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RepeatedInt32  []int32                `protobuf:"varint,1,rep,packed,name=repeated_int32,json=repeatedInt32,proto3" json:"repeated_int32,omitempty"`
	RepeatedInt64  []int64                `protobuf:"varint,2,rep,packed,name=repeated_int64,json=repeatedInt64,proto3" json:"repeated_int64,omitempty"`
	RepeatedUint32 []uint32               `protobuf:"varint,3,rep,packed,name=repeated_uint32,json=repeatedUint32,proto3" json:"repeated_uint32,omitempty"`
	RepeatedUint64 []uint64               `protobuf:"varint,4,rep,packed,name=repeated_uint64,json=repeatedUint64,proto3" json:"repeated_uint64,omitempty"`
	RepeatedFloat  []float32              `protobuf:"fixed32,5,rep,packed,name=repeated_float,json=repeatedFloat,proto3" json:"repeated_float,omitempty"`
	RepeatedDouble []float64              `protobuf:"fixed64,6,rep,packed,name=repeated_double,json=repeatedDouble,proto3" json:"repeated_double,omitempty"`
	RepeatedBool   []bool                 `protobuf:"varint,7,rep,packed,name=repeated_bool,json=repeatedBool,proto3" json:"repeated_bool,omitempty"`
	RepeatedBytes  [][]byte               `protobuf:"bytes,8,rep,name=repeated_bytes,json=repeatedBytes,proto3" json:"repeated_bytes,omitempty"`
	RepeatedEnum   []TestEnum             `protobuf:"varint,9,rep,packed,name=repeated_enum,json=repeatedEnum,proto3,enum=testshapes.TestEnum" json:"repeated_enum,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RepeatedScalarsMessage) Reset() {
	*x = RepeatedScalarsMessage{}
	mi := &file_test_shapes_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedScalarsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedScalarsMessage) ProtoMessage() {}

func (x *RepeatedScalarsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_shapes_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedScalarsMessage.ProtoReflect.Descriptor instead.
func (*RepeatedScalarsMessage) Descriptor() ([]byte, []int) {
	return file_test_shapes_proto_rawDescGZIP(), []int{6}
}

func (x *RepeatedScalarsMessage) GetRepeatedInt32() []int32 {
	if x != nil {
		return x.RepeatedInt32
	}
	return nil
}

func (x *RepeatedScalarsMessage) GetRepeatedInt64() []int64 {
	if x != nil {
		return x.RepeatedInt64
	}
	return nil
}

func (x *RepeatedScalarsMessage) GetRepeatedUint32() []uint32 {
	if x != nil {
		return x.RepeatedUint32
	}
	return nil
}

func (x *RepeatedScalarsMessage) GetRepeatedUint64() []uint64 {
	if x != nil {
		return x.RepeatedUint64
	}
	return nil
}

func (x *RepeatedScalarsMessage) GetRepeatedFloat() []float32 {
	if x != nil {
		return x.RepeatedFloat
	}
	return nil
}

func (x *RepeatedScalarsMessage) GetRepeatedDouble() []float64 {
	if x != nil {
		return x.RepeatedDouble
	}
	return nil
}

func (x *RepeatedScalarsMessage) GetRepeatedBool() []bool {
	if x != nil {
		return x.RepeatedBool
	}
	return nil
}

func (x *RepeatedScalarsMessage) GetRepeatedBytes() [][]byte {
	if x != nil {
		return x.RepeatedBytes
	}
	return nil
}

func (x *RepeatedScalarsMessage) GetRepeatedEnum() []TestEnum {
	if x != nil {
		return x.RepeatedEnum
	}
	return nil
}

type CompatibilityMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Choice:
	//
	//	*CompatibilityMessage_NameChoice
	//	*CompatibilityMessage_NumberChoice
	//	*CompatibilityMessage_ChildChoice
	Choice           isCompatibilityMessage_Choice `protobuf_oneof:"choice"`
	OptionalString   *string                       `protobuf:"bytes,4,opt,name=optional_string,json=optionalString,proto3,oneof" json:"optional_string,omitempty"`
	OptionalInt32    *int32                        `protobuf:"varint,5,opt,name=optional_int32,json=optionalInt32,proto3,oneof" json:"optional_int32,omitempty"`
	RepeatedInt32    []int32                       `protobuf:"varint,6,rep,packed,name=repeated_int32,json=repeatedInt32,proto3" json:"repeated_int32,omitempty"`
	RepeatedBool     []bool                        `protobuf:"varint,7,rep,packed,name=repeated_bool,json=repeatedBool,proto3" json:"repeated_bool,omitempty"`
	RepeatedBytes    [][]byte                      `protobuf:"bytes,8,rep,name=repeated_bytes,json=repeatedBytes,proto3" json:"repeated_bytes,omitempty"`
	RepeatedEnum     []TestEnum                    `protobuf:"varint,9,rep,packed,name=repeated_enum,json=repeatedEnum,proto3,enum=testshapes.TestEnum" json:"repeated_enum,omitempty"`
	MapStringInt32   map[string]int32              `protobuf:"bytes,10,rep,name=map_string_int32,json=mapStringInt32,proto3" json:"map_string_int32,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	MapInt32String   map[int32]string              `protobuf:"bytes,11,rep,name=map_int32_string,json=mapInt32String,proto3" json:"map_int32_string,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapStringMessage map[string]*ChildMessage      `protobuf:"bytes,12,rep,name=map_string_message,json=mapStringMessage,proto3" json:"map_string_message,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CompatibilityMessage) Reset() {
	*x = CompatibilityMessage{}
	mi := &file_test_shapes_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompatibilityMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompatibilityMessage) ProtoMessage() {}

func (x *CompatibilityMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_shapes_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompatibilityMessage.ProtoReflect.Descriptor instead.
func (*CompatibilityMessage) Descriptor() ([]byte, []int) {
	return file_test_shapes_proto_rawDescGZIP(), []int{7}
}

func (x *CompatibilityMessage) GetChoice() isCompatibilityMessage_Choice {
	if x != nil {
		return x.Choice
	}
	return nil
}

func (x *CompatibilityMessage) GetNameChoice() string {
	if x != nil {
		if x, ok := x.Choice.(*CompatibilityMessage_NameChoice); ok {
			return x.NameChoice
		}
	}
	return ""
}

func (x *CompatibilityMessage) GetNumberChoice() int32 {
	if x != nil {
		if x, ok := x.Choice.(*CompatibilityMessage_NumberChoice); ok {
			return x.NumberChoice
		}
	}
	return 0
}

func (x *CompatibilityMessage) GetChildChoice() *ChildMessage {
	if x != nil {
		if x, ok := x.Choice.(*CompatibilityMessage_ChildChoice); ok {
			return x.ChildChoice
		}
	}
	return nil
}

func (x *CompatibilityMessage) GetOptionalString() string {
	if x != nil && x.OptionalString != nil {
		return *x.OptionalString
	}
	return ""
}

func (x *CompatibilityMessage) GetOptionalInt32() int32 {
	if x != nil && x.OptionalInt32 != nil {
		return *x.OptionalInt32
	}
	return 0
}

func (x *CompatibilityMessage) GetRepeatedInt32() []int32 {
	if x != nil {
		return x.RepeatedInt32
	}
	return nil
}

func (x *CompatibilityMessage) GetRepeatedBool() []bool {
	if x != nil {
		return x.RepeatedBool
	}
	return nil
}

func (x *CompatibilityMessage) GetRepeatedBytes() [][]byte {
	if x != nil {
		return x.RepeatedBytes
	}
	return nil
}

func (x *CompatibilityMessage) GetRepeatedEnum() []TestEnum {
	if x != nil {
		return x.RepeatedEnum
	}
	return nil
}

func (x *CompatibilityMessage) GetMapStringInt32() map[string]int32 {
	if x != nil {
		return x.MapStringInt32
	}
	return nil
}

func (x *CompatibilityMessage) GetMapInt32String() map[int32]string {
	if x != nil {
		return x.MapInt32String
	}
	return nil
}

func (x *CompatibilityMessage) GetMapStringMessage() map[string]*ChildMessage {
	if x != nil {
		return x.MapStringMessage
	}
	return nil
}

type isCompatibilityMessage_Choice interface {
	isCompatibilityMessage_Choice()
}

type CompatibilityMessage_NameChoice struct {
	NameChoice string `protobuf:"bytes,1,opt,name=name_choice,json=nameChoice,proto3,oneof"`
}

type CompatibilityMessage_NumberChoice struct {
	NumberChoice int32 `protobuf:"varint,2,opt,name=number_choice,json=numberChoice,proto3,oneof"`
}

type CompatibilityMessage_ChildChoice struct {
	ChildChoice *ChildMessage `protobuf:"bytes,3,opt,name=child_choice,json=childChoice,proto3,oneof"`
}

func (*CompatibilityMessage_NameChoice) isCompatibilityMessage_Choice() {}

func (*CompatibilityMessage_NumberChoice) isCompatibilityMessage_Choice() {}

func (*CompatibilityMessage_ChildChoice) isCompatibilityMessage_Choice() {}

var File_test_shapes_proto protoreflect.FileDescriptor

const file_test_shapes_proto_rawDesc = "" +
	"\n" +
	"\x11test_shapes.proto\x12\n" +
	"testshapes\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xa3\b\n" +
	"\x0eComplexMessage\x12!\n" +
	"\fdouble_field\x18\x01 \x01(\x01R\vdoubleField\x12\x1f\n" +
	"\vfloat_field\x18\x02 \x01(\x02R\n" +
	"floatField\x12\x1f\n" +
	"\vint32_field\x18\x03 \x01(\x05R\n" +
	"int32Field\x12\x1f\n" +
	"\vint64_field\x18\x04 \x01(\x03R\n" +
	"int64Field\x12!\n" +
	"\fuint32_field\x18\x05 \x01(\rR\vuint32Field\x12!\n" +
	"\fuint64_field\x18\x06 \x01(\x04R\vuint64Field\x12!\n" +
	"\fsint32_field\x18\a \x01(\x11R\vsint32Field\x12!\n" +
	"\fsint64_field\x18\b \x01(\x12R\vsint64Field\x12#\n" +
	"\rfixed32_field\x18\t \x01(\aR\ffixed32Field\x12#\n" +
	"\rfixed64_field\x18\n" +
	" \x01(\x06R\ffixed64Field\x12%\n" +
	"\x0esfixed32_field\x18\v \x01(\x0fR\rsfixed32Field\x12%\n" +
	"\x0esfixed64_field\x18\f \x01(\x10R\rsfixed64Field\x12\x1d\n" +
	"\n" +
	"bool_field\x18\r \x01(\bR\tboolField\x12!\n" +
	"\fstring_field\x18\x0e \x01(\tR\vstringField\x12\x1f\n" +
	"\vbytes_field\x18\x0f \x01(\fR\n" +
	"bytesField\x123\n" +
	"\n" +
	"enum_field\x18\x10 \x01(\x0e2\x14.testshapes.TestEnumR\tenumField\x12C\n" +
	"\x0ftimestamp_field\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\x0etimestampField\x12@\n" +
	"\x0eduration_field\x18\x12 \x01(\v2\x19.google.protobuf.DurationR\rdurationField\x129\n" +
	"\vchild_field\x18\x13 \x01(\v2\x18.testshapes.ChildMessageR\n" +
	"childField\x12'\n" +
	"\x0frepeated_string\x18\x14 \x03(\tR\x0erepeatedString\x12C\n" +
	"\x10repeated_message\x18\x15 \x03(\v2\x18.testshapes.ChildMessageR\x0frepeatedMessage\x12[\n" +
	"\x11map_string_string\x18\x16 \x03(\v2/.testshapes.ComplexMessage.MapStringStringEntryR\x0fmapStringString\x1aB\n" +
	"\x14MapStringStringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\fChildMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\"\xd9\x06\n" +
	"\vSpecMessage\x121\n" +
	"\tany_field\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\banyField\x127\n" +
	"\vempty_field\x18\x02 \x01(\v2\x16.google.protobuf.EmptyR\n" +
	"emptyField\x12D\n" +
	"\x10field_mask_field\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\x0efieldMaskField\x12J\n" +
	"\x12double_value_field\x18\a \x01(\v2\x1c.google.protobuf.DoubleValueR\x10doubleValueField\x12G\n" +
	"\x11float_value_field\x18\b \x01(\v2\x1b.google.protobuf.FloatValueR\x0ffloatValueField\x12G\n" +
	"\x11int64_value_field\x18\t \x01(\v2\x1b.google.protobuf.Int64ValueR\x0fint64ValueField\x12J\n" +
	"\x12uint64_value_field\x18\n" +
	" \x01(\v2\x1c.google.protobuf.UInt64ValueR\x10uint64ValueField\x12G\n" +
	"\x11int32_value_field\x18\v \x01(\v2\x1b.google.protobuf.Int32ValueR\x0fint32ValueField\x12J\n" +
	"\x12uint32_value_field\x18\f \x01(\v2\x1c.google.protobuf.UInt32ValueR\x10uint32ValueField\x12D\n" +
	"\x10bool_value_field\x18\r \x01(\v2\x1a.google.protobuf.BoolValueR\x0eboolValueField\x12J\n" +
	"\x12string_value_field\x18\x0e \x01(\v2\x1c.google.protobuf.StringValueR\x10stringValueField\x12G\n" +
	"\x11bytes_value_field\x18\x0f \x01(\v2\x1b.google.protobuf.BytesValueR\x0fbytesValueField\"K\n" +
	"\rStructMessage\x12:\n" +
	"\fstruct_field\x18\x01 \x01(\v2\x17.google.protobuf.StructR\vstructField\"G\n" +
	"\fValueMessage\x127\n" +
	"\vvalue_field\x18\x01 \x01(\v2\x16.google.protobuf.ValueR\n" +
	"valueField\"X\n" +
	"\x10ListValueMessage\x12D\n" +
	"\x10list_value_field\x18\x01 \x01(\v2\x1a.google.protobuf.ListValueR\x0elistValueField\"\x8f\x03\n" +
	"\x16RepeatedScalarsMessage\x12%\n" +
	"\x0erepeated_int32\x18\x01 \x03(\x05R\rrepeatedInt32\x12%\n" +
	"\x0erepeated_int64\x18\x02 \x03(\x03R\rrepeatedInt64\x12'\n" +
	"\x0frepeated_uint32\x18\x03 \x03(\rR\x0erepeatedUint32\x12'\n" +
	"\x0frepeated_uint64\x18\x04 \x03(\x04R\x0erepeatedUint64\x12%\n" +
	"\x0erepeated_float\x18\x05 \x03(\x02R\rrepeatedFloat\x12'\n" +
	"\x0frepeated_double\x18\x06 \x03(\x01R\x0erepeatedDouble\x12#\n" +
	"\rrepeated_bool\x18\a \x03(\bR\frepeatedBool\x12%\n" +
	"\x0erepeated_bytes\x18\b \x03(\fR\rrepeatedBytes\x129\n" +
	"\rrepeated_enum\x18\t \x03(\x0e2\x14.testshapes.TestEnumR\frepeatedEnum\"\xe3\a\n" +
	"\x14CompatibilityMessage\x12!\n" +
	"\vname_choice\x18\x01 \x01(\tH\x00R\n" +
	"nameChoice\x12%\n" +
	"\rnumber_choice\x18\x02 \x01(\x05H\x00R\fnumberChoice\x12=\n" +
	"\fchild_choice\x18\x03 \x01(\v2\x18.testshapes.ChildMessageH\x00R\vchildChoice\x12,\n" +
	"\x0foptional_string\x18\x04 \x01(\tH\x01R\x0eoptionalString\x88\x01\x01\x12*\n" +
	"\x0eoptional_int32\x18\x05 \x01(\x05H\x02R\roptionalInt32\x88\x01\x01\x12%\n" +
	"\x0erepeated_int32\x18\x06 \x03(\x05R\rrepeatedInt32\x12#\n" +
	"\rrepeated_bool\x18\a \x03(\bR\frepeatedBool\x12%\n" +
	"\x0erepeated_bytes\x18\b \x03(\fR\rrepeatedBytes\x129\n" +
	"\rrepeated_enum\x18\t \x03(\x0e2\x14.testshapes.TestEnumR\frepeatedEnum\x12^\n" +
	"\x10map_string_int32\x18\n" +
	" \x03(\v24.testshapes.CompatibilityMessage.MapStringInt32EntryR\x0emapStringInt32\x12^\n" +
	"\x10map_int32_string\x18\v \x03(\v24.testshapes.CompatibilityMessage.MapInt32StringEntryR\x0emapInt32String\x12d\n" +
	"\x12map_string_message\x18\f \x03(\v26.testshapes.CompatibilityMessage.MapStringMessageEntryR\x10mapStringMessage\x1aA\n" +
	"\x13MapStringInt32Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aA\n" +
	"\x13MapInt32StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a]\n" +
	"\x15MapStringMessageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.testshapes.ChildMessageR\x05value:\x028\x01B\b\n" +
	"\x06choiceB\x12\n" +
	"\x10_optional_stringB\x11\n" +
	"\x0f_optional_int32*P\n" +
	"\bTestEnum\x12\x19\n" +
	"\x15TEST_ENUM_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fTEST_ENUM_FIRST\x10\x01\x12\x14\n" +
	"\x10TEST_ENUM_SECOND\x10\x02B2Z0github.com/sudorandom/protojsonx/internal/testpbb\x06proto3"

var (
	file_test_shapes_proto_rawDescOnce sync.Once
	file_test_shapes_proto_rawDescData []byte
)

func file_test_shapes_proto_rawDescGZIP() []byte {
	file_test_shapes_proto_rawDescOnce.Do(func() {
		file_test_shapes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_shapes_proto_rawDesc), len(file_test_shapes_proto_rawDesc)))
	})
	return file_test_shapes_proto_rawDescData
}

var file_test_shapes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_shapes_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_test_shapes_proto_goTypes = []any{
	(TestEnum)(0),                  // 0: testshapes.TestEnum
	(*ComplexMessage)(nil),         // 1: testshapes.ComplexMessage
	(*ChildMessage)(nil),           // 2: testshapes.ChildMessage
	(*SpecMessage)(nil),            // 3: testshapes.SpecMessage
	(*StructMessage)(nil),          // 4: testshapes.StructMessage
	(*ValueMessage)(nil),           // 5: testshapes.ValueMessage
	(*ListValueMessage)(nil),       // 6: testshapes.ListValueMessage
	(*RepeatedScalarsMessage)(nil), // 7: testshapes.RepeatedScalarsMessage
	(*CompatibilityMessage)(nil),   // 8: testshapes.CompatibilityMessage
	nil,                            // 9: testshapes.ComplexMessage.MapStringStringEntry
	nil,                            // 10: testshapes.CompatibilityMessage.MapStringInt32Entry
	nil,                            // 11: testshapes.CompatibilityMessage.MapInt32StringEntry
	nil,                            // 12: testshapes.CompatibilityMessage.MapStringMessageEntry
	(*timestamppb.Timestamp)(nil),  // 13: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),    // 14: google.protobuf.Duration
	(*anypb.Any)(nil),              // 15: google.protobuf.Any
	(*emptypb.Empty)(nil),          // 16: google.protobuf.Empty
	(*fieldmaskpb.FieldMask)(nil),  // 17: google.protobuf.FieldMask
	(*wrapperspb.DoubleValue)(nil), // 18: google.protobuf.DoubleValue
	(*wrapperspb.FloatValue)(nil),  // 19: google.protobuf.FloatValue
	(*wrapperspb.Int64Value)(nil),  // 20: google.protobuf.Int64Value
	(*wrapperspb.UInt64Value)(nil), // 21: google.protobuf.UInt64Value
	(*wrapperspb.Int32Value)(nil),  // 22: google.protobuf.Int32Value
	(*wrapperspb.UInt32Value)(nil), // 23: google.protobuf.UInt32Value
	(*wrapperspb.BoolValue)(nil),   // 24: google.protobuf.BoolValue
	(*wrapperspb.StringValue)(nil), // 25: google.protobuf.StringValue
	(*wrapperspb.BytesValue)(nil),  // 26: google.protobuf.BytesValue
	(*structpb.Struct)(nil),        // 27: google.protobuf.Struct
	(*structpb.Value)(nil),         // 28: google.protobuf.Value
	(*structpb.ListValue)(nil),     // 29: google.protobuf.ListValue
}
var file_test_shapes_proto_depIdxs = []int32{
	0,  // 0: testshapes.ComplexMessage.enum_field:type_name -> testshapes.TestEnum
	13, // 1: testshapes.ComplexMessage.timestamp_field:type_name -> google.protobuf.Timestamp
	14, // 2: testshapes.ComplexMessage.duration_field:type_name -> google.protobuf.Duration
	2,  // 3: testshapes.ComplexMessage.child_field:type_name -> testshapes.ChildMessage
	2,  // 4: testshapes.ComplexMessage.repeated_message:type_name -> testshapes.ChildMessage
	9,  // 5: testshapes.ComplexMessage.map_string_string:type_name -> testshapes.ComplexMessage.MapStringStringEntry
	15, // 6: testshapes.SpecMessage.any_field:type_name -> google.protobuf.Any
	16, // 7: testshapes.SpecMessage.empty_field:type_name -> google.protobuf.Empty
	17, // 8: testshapes.SpecMessage.field_mask_field:type_name -> google.protobuf.FieldMask
	18, // 9: testshapes.SpecMessage.double_value_field:type_name -> google.protobuf.DoubleValue
	19, // 10: testshapes.SpecMessage.float_value_field:type_name -> google.protobuf.FloatValue
	20, // 11: testshapes.SpecMessage.int64_value_field:type_name -> google.protobuf.Int64Value
	21, // 12: testshapes.SpecMessage.uint64_value_field:type_name -> google.protobuf.UInt64Value
	22, // 13: testshapes.SpecMessage.int32_value_field:type_name -> google.protobuf.Int32Value
	23, // 14: testshapes.SpecMessage.uint32_value_field:type_name -> google.protobuf.UInt32Value
	24, // 15: testshapes.SpecMessage.bool_value_field:type_name -> google.protobuf.BoolValue
	25, // 16: testshapes.SpecMessage.string_value_field:type_name -> google.protobuf.StringValue
	26, // 17: testshapes.SpecMessage.bytes_value_field:type_name -> google.protobuf.BytesValue
	27, // 18: testshapes.StructMessage.struct_field:type_name -> google.protobuf.Struct
	28, // 19: testshapes.ValueMessage.value_field:type_name -> google.protobuf.Value
	29, // 20: testshapes.ListValueMessage.list_value_field:type_name -> google.protobuf.ListValue
	0,  // 21: testshapes.RepeatedScalarsMessage.repeated_enum:type_name -> testshapes.TestEnum
	2,  // 22: testshapes.CompatibilityMessage.child_choice:type_name -> testshapes.ChildMessage
	0,  // 23: testshapes.CompatibilityMessage.repeated_enum:type_name -> testshapes.TestEnum
	10, // 24: testshapes.CompatibilityMessage.map_string_int32:type_name -> testshapes.CompatibilityMessage.MapStringInt32Entry
	11, // 25: testshapes.CompatibilityMessage.map_int32_string:type_name -> testshapes.CompatibilityMessage.MapInt32StringEntry
	12, // 26: testshapes.CompatibilityMessage.map_string_message:type_name -> testshapes.CompatibilityMessage.MapStringMessageEntry
	2,  // 27: testshapes.CompatibilityMessage.MapStringMessageEntry.value:type_name -> testshapes.ChildMessage
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_test_shapes_proto_init() }
func file_test_shapes_proto_init() {
	if File_test_shapes_proto != nil {
		return
	}
	file_test_shapes_proto_msgTypes[7].OneofWrappers = []any{
		(*CompatibilityMessage_NameChoice)(nil),
		(*CompatibilityMessage_NumberChoice)(nil),
		(*CompatibilityMessage_ChildChoice)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_shapes_proto_rawDesc), len(file_test_shapes_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_shapes_proto_goTypes,
		DependencyIndexes: file_test_shapes_proto_depIdxs,
		EnumInfos:         file_test_shapes_proto_enumTypes,
		MessageInfos:      file_test_shapes_proto_msgTypes,
	}.Build()
	File_test_shapes_proto = out.File
	file_test_shapes_proto_goTypes = nil
	file_test_shapes_proto_depIdxs = nil
}
