// Code generated by protoc-gen-go-protojsonx. DO NOT EDIT.
// versions:
// 	protoc-gen-go-protojsonx v0.1.0
// source: test_shapes.proto

package testpb

import (
	protojsonxgen "github.com/sudorandom/protojsonx/protojsonxgen"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// This file is a placeholder for schema-specific protojsonx code.
// The generator is wired through protogen.Options so it follows the same
// module= and import-path behavior as protoc-gen-go.
const _ = "protojsonx generated scaffold 0.1.0"

func (x *ComplexMessage) MarshalProtoJSONX() ([]byte, error) {
	e := protojsonxgen.NewEncoder()
	if err := x.marshalProtoJSONXTo(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (x *ComplexMessage) UnmarshalProtoJSONX(data []byte) error {
	d := protojsonxgen.NewDecoder(data)
	*x = ComplexMessage{}
	firstKey, savedOff, savedDepth, _, peekErr := d.PeekObjectFieldName()
	if peekErr != nil {
		return peekErr
	}
	if firstKey == "doubleField" || firstKey == "" {
		d.Reset(savedOff, savedDepth)
		if ok, err := x.unmarshalProtoJSONXFast(d); err != nil {
			return err
		} else if ok {
			return d.Finish()
		}
		*x = ComplexMessage{}
	}
	d.Reset(savedOff, savedDepth)
	if err := x.unmarshalProtoJSONXFrom(d); err != nil {
		return err
	}
	return d.Finish()
}

func (x *ComplexMessage) marshalProtoJSONXTo(e *protojsonxgen.Encoder) error {
	e.Byte('{')
	wrote := false
	if x.DoubleField != 0 {
		e.FieldPrefix(&wrote, "doubleField")
		e.Float64(x.DoubleField)
	}
	if x.FloatField != 0 {
		e.FieldPrefix(&wrote, "floatField")
		e.Float32(x.FloatField)
	}
	if x.Int32Field != 0 {
		e.FieldPrefix(&wrote, "int32Field")
		e.Int32(x.Int32Field)
	}
	if x.Int64Field != 0 {
		e.FieldPrefix(&wrote, "int64Field")
		e.Int64String(x.Int64Field)
	}
	if x.Uint32Field != 0 {
		e.FieldPrefix(&wrote, "uint32Field")
		e.Uint32(x.Uint32Field)
	}
	if x.Uint64Field != 0 {
		e.FieldPrefix(&wrote, "uint64Field")
		e.Uint64String(x.Uint64Field)
	}
	if x.Sint32Field != 0 {
		e.FieldPrefix(&wrote, "sint32Field")
		e.Int32(x.Sint32Field)
	}
	if x.Sint64Field != 0 {
		e.FieldPrefix(&wrote, "sint64Field")
		e.Int64String(x.Sint64Field)
	}
	if x.Fixed32Field != 0 {
		e.FieldPrefix(&wrote, "fixed32Field")
		e.Uint32(x.Fixed32Field)
	}
	if x.Fixed64Field != 0 {
		e.FieldPrefix(&wrote, "fixed64Field")
		e.Uint64String(x.Fixed64Field)
	}
	if x.Sfixed32Field != 0 {
		e.FieldPrefix(&wrote, "sfixed32Field")
		e.Int32(x.Sfixed32Field)
	}
	if x.Sfixed64Field != 0 {
		e.FieldPrefix(&wrote, "sfixed64Field")
		e.Int64String(x.Sfixed64Field)
	}
	if x.BoolField {
		e.FieldPrefix(&wrote, "boolField")
		e.Bool(x.BoolField)
	}
	if x.StringField != "" {
		e.FieldPrefix(&wrote, "stringField")
		e.String(x.StringField)
	}
	if len(x.BytesField) > 0 {
		e.FieldPrefix(&wrote, "bytesField")
		e.BytesField(x.BytesField)
	}
	if x.EnumField != 0 {
		e.FieldPrefix(&wrote, "enumField")
		switch x.EnumField {
		case TestEnum_TEST_ENUM_UNSPECIFIED:
			e.String("TEST_ENUM_UNSPECIFIED")
		case TestEnum_TEST_ENUM_FIRST:
			e.String("TEST_ENUM_FIRST")
		case TestEnum_TEST_ENUM_SECOND:
			e.String("TEST_ENUM_SECOND")
		default:
			e.Int32(int32(x.EnumField))
		}
	}
	if x.TimestampField != nil {
		e.FieldPrefix(&wrote, "timestampField")
		if err := e.Timestamp(x.TimestampField.GetSeconds(), x.TimestampField.GetNanos()); err != nil {
			return err
		}
	}
	if x.DurationField != nil {
		e.FieldPrefix(&wrote, "durationField")
		if err := e.Duration(x.DurationField.GetSeconds(), x.DurationField.GetNanos()); err != nil {
			return err
		}
	}
	if x.ChildField != nil {
		e.FieldPrefix(&wrote, "childField")
		if err := x.ChildField.marshalProtoJSONXTo(e); err != nil {
			return err
		}
	}
	if len(x.RepeatedString) > 0 {
		e.FieldPrefix(&wrote, "repeatedString")
		e.Byte('[')
		for i, v := range x.RepeatedString {
			if i > 0 {
				e.Byte(',')
			}
			e.String(v)
		}
		e.Byte(']')
	}
	if len(x.RepeatedMessage) > 0 {
		e.FieldPrefix(&wrote, "repeatedMessage")
		e.Byte('[')
		for i, v := range x.RepeatedMessage {
			if i > 0 {
				e.Byte(',')
			}
			if v == nil {
				e.Raw("null")
			} else if err := v.marshalProtoJSONXTo(e); err != nil {
				return err
			}
		}
		e.Byte(']')
	}
	if len(x.MapStringString) > 0 {
		e.FieldPrefix(&wrote, "mapStringString")
		e.StringMap(x.MapStringString)
	}
	e.Byte('}')
	return nil
}

func (x *ComplexMessage) unmarshalProtoJSONXFast(d *protojsonxgen.Decoder) (bool, error) {
	if err := d.BeginObject(); err != nil {
		return false, err
	}
	fastFirst := true
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "doubleField")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.DoubleField = 0
		} else {
			v, err := d.ReadFloat64()
			if err != nil {
				return false, err
			}
			x.DoubleField = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "floatField")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.FloatField = 0
		} else {
			v, err := d.ReadFloat32()
			if err != nil {
				return false, err
			}
			x.FloatField = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "int32Field")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.Int32Field = 0
		} else {
			v, err := d.ReadInt32()
			if err != nil {
				return false, err
			}
			x.Int32Field = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "int64Field")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.Int64Field = 0
		} else {
			v, err := d.ReadInt64()
			if err != nil {
				return false, err
			}
			x.Int64Field = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "uint32Field")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.Uint32Field = 0
		} else {
			v, err := d.ReadUint32()
			if err != nil {
				return false, err
			}
			x.Uint32Field = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "uint64Field")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.Uint64Field = 0
		} else {
			v, err := d.ReadUint64()
			if err != nil {
				return false, err
			}
			x.Uint64Field = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "sint32Field")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.Sint32Field = 0
		} else {
			v, err := d.ReadInt32()
			if err != nil {
				return false, err
			}
			x.Sint32Field = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "sint64Field")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.Sint64Field = 0
		} else {
			v, err := d.ReadInt64()
			if err != nil {
				return false, err
			}
			x.Sint64Field = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "fixed32Field")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.Fixed32Field = 0
		} else {
			v, err := d.ReadUint32()
			if err != nil {
				return false, err
			}
			x.Fixed32Field = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "fixed64Field")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.Fixed64Field = 0
		} else {
			v, err := d.ReadUint64()
			if err != nil {
				return false, err
			}
			x.Fixed64Field = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "sfixed32Field")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.Sfixed32Field = 0
		} else {
			v, err := d.ReadInt32()
			if err != nil {
				return false, err
			}
			x.Sfixed32Field = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "sfixed64Field")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.Sfixed64Field = 0
		} else {
			v, err := d.ReadInt64()
			if err != nil {
				return false, err
			}
			x.Sfixed64Field = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "boolField")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.BoolField = false
		} else {
			v, err := d.ReadBool()
			if err != nil {
				return false, err
			}
			x.BoolField = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "stringField")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.StringField = ""
		} else {
			v, err := d.ReadString()
			if err != nil {
				return false, err
			}
			x.StringField = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "bytesField")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.BytesField = nil
		} else {
			v, err := d.ReadBytes()
			if err != nil {
				return false, err
			}
			x.BytesField = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "enumField")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.EnumField = 0
		} else {
			var v TestEnum
			if d.IsString() {
				s, err := d.ReadStringBytes()
				if err != nil {
					return false, err
				}
				if protojsonxgen.MatchStringBytes(s, "TEST_ENUM_UNSPECIFIED") {
					v = TestEnum_TEST_ENUM_UNSPECIFIED
				} else if protojsonxgen.MatchStringBytes(s, "TEST_ENUM_FIRST") {
					v = TestEnum_TEST_ENUM_FIRST
				} else if protojsonxgen.MatchStringBytes(s, "TEST_ENUM_SECOND") {
					v = TestEnum_TEST_ENUM_SECOND
				} else {
					return false, protojsonxgen.UnknownEnumValue(string(s))
				}
			} else {
				n, err := d.ReadInt32()
				if err != nil {
					return false, err
				}
				v = TestEnum(n)
			}
			x.EnumField = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "timestampField")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.TimestampField = nil
		} else {
			secs, nanos, err := d.ReadTimestamp()
			if err != nil {
				return false, err
			}
			x.TimestampField = &timestamppb.Timestamp{Seconds: secs, Nanos: nanos}
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "durationField")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.DurationField = nil
		} else {
			secs, nanos, err := d.ReadDuration()
			if err != nil {
				return false, err
			}
			x.DurationField = &durationpb.Duration{Seconds: secs, Nanos: nanos}
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "childField")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.ChildField = nil
		} else {
			x.ChildField = &ChildMessage{}
			if ok, err := x.ChildField.unmarshalProtoJSONXFast(d); err != nil {
				return false, err
			} else if !ok {
				return false, nil
			}
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "repeatedString")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.RepeatedString = nil
		} else {
			values := x.RepeatedString[:0]
			if values == nil {
				values = make([]string, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadString()
				if err != nil {
					return false, err
				}
				values = append(values, v)
			}
			x.RepeatedString = values
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "repeatedMessage")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.RepeatedMessage = nil
		} else {
			values := x.RepeatedMessage[:0]
			if values == nil {
				values = make([]*ChildMessage, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				if d.ReadNull() {
					return false, protojsonxgen.NullRepeatedMessage()
				}
				v := &ChildMessage{}
				if ok, err := v.unmarshalProtoJSONXFast(d); err != nil {
					return false, err
				} else if !ok {
					return false, nil
				}
				values = append(values, v)
			}
			x.RepeatedMessage = values
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "mapStringString")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.MapStringString = nil
		} else {
			m := make(map[string]string)
			if err := d.BeginObject(); err != nil {
				return false, err
			}
			mapFirst := true
			for {
				k, mapOK, err := d.NextObjectKey(&mapFirst)
				if err != nil {
					return false, err
				}
				if !mapOK {
					break
				}
				v, err := d.ReadString()
				if err != nil {
					return false, err
				}
				m[k] = v
			}
			x.MapStringString = m
		}
	}
	done, err := d.TryEndObject()
	if err != nil {
		return false, err
	}
	if !done {
		return false, nil
	}
	return true, nil
}

func (x *ComplexMessage) unmarshalProtoJSONXFrom(d *protojsonxgen.Decoder) error {
	if err := d.BeginObject(); err != nil {
		return err
	}
	var seen uint64
	first := true
	for {
		key, ok, err := d.NextObjectKey(&first)
		if err != nil {
			return err
		}
		if !ok {
			return nil
		}
		expected := 0
		switch expected {
		case 0:
			if key == "doubleField" {
				expected = 1
				const bit = uint64(1) << 0
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.DoubleField = 0
					return nil
				}
				v, err := d.ReadFloat64()
				if err != nil {
					return err
				}
				x.DoubleField = v
				continue
			}
		case 1:
			if key == "floatField" {
				expected = 2
				const bit = uint64(1) << 1
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.FloatField = 0
					return nil
				}
				v, err := d.ReadFloat32()
				if err != nil {
					return err
				}
				x.FloatField = v
				continue
			}
		case 2:
			if key == "int32Field" {
				expected = 3
				const bit = uint64(1) << 2
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.Int32Field = 0
					return nil
				}
				v, err := d.ReadInt32()
				if err != nil {
					return err
				}
				x.Int32Field = v
				continue
			}
		case 3:
			if key == "int64Field" {
				expected = 4
				const bit = uint64(1) << 3
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.Int64Field = 0
					return nil
				}
				v, err := d.ReadInt64()
				if err != nil {
					return err
				}
				x.Int64Field = v
				continue
			}
		case 4:
			if key == "uint32Field" {
				expected = 5
				const bit = uint64(1) << 4
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.Uint32Field = 0
					return nil
				}
				v, err := d.ReadUint32()
				if err != nil {
					return err
				}
				x.Uint32Field = v
				continue
			}
		case 5:
			if key == "uint64Field" {
				expected = 6
				const bit = uint64(1) << 5
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.Uint64Field = 0
					return nil
				}
				v, err := d.ReadUint64()
				if err != nil {
					return err
				}
				x.Uint64Field = v
				continue
			}
		case 6:
			if key == "sint32Field" {
				expected = 7
				const bit = uint64(1) << 6
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.Sint32Field = 0
					return nil
				}
				v, err := d.ReadInt32()
				if err != nil {
					return err
				}
				x.Sint32Field = v
				continue
			}
		case 7:
			if key == "sint64Field" {
				expected = 8
				const bit = uint64(1) << 7
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.Sint64Field = 0
					return nil
				}
				v, err := d.ReadInt64()
				if err != nil {
					return err
				}
				x.Sint64Field = v
				continue
			}
		case 8:
			if key == "fixed32Field" {
				expected = 9
				const bit = uint64(1) << 8
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.Fixed32Field = 0
					return nil
				}
				v, err := d.ReadUint32()
				if err != nil {
					return err
				}
				x.Fixed32Field = v
				continue
			}
		case 9:
			if key == "fixed64Field" {
				expected = 10
				const bit = uint64(1) << 9
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.Fixed64Field = 0
					return nil
				}
				v, err := d.ReadUint64()
				if err != nil {
					return err
				}
				x.Fixed64Field = v
				continue
			}
		case 10:
			if key == "sfixed32Field" {
				expected = 11
				const bit = uint64(1) << 10
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.Sfixed32Field = 0
					return nil
				}
				v, err := d.ReadInt32()
				if err != nil {
					return err
				}
				x.Sfixed32Field = v
				continue
			}
		case 11:
			if key == "sfixed64Field" {
				expected = 12
				const bit = uint64(1) << 11
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.Sfixed64Field = 0
					return nil
				}
				v, err := d.ReadInt64()
				if err != nil {
					return err
				}
				x.Sfixed64Field = v
				continue
			}
		case 12:
			if key == "boolField" {
				expected = 13
				const bit = uint64(1) << 12
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.BoolField = false
					return nil
				}
				v, err := d.ReadBool()
				if err != nil {
					return err
				}
				x.BoolField = v
				continue
			}
		case 13:
			if key == "stringField" {
				expected = 14
				const bit = uint64(1) << 13
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.StringField = ""
					return nil
				}
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				x.StringField = v
				continue
			}
		case 14:
			if key == "bytesField" {
				expected = 15
				const bit = uint64(1) << 14
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.BytesField = nil
					return nil
				}
				v, err := d.ReadBytes()
				if err != nil {
					return err
				}
				x.BytesField = v
				continue
			}
		case 15:
			if key == "enumField" {
				expected = 16
				const bit = uint64(1) << 15
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.EnumField = 0
					return nil
				}
				var v TestEnum
				if d.IsString() {
					s, err := d.ReadStringBytes()
					if err != nil {
						return err
					}
					if protojsonxgen.MatchStringBytes(s, "TEST_ENUM_UNSPECIFIED") {
						v = TestEnum_TEST_ENUM_UNSPECIFIED
					} else if protojsonxgen.MatchStringBytes(s, "TEST_ENUM_FIRST") {
						v = TestEnum_TEST_ENUM_FIRST
					} else if protojsonxgen.MatchStringBytes(s, "TEST_ENUM_SECOND") {
						v = TestEnum_TEST_ENUM_SECOND
					} else {
						return protojsonxgen.UnknownEnumValue(string(s))
					}
				} else {
					n, err := d.ReadInt32()
					if err != nil {
						return err
					}
					v = TestEnum(n)
				}
				x.EnumField = v
				continue
			}
		case 16:
			if key == "timestampField" {
				expected = 17
				const bit = uint64(1) << 16
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.TimestampField = nil
					return nil
				}
				secs, nanos, err := d.ReadTimestamp()
				if err != nil {
					return err
				}
				x.TimestampField = &timestamppb.Timestamp{Seconds: secs, Nanos: nanos}
				continue
			}
		case 17:
			if key == "durationField" {
				expected = 18
				const bit = uint64(1) << 17
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.DurationField = nil
					return nil
				}
				secs, nanos, err := d.ReadDuration()
				if err != nil {
					return err
				}
				x.DurationField = &durationpb.Duration{Seconds: secs, Nanos: nanos}
				continue
			}
		case 18:
			if key == "childField" {
				expected = 19
				const bit = uint64(1) << 18
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.ChildField = nil
					return nil
				}
				x.ChildField = &ChildMessage{}
				if err := x.ChildField.unmarshalProtoJSONXFrom(d); err != nil {
					return err
				}
				continue
			}
		case 19:
			if key == "repeatedString" {
				expected = 20
				const bit = uint64(1) << 19
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.RepeatedString = nil
					return nil
				}
				values := x.RepeatedString[:0]
				if values == nil {
					values = make([]string, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					v, err := d.ReadString()
					if err != nil {
						return err
					}
					values = append(values, v)
				}
				x.RepeatedString = values
				continue
			}
		case 20:
			if key == "repeatedMessage" {
				expected = 21
				const bit = uint64(1) << 20
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.RepeatedMessage = nil
					return nil
				}
				values := x.RepeatedMessage[:0]
				if values == nil {
					values = make([]*ChildMessage, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					if d.ReadNull() {
						return protojsonxgen.NullRepeatedMessage()
					}
					v := &ChildMessage{}
					if err := v.unmarshalProtoJSONXFrom(d); err != nil {
						return err
					}
					values = append(values, v)
				}
				x.RepeatedMessage = values
				continue
			}
		case 21:
			if key == "mapStringString" {
				expected = 22
				const bit = uint64(1) << 21
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.MapStringString = nil
					return nil
				}
				m := make(map[string]string)
				if err := d.BeginObject(); err != nil {
					return err
				}
				mapFirst := true
				for {
					k, mapOK, err := d.NextObjectKey(&mapFirst)
					if err != nil {
						return err
					}
					if !mapOK {
						break
					}
					v, err := d.ReadString()
					if err != nil {
						return err
					}
					m[k] = v
				}
				x.MapStringString = m
				continue
			}
		}
		switch key {
		case "doubleField", "double_field":
			const bit = uint64(1) << 0
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.DoubleField = 0
				return nil
			}
			v, err := d.ReadFloat64()
			if err != nil {
				return err
			}
			x.DoubleField = v
			continue
		case "floatField", "float_field":
			const bit = uint64(1) << 1
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.FloatField = 0
				return nil
			}
			v, err := d.ReadFloat32()
			if err != nil {
				return err
			}
			x.FloatField = v
			continue
		case "int32Field", "int32_field":
			const bit = uint64(1) << 2
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.Int32Field = 0
				return nil
			}
			v, err := d.ReadInt32()
			if err != nil {
				return err
			}
			x.Int32Field = v
			continue
		case "int64Field", "int64_field":
			const bit = uint64(1) << 3
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.Int64Field = 0
				return nil
			}
			v, err := d.ReadInt64()
			if err != nil {
				return err
			}
			x.Int64Field = v
			continue
		case "uint32Field", "uint32_field":
			const bit = uint64(1) << 4
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.Uint32Field = 0
				return nil
			}
			v, err := d.ReadUint32()
			if err != nil {
				return err
			}
			x.Uint32Field = v
			continue
		case "uint64Field", "uint64_field":
			const bit = uint64(1) << 5
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.Uint64Field = 0
				return nil
			}
			v, err := d.ReadUint64()
			if err != nil {
				return err
			}
			x.Uint64Field = v
			continue
		case "sint32Field", "sint32_field":
			const bit = uint64(1) << 6
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.Sint32Field = 0
				return nil
			}
			v, err := d.ReadInt32()
			if err != nil {
				return err
			}
			x.Sint32Field = v
			continue
		case "sint64Field", "sint64_field":
			const bit = uint64(1) << 7
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.Sint64Field = 0
				return nil
			}
			v, err := d.ReadInt64()
			if err != nil {
				return err
			}
			x.Sint64Field = v
			continue
		case "fixed32Field", "fixed32_field":
			const bit = uint64(1) << 8
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.Fixed32Field = 0
				return nil
			}
			v, err := d.ReadUint32()
			if err != nil {
				return err
			}
			x.Fixed32Field = v
			continue
		case "fixed64Field", "fixed64_field":
			const bit = uint64(1) << 9
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.Fixed64Field = 0
				return nil
			}
			v, err := d.ReadUint64()
			if err != nil {
				return err
			}
			x.Fixed64Field = v
			continue
		case "sfixed32Field", "sfixed32_field":
			const bit = uint64(1) << 10
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.Sfixed32Field = 0
				return nil
			}
			v, err := d.ReadInt32()
			if err != nil {
				return err
			}
			x.Sfixed32Field = v
			continue
		case "sfixed64Field", "sfixed64_field":
			const bit = uint64(1) << 11
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.Sfixed64Field = 0
				return nil
			}
			v, err := d.ReadInt64()
			if err != nil {
				return err
			}
			x.Sfixed64Field = v
			continue
		case "boolField", "bool_field":
			const bit = uint64(1) << 12
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.BoolField = false
				return nil
			}
			v, err := d.ReadBool()
			if err != nil {
				return err
			}
			x.BoolField = v
			continue
		case "stringField", "string_field":
			const bit = uint64(1) << 13
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.StringField = ""
				return nil
			}
			v, err := d.ReadString()
			if err != nil {
				return err
			}
			x.StringField = v
			continue
		case "bytesField", "bytes_field":
			const bit = uint64(1) << 14
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.BytesField = nil
				return nil
			}
			v, err := d.ReadBytes()
			if err != nil {
				return err
			}
			x.BytesField = v
			continue
		case "enumField", "enum_field":
			const bit = uint64(1) << 15
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.EnumField = 0
				return nil
			}
			var v TestEnum
			if d.IsString() {
				s, err := d.ReadStringBytes()
				if err != nil {
					return err
				}
				if protojsonxgen.MatchStringBytes(s, "TEST_ENUM_UNSPECIFIED") {
					v = TestEnum_TEST_ENUM_UNSPECIFIED
				} else if protojsonxgen.MatchStringBytes(s, "TEST_ENUM_FIRST") {
					v = TestEnum_TEST_ENUM_FIRST
				} else if protojsonxgen.MatchStringBytes(s, "TEST_ENUM_SECOND") {
					v = TestEnum_TEST_ENUM_SECOND
				} else {
					return protojsonxgen.UnknownEnumValue(string(s))
				}
			} else {
				n, err := d.ReadInt32()
				if err != nil {
					return err
				}
				v = TestEnum(n)
			}
			x.EnumField = v
			continue
		case "timestampField", "timestamp_field":
			const bit = uint64(1) << 16
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.TimestampField = nil
				return nil
			}
			secs, nanos, err := d.ReadTimestamp()
			if err != nil {
				return err
			}
			x.TimestampField = &timestamppb.Timestamp{Seconds: secs, Nanos: nanos}
			continue
		case "durationField", "duration_field":
			const bit = uint64(1) << 17
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.DurationField = nil
				return nil
			}
			secs, nanos, err := d.ReadDuration()
			if err != nil {
				return err
			}
			x.DurationField = &durationpb.Duration{Seconds: secs, Nanos: nanos}
			continue
		case "childField", "child_field":
			const bit = uint64(1) << 18
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.ChildField = nil
				return nil
			}
			x.ChildField = &ChildMessage{}
			if err := x.ChildField.unmarshalProtoJSONXFrom(d); err != nil {
				return err
			}
			continue
		case "repeatedString", "repeated_string":
			const bit = uint64(1) << 19
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.RepeatedString = nil
				return nil
			}
			values := x.RepeatedString[:0]
			if values == nil {
				values = make([]string, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				values = append(values, v)
			}
			x.RepeatedString = values
			continue
		case "repeatedMessage", "repeated_message":
			const bit = uint64(1) << 20
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.RepeatedMessage = nil
				return nil
			}
			values := x.RepeatedMessage[:0]
			if values == nil {
				values = make([]*ChildMessage, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return err
				}
				if !elemOK {
					break
				}
				if d.ReadNull() {
					return protojsonxgen.NullRepeatedMessage()
				}
				v := &ChildMessage{}
				if err := v.unmarshalProtoJSONXFrom(d); err != nil {
					return err
				}
				values = append(values, v)
			}
			x.RepeatedMessage = values
			continue
		case "mapStringString", "map_string_string":
			const bit = uint64(1) << 21
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.MapStringString = nil
				return nil
			}
			m := make(map[string]string)
			if err := d.BeginObject(); err != nil {
				return err
			}
			mapFirst := true
			for {
				k, mapOK, err := d.NextObjectKey(&mapFirst)
				if err != nil {
					return err
				}
				if !mapOK {
					break
				}
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				m[k] = v
			}
			x.MapStringString = m
			continue
		default:
			return protojsonxgen.UnknownField(key)
		}
	}
}

func (x *ChildMessage) MarshalProtoJSONX() ([]byte, error) {
	e := protojsonxgen.NewEncoder()
	if err := x.marshalProtoJSONXTo(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (x *ChildMessage) UnmarshalProtoJSONX(data []byte) error {
	d := protojsonxgen.NewDecoder(data)
	*x = ChildMessage{}
	firstKey, savedOff, savedDepth, _, peekErr := d.PeekObjectFieldName()
	if peekErr != nil {
		return peekErr
	}
	if firstKey == "name" || firstKey == "" {
		d.Reset(savedOff, savedDepth)
		if ok, err := x.unmarshalProtoJSONXFast(d); err != nil {
			return err
		} else if ok {
			return d.Finish()
		}
		*x = ChildMessage{}
	}
	d.Reset(savedOff, savedDepth)
	if err := x.unmarshalProtoJSONXFrom(d); err != nil {
		return err
	}
	return d.Finish()
}

func (x *ChildMessage) marshalProtoJSONXTo(e *protojsonxgen.Encoder) error {
	e.Byte('{')
	wrote := false
	if x.Name != "" {
		e.FieldPrefix(&wrote, "name")
		e.String(x.Name)
	}
	if x.Value != 0 {
		e.FieldPrefix(&wrote, "value")
		e.Int32(x.Value)
	}
	e.Byte('}')
	return nil
}

func (x *ChildMessage) unmarshalProtoJSONXFast(d *protojsonxgen.Decoder) (bool, error) {
	if err := d.BeginObject(); err != nil {
		return false, err
	}
	fastFirst := true
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "name")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.Name = ""
		} else {
			v, err := d.ReadString()
			if err != nil {
				return false, err
			}
			x.Name = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "value")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.Value = 0
		} else {
			v, err := d.ReadInt32()
			if err != nil {
				return false, err
			}
			x.Value = v
		}
	}
	done, err := d.TryEndObject()
	if err != nil {
		return false, err
	}
	if !done {
		return false, nil
	}
	return true, nil
}

func (x *ChildMessage) unmarshalProtoJSONXFrom(d *protojsonxgen.Decoder) error {
	if err := d.BeginObject(); err != nil {
		return err
	}
	var seen uint64
	first := true
	for {
		key, ok, err := d.NextObjectKey(&first)
		if err != nil {
			return err
		}
		if !ok {
			return nil
		}
		expected := 0
		switch expected {
		case 0:
			if key == "name" {
				expected = 1
				const bit = uint64(1) << 0
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.Name = ""
					return nil
				}
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				x.Name = v
				continue
			}
		case 1:
			if key == "value" {
				expected = 2
				const bit = uint64(1) << 1
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.Value = 0
					return nil
				}
				v, err := d.ReadInt32()
				if err != nil {
					return err
				}
				x.Value = v
				continue
			}
		}
		switch key {
		case "name":
			const bit = uint64(1) << 0
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.Name = ""
				return nil
			}
			v, err := d.ReadString()
			if err != nil {
				return err
			}
			x.Name = v
			continue
		case "value":
			const bit = uint64(1) << 1
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.Value = 0
				return nil
			}
			v, err := d.ReadInt32()
			if err != nil {
				return err
			}
			x.Value = v
			continue
		default:
			return protojsonxgen.UnknownField(key)
		}
	}
}

func (x *SpecMessage) MarshalProtoJSONX() ([]byte, error) {
	return protojsonxgen.Marshal(x)
}

func (x *SpecMessage) UnmarshalProtoJSONX(data []byte) error {
	return protojsonxgen.Unmarshal(data, x)
}

func (x *StructMessage) MarshalProtoJSONX() ([]byte, error) {
	return protojsonxgen.Marshal(x)
}

func (x *StructMessage) UnmarshalProtoJSONX(data []byte) error {
	return protojsonxgen.Unmarshal(data, x)
}

func (x *ValueMessage) MarshalProtoJSONX() ([]byte, error) {
	return protojsonxgen.Marshal(x)
}

func (x *ValueMessage) UnmarshalProtoJSONX(data []byte) error {
	return protojsonxgen.Unmarshal(data, x)
}

func (x *ListValueMessage) MarshalProtoJSONX() ([]byte, error) {
	return protojsonxgen.Marshal(x)
}

func (x *ListValueMessage) UnmarshalProtoJSONX(data []byte) error {
	return protojsonxgen.Unmarshal(data, x)
}

func (x *RepeatedScalarsMessage) MarshalProtoJSONX() ([]byte, error) {
	e := protojsonxgen.NewEncoder()
	if err := x.marshalProtoJSONXTo(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (x *RepeatedScalarsMessage) UnmarshalProtoJSONX(data []byte) error {
	d := protojsonxgen.NewDecoder(data)
	*x = RepeatedScalarsMessage{}
	firstKey, savedOff, savedDepth, _, peekErr := d.PeekObjectFieldName()
	if peekErr != nil {
		return peekErr
	}
	if firstKey == "repeatedInt32" || firstKey == "" {
		d.Reset(savedOff, savedDepth)
		if ok, err := x.unmarshalProtoJSONXFast(d); err != nil {
			return err
		} else if ok {
			return d.Finish()
		}
		*x = RepeatedScalarsMessage{}
	}
	d.Reset(savedOff, savedDepth)
	if err := x.unmarshalProtoJSONXFrom(d); err != nil {
		return err
	}
	return d.Finish()
}

func (x *RepeatedScalarsMessage) marshalProtoJSONXTo(e *protojsonxgen.Encoder) error {
	e.Byte('{')
	wrote := false
	if len(x.RepeatedInt32) > 0 {
		e.FieldPrefix(&wrote, "repeatedInt32")
		e.Byte('[')
		for i, v := range x.RepeatedInt32 {
			if i > 0 {
				e.Byte(',')
			}
			e.Int32(v)
		}
		e.Byte(']')
	}
	if len(x.RepeatedInt64) > 0 {
		e.FieldPrefix(&wrote, "repeatedInt64")
		e.Byte('[')
		for i, v := range x.RepeatedInt64 {
			if i > 0 {
				e.Byte(',')
			}
			e.Int64String(v)
		}
		e.Byte(']')
	}
	if len(x.RepeatedUint32) > 0 {
		e.FieldPrefix(&wrote, "repeatedUint32")
		e.Byte('[')
		for i, v := range x.RepeatedUint32 {
			if i > 0 {
				e.Byte(',')
			}
			e.Uint32(v)
		}
		e.Byte(']')
	}
	if len(x.RepeatedUint64) > 0 {
		e.FieldPrefix(&wrote, "repeatedUint64")
		e.Byte('[')
		for i, v := range x.RepeatedUint64 {
			if i > 0 {
				e.Byte(',')
			}
			e.Uint64String(v)
		}
		e.Byte(']')
	}
	if len(x.RepeatedFloat) > 0 {
		e.FieldPrefix(&wrote, "repeatedFloat")
		e.Byte('[')
		for i, v := range x.RepeatedFloat {
			if i > 0 {
				e.Byte(',')
			}
			e.Float32(v)
		}
		e.Byte(']')
	}
	if len(x.RepeatedDouble) > 0 {
		e.FieldPrefix(&wrote, "repeatedDouble")
		e.Byte('[')
		for i, v := range x.RepeatedDouble {
			if i > 0 {
				e.Byte(',')
			}
			e.Float64(v)
		}
		e.Byte(']')
	}
	if len(x.RepeatedBool) > 0 {
		e.FieldPrefix(&wrote, "repeatedBool")
		e.Byte('[')
		for i, v := range x.RepeatedBool {
			if i > 0 {
				e.Byte(',')
			}
			e.Bool(v)
		}
		e.Byte(']')
	}
	if len(x.RepeatedBytes) > 0 {
		e.FieldPrefix(&wrote, "repeatedBytes")
		e.Byte('[')
		for i, v := range x.RepeatedBytes {
			if i > 0 {
				e.Byte(',')
			}
			e.BytesField(v)
		}
		e.Byte(']')
	}
	if len(x.RepeatedEnum) > 0 {
		e.FieldPrefix(&wrote, "repeatedEnum")
		e.Byte('[')
		for i, v := range x.RepeatedEnum {
			if i > 0 {
				e.Byte(',')
			}
			switch v {
			case TestEnum_TEST_ENUM_UNSPECIFIED:
				e.String("TEST_ENUM_UNSPECIFIED")
			case TestEnum_TEST_ENUM_FIRST:
				e.String("TEST_ENUM_FIRST")
			case TestEnum_TEST_ENUM_SECOND:
				e.String("TEST_ENUM_SECOND")
			default:
				e.Int32(int32(v))
			}
		}
		e.Byte(']')
	}
	e.Byte('}')
	return nil
}

func (x *RepeatedScalarsMessage) unmarshalProtoJSONXFast(d *protojsonxgen.Decoder) (bool, error) {
	if err := d.BeginObject(); err != nil {
		return false, err
	}
	fastFirst := true
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "repeatedInt32")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.RepeatedInt32 = nil
		} else {
			values := x.RepeatedInt32[:0]
			if values == nil {
				values = make([]int32, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadInt32()
				if err != nil {
					return false, err
				}
				values = append(values, v)
			}
			x.RepeatedInt32 = values
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "repeatedInt64")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.RepeatedInt64 = nil
		} else {
			values := x.RepeatedInt64[:0]
			if values == nil {
				values = make([]int64, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadInt64()
				if err != nil {
					return false, err
				}
				values = append(values, v)
			}
			x.RepeatedInt64 = values
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "repeatedUint32")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.RepeatedUint32 = nil
		} else {
			values := x.RepeatedUint32[:0]
			if values == nil {
				values = make([]uint32, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadUint32()
				if err != nil {
					return false, err
				}
				values = append(values, v)
			}
			x.RepeatedUint32 = values
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "repeatedUint64")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.RepeatedUint64 = nil
		} else {
			values := x.RepeatedUint64[:0]
			if values == nil {
				values = make([]uint64, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadUint64()
				if err != nil {
					return false, err
				}
				values = append(values, v)
			}
			x.RepeatedUint64 = values
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "repeatedFloat")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.RepeatedFloat = nil
		} else {
			values := x.RepeatedFloat[:0]
			if values == nil {
				values = make([]float32, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadFloat32()
				if err != nil {
					return false, err
				}
				values = append(values, v)
			}
			x.RepeatedFloat = values
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "repeatedDouble")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.RepeatedDouble = nil
		} else {
			values := x.RepeatedDouble[:0]
			if values == nil {
				values = make([]float64, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadFloat64()
				if err != nil {
					return false, err
				}
				values = append(values, v)
			}
			x.RepeatedDouble = values
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "repeatedBool")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.RepeatedBool = nil
		} else {
			values := x.RepeatedBool[:0]
			if values == nil {
				values = make([]bool, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadBool()
				if err != nil {
					return false, err
				}
				values = append(values, v)
			}
			x.RepeatedBool = values
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "repeatedBytes")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.RepeatedBytes = nil
		} else {
			values := x.RepeatedBytes[:0]
			if values == nil {
				values = make([][]byte, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadBytes()
				if err != nil {
					return false, err
				}
				values = append(values, v)
			}
			x.RepeatedBytes = values
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "repeatedEnum")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.RepeatedEnum = nil
		} else {
			values := x.RepeatedEnum[:0]
			if values == nil {
				values = make([]TestEnum, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				var v TestEnum
				if d.IsString() {
					s, err := d.ReadStringBytes()
					if err != nil {
						return false, err
					}
					if protojsonxgen.MatchStringBytes(s, "TEST_ENUM_UNSPECIFIED") {
						v = TestEnum_TEST_ENUM_UNSPECIFIED
					} else if protojsonxgen.MatchStringBytes(s, "TEST_ENUM_FIRST") {
						v = TestEnum_TEST_ENUM_FIRST
					} else if protojsonxgen.MatchStringBytes(s, "TEST_ENUM_SECOND") {
						v = TestEnum_TEST_ENUM_SECOND
					} else {
						return false, protojsonxgen.UnknownEnumValue(string(s))
					}
				} else {
					n, err := d.ReadInt32()
					if err != nil {
						return false, err
					}
					v = TestEnum(n)
				}
				values = append(values, v)
			}
			x.RepeatedEnum = values
		}
	}
	done, err := d.TryEndObject()
	if err != nil {
		return false, err
	}
	if !done {
		return false, nil
	}
	return true, nil
}

func (x *RepeatedScalarsMessage) unmarshalProtoJSONXFrom(d *protojsonxgen.Decoder) error {
	if err := d.BeginObject(); err != nil {
		return err
	}
	var seen uint64
	first := true
	for {
		key, ok, err := d.NextObjectKey(&first)
		if err != nil {
			return err
		}
		if !ok {
			return nil
		}
		expected := 0
		switch expected {
		case 0:
			if key == "repeatedInt32" {
				expected = 1
				const bit = uint64(1) << 0
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.RepeatedInt32 = nil
					return nil
				}
				values := x.RepeatedInt32[:0]
				if values == nil {
					values = make([]int32, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					v, err := d.ReadInt32()
					if err != nil {
						return err
					}
					values = append(values, v)
				}
				x.RepeatedInt32 = values
				continue
			}
		case 1:
			if key == "repeatedInt64" {
				expected = 2
				const bit = uint64(1) << 1
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.RepeatedInt64 = nil
					return nil
				}
				values := x.RepeatedInt64[:0]
				if values == nil {
					values = make([]int64, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					v, err := d.ReadInt64()
					if err != nil {
						return err
					}
					values = append(values, v)
				}
				x.RepeatedInt64 = values
				continue
			}
		case 2:
			if key == "repeatedUint32" {
				expected = 3
				const bit = uint64(1) << 2
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.RepeatedUint32 = nil
					return nil
				}
				values := x.RepeatedUint32[:0]
				if values == nil {
					values = make([]uint32, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					v, err := d.ReadUint32()
					if err != nil {
						return err
					}
					values = append(values, v)
				}
				x.RepeatedUint32 = values
				continue
			}
		case 3:
			if key == "repeatedUint64" {
				expected = 4
				const bit = uint64(1) << 3
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.RepeatedUint64 = nil
					return nil
				}
				values := x.RepeatedUint64[:0]
				if values == nil {
					values = make([]uint64, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					v, err := d.ReadUint64()
					if err != nil {
						return err
					}
					values = append(values, v)
				}
				x.RepeatedUint64 = values
				continue
			}
		case 4:
			if key == "repeatedFloat" {
				expected = 5
				const bit = uint64(1) << 4
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.RepeatedFloat = nil
					return nil
				}
				values := x.RepeatedFloat[:0]
				if values == nil {
					values = make([]float32, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					v, err := d.ReadFloat32()
					if err != nil {
						return err
					}
					values = append(values, v)
				}
				x.RepeatedFloat = values
				continue
			}
		case 5:
			if key == "repeatedDouble" {
				expected = 6
				const bit = uint64(1) << 5
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.RepeatedDouble = nil
					return nil
				}
				values := x.RepeatedDouble[:0]
				if values == nil {
					values = make([]float64, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					v, err := d.ReadFloat64()
					if err != nil {
						return err
					}
					values = append(values, v)
				}
				x.RepeatedDouble = values
				continue
			}
		case 6:
			if key == "repeatedBool" {
				expected = 7
				const bit = uint64(1) << 6
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.RepeatedBool = nil
					return nil
				}
				values := x.RepeatedBool[:0]
				if values == nil {
					values = make([]bool, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					v, err := d.ReadBool()
					if err != nil {
						return err
					}
					values = append(values, v)
				}
				x.RepeatedBool = values
				continue
			}
		case 7:
			if key == "repeatedBytes" {
				expected = 8
				const bit = uint64(1) << 7
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.RepeatedBytes = nil
					return nil
				}
				values := x.RepeatedBytes[:0]
				if values == nil {
					values = make([][]byte, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					v, err := d.ReadBytes()
					if err != nil {
						return err
					}
					values = append(values, v)
				}
				x.RepeatedBytes = values
				continue
			}
		case 8:
			if key == "repeatedEnum" {
				expected = 9
				const bit = uint64(1) << 8
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.RepeatedEnum = nil
					return nil
				}
				values := x.RepeatedEnum[:0]
				if values == nil {
					values = make([]TestEnum, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					var v TestEnum
					if d.IsString() {
						s, err := d.ReadStringBytes()
						if err != nil {
							return err
						}
						if protojsonxgen.MatchStringBytes(s, "TEST_ENUM_UNSPECIFIED") {
							v = TestEnum_TEST_ENUM_UNSPECIFIED
						} else if protojsonxgen.MatchStringBytes(s, "TEST_ENUM_FIRST") {
							v = TestEnum_TEST_ENUM_FIRST
						} else if protojsonxgen.MatchStringBytes(s, "TEST_ENUM_SECOND") {
							v = TestEnum_TEST_ENUM_SECOND
						} else {
							return protojsonxgen.UnknownEnumValue(string(s))
						}
					} else {
						n, err := d.ReadInt32()
						if err != nil {
							return err
						}
						v = TestEnum(n)
					}
					values = append(values, v)
				}
				x.RepeatedEnum = values
				continue
			}
		}
		switch key {
		case "repeatedInt32", "repeated_int32":
			const bit = uint64(1) << 0
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.RepeatedInt32 = nil
				return nil
			}
			values := x.RepeatedInt32[:0]
			if values == nil {
				values = make([]int32, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadInt32()
				if err != nil {
					return err
				}
				values = append(values, v)
			}
			x.RepeatedInt32 = values
			continue
		case "repeatedInt64", "repeated_int64":
			const bit = uint64(1) << 1
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.RepeatedInt64 = nil
				return nil
			}
			values := x.RepeatedInt64[:0]
			if values == nil {
				values = make([]int64, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadInt64()
				if err != nil {
					return err
				}
				values = append(values, v)
			}
			x.RepeatedInt64 = values
			continue
		case "repeatedUint32", "repeated_uint32":
			const bit = uint64(1) << 2
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.RepeatedUint32 = nil
				return nil
			}
			values := x.RepeatedUint32[:0]
			if values == nil {
				values = make([]uint32, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadUint32()
				if err != nil {
					return err
				}
				values = append(values, v)
			}
			x.RepeatedUint32 = values
			continue
		case "repeatedUint64", "repeated_uint64":
			const bit = uint64(1) << 3
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.RepeatedUint64 = nil
				return nil
			}
			values := x.RepeatedUint64[:0]
			if values == nil {
				values = make([]uint64, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadUint64()
				if err != nil {
					return err
				}
				values = append(values, v)
			}
			x.RepeatedUint64 = values
			continue
		case "repeatedFloat", "repeated_float":
			const bit = uint64(1) << 4
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.RepeatedFloat = nil
				return nil
			}
			values := x.RepeatedFloat[:0]
			if values == nil {
				values = make([]float32, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadFloat32()
				if err != nil {
					return err
				}
				values = append(values, v)
			}
			x.RepeatedFloat = values
			continue
		case "repeatedDouble", "repeated_double":
			const bit = uint64(1) << 5
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.RepeatedDouble = nil
				return nil
			}
			values := x.RepeatedDouble[:0]
			if values == nil {
				values = make([]float64, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadFloat64()
				if err != nil {
					return err
				}
				values = append(values, v)
			}
			x.RepeatedDouble = values
			continue
		case "repeatedBool", "repeated_bool":
			const bit = uint64(1) << 6
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.RepeatedBool = nil
				return nil
			}
			values := x.RepeatedBool[:0]
			if values == nil {
				values = make([]bool, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadBool()
				if err != nil {
					return err
				}
				values = append(values, v)
			}
			x.RepeatedBool = values
			continue
		case "repeatedBytes", "repeated_bytes":
			const bit = uint64(1) << 7
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.RepeatedBytes = nil
				return nil
			}
			values := x.RepeatedBytes[:0]
			if values == nil {
				values = make([][]byte, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadBytes()
				if err != nil {
					return err
				}
				values = append(values, v)
			}
			x.RepeatedBytes = values
			continue
		case "repeatedEnum", "repeated_enum":
			const bit = uint64(1) << 8
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.RepeatedEnum = nil
				return nil
			}
			values := x.RepeatedEnum[:0]
			if values == nil {
				values = make([]TestEnum, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return err
				}
				if !elemOK {
					break
				}
				var v TestEnum
				if d.IsString() {
					s, err := d.ReadStringBytes()
					if err != nil {
						return err
					}
					if protojsonxgen.MatchStringBytes(s, "TEST_ENUM_UNSPECIFIED") {
						v = TestEnum_TEST_ENUM_UNSPECIFIED
					} else if protojsonxgen.MatchStringBytes(s, "TEST_ENUM_FIRST") {
						v = TestEnum_TEST_ENUM_FIRST
					} else if protojsonxgen.MatchStringBytes(s, "TEST_ENUM_SECOND") {
						v = TestEnum_TEST_ENUM_SECOND
					} else {
						return protojsonxgen.UnknownEnumValue(string(s))
					}
				} else {
					n, err := d.ReadInt32()
					if err != nil {
						return err
					}
					v = TestEnum(n)
				}
				values = append(values, v)
			}
			x.RepeatedEnum = values
			continue
		default:
			return protojsonxgen.UnknownField(key)
		}
	}
}

func (x *CompatibilityMessage) MarshalProtoJSONX() ([]byte, error) {
	return protojsonxgen.Marshal(x)
}

func (x *CompatibilityMessage) UnmarshalProtoJSONX(data []byte) error {
	return protojsonxgen.Unmarshal(data, x)
}
