// Code generated by protoc-gen-go-protojsonx. DO NOT EDIT.
// versions:
// 	protoc-gen-go-protojsonx v0.1.0
// source: user.proto

package testpb

import (
	protojsonxgen "github.com/sudorandom/protojsonx/protojsonxgen"
)

// This file is a placeholder for schema-specific protojsonx code.
// The generator is wired through protogen.Options so it follows the same
// module= and import-path behavior as protoc-gen-go.
const _ = "protojsonx generated scaffold 0.1.0"

func (x *UserProfile) MarshalProtoJSONX() ([]byte, error) {
	e := protojsonxgen.NewEncoder()
	if err := x.marshalProtoJSONXTo(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (x *UserProfile) UnmarshalProtoJSONX(data []byte) error {
	d := protojsonxgen.NewDecoder(data)
	*x = UserProfile{}
	firstKey, savedOff, savedDepth, _, peekErr := d.PeekObjectFieldName()
	if peekErr != nil {
		return peekErr
	}
	if firstKey == "id" || firstKey == "" {
		d.Reset(savedOff, savedDepth)
		if ok, err := x.unmarshalProtoJSONXFast(d); err != nil {
			return err
		} else if ok {
			return d.Finish()
		}
		*x = UserProfile{}
	}
	d.Reset(savedOff, savedDepth)
	if err := x.unmarshalProtoJSONXFrom(d); err != nil {
		return err
	}
	return d.Finish()
}

func (x *UserProfile) marshalProtoJSONXTo(e *protojsonxgen.Encoder) error {
	e.Byte('{')
	wrote := false
	if x.Id != "" {
		e.FieldPrefix(&wrote, "id")
		e.String(x.Id)
	}
	if x.Email != "" {
		e.FieldPrefix(&wrote, "email")
		e.String(x.Email)
	}
	if x.Name != "" {
		e.FieldPrefix(&wrote, "name")
		e.String(x.Name)
	}
	if x.Age != 0 {
		e.FieldPrefix(&wrote, "age")
		e.Int32(x.Age)
	}
	if x.IsActive {
		e.FieldPrefix(&wrote, "isActive")
		e.Bool(x.IsActive)
	}
	if x.Status != 0 {
		e.FieldPrefix(&wrote, "status")
		switch x.Status {
		case UserStatus_STATUS_UNSPECIFIED:
			e.String("STATUS_UNSPECIFIED")
		case UserStatus_STATUS_ACTIVE:
			e.String("STATUS_ACTIVE")
		case UserStatus_STATUS_INACTIVE:
			e.String("STATUS_INACTIVE")
		case UserStatus_STATUS_SUSPENDED:
			e.String("STATUS_SUSPENDED")
		default:
			e.Int32(int32(x.Status))
		}
	}
	if len(x.Tags) > 0 {
		e.FieldPrefix(&wrote, "tags")
		e.Byte('[')
		for i, v := range x.Tags {
			if i > 0 {
				e.Byte(',')
			}
			e.String(v)
		}
		e.Byte(']')
	}
	if len(x.Metadata) > 0 {
		e.FieldPrefix(&wrote, "metadata")
		e.StringMap(x.Metadata)
	}
	if x.Address != nil {
		e.FieldPrefix(&wrote, "address")
		if err := x.Address.marshalProtoJSONXTo(e); err != nil {
			return err
		}
	}
	if len(x.Sessions) > 0 {
		e.FieldPrefix(&wrote, "sessions")
		e.Byte('[')
		for i, v := range x.Sessions {
			if i > 0 {
				e.Byte(',')
			}
			if v == nil {
				e.Raw("null")
			} else if err := v.marshalProtoJSONXTo(e); err != nil {
				return err
			}
		}
		e.Byte(']')
	}
	e.Byte('}')
	return nil
}

func (x *UserProfile) unmarshalProtoJSONXFast(d *protojsonxgen.Decoder) (bool, error) {
	if err := d.BeginObject(); err != nil {
		return false, err
	}
	fastFirst := true
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "id")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.Id = ""
		} else {
			v, err := d.ReadString()
			if err != nil {
				return false, err
			}
			x.Id = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "email")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.Email = ""
		} else {
			v, err := d.ReadString()
			if err != nil {
				return false, err
			}
			x.Email = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "name")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.Name = ""
		} else {
			v, err := d.ReadString()
			if err != nil {
				return false, err
			}
			x.Name = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "age")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.Age = 0
		} else {
			v, err := d.ReadInt32()
			if err != nil {
				return false, err
			}
			x.Age = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "isActive")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.IsActive = false
		} else {
			v, err := d.ReadBool()
			if err != nil {
				return false, err
			}
			x.IsActive = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "status")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.Status = 0
		} else {
			var v UserStatus
			if d.IsString() {
				s, err := d.ReadStringBytes()
				if err != nil {
					return false, err
				}
				if protojsonxgen.MatchStringBytes(s, "STATUS_UNSPECIFIED") {
					v = UserStatus_STATUS_UNSPECIFIED
				} else if protojsonxgen.MatchStringBytes(s, "STATUS_ACTIVE") {
					v = UserStatus_STATUS_ACTIVE
				} else if protojsonxgen.MatchStringBytes(s, "STATUS_INACTIVE") {
					v = UserStatus_STATUS_INACTIVE
				} else if protojsonxgen.MatchStringBytes(s, "STATUS_SUSPENDED") {
					v = UserStatus_STATUS_SUSPENDED
				} else {
					return false, protojsonxgen.UnknownEnumValue(string(s))
				}
			} else {
				n, err := d.ReadInt32()
				if err != nil {
					return false, err
				}
				v = UserStatus(n)
			}
			x.Status = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "tags")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.Tags = nil
		} else {
			values := x.Tags[:0]
			if values == nil {
				values = make([]string, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadString()
				if err != nil {
					return false, err
				}
				values = append(values, v)
			}
			x.Tags = values
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "metadata")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.Metadata = nil
		} else {
			m := make(map[string]string)
			if err := d.BeginObject(); err != nil {
				return false, err
			}
			mapFirst := true
			for {
				k, mapOK, err := d.NextObjectKey(&mapFirst)
				if err != nil {
					return false, err
				}
				if !mapOK {
					break
				}
				v, err := d.ReadString()
				if err != nil {
					return false, err
				}
				m[k] = v
			}
			x.Metadata = m
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "address")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.Address = nil
		} else {
			x.Address = &Address{}
			if ok, err := x.Address.unmarshalProtoJSONXFast(d); err != nil {
				return false, err
			} else if !ok {
				return false, nil
			}
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "sessions")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.Sessions = nil
		} else {
			values := x.Sessions[:0]
			if values == nil {
				values = make([]*Session, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				if d.ReadNull() {
					return false, protojsonxgen.NullRepeatedMessage()
				}
				v := &Session{}
				if ok, err := v.unmarshalProtoJSONXFast(d); err != nil {
					return false, err
				} else if !ok {
					return false, nil
				}
				values = append(values, v)
			}
			x.Sessions = values
		}
	}
	done, err := d.TryEndObject()
	if err != nil {
		return false, err
	}
	if !done {
		return false, nil
	}
	return true, nil
}

func (x *UserProfile) unmarshalProtoJSONXFrom(d *protojsonxgen.Decoder) error {
	if err := d.BeginObject(); err != nil {
		return err
	}
	var seen uint64
	first := true
	for {
		key, ok, err := d.NextObjectKey(&first)
		if err != nil {
			return err
		}
		if !ok {
			return nil
		}
		expected := 0
		switch expected {
		case 0:
			if key == "id" {
				expected = 1
				const bit = uint64(1) << 0
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.Id = ""
					return nil
				}
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				x.Id = v
				continue
			}
		case 1:
			if key == "email" {
				expected = 2
				const bit = uint64(1) << 1
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.Email = ""
					return nil
				}
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				x.Email = v
				continue
			}
		case 2:
			if key == "name" {
				expected = 3
				const bit = uint64(1) << 2
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.Name = ""
					return nil
				}
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				x.Name = v
				continue
			}
		case 3:
			if key == "age" {
				expected = 4
				const bit = uint64(1) << 3
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.Age = 0
					return nil
				}
				v, err := d.ReadInt32()
				if err != nil {
					return err
				}
				x.Age = v
				continue
			}
		case 4:
			if key == "isActive" {
				expected = 5
				const bit = uint64(1) << 4
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.IsActive = false
					return nil
				}
				v, err := d.ReadBool()
				if err != nil {
					return err
				}
				x.IsActive = v
				continue
			}
		case 5:
			if key == "status" {
				expected = 6
				const bit = uint64(1) << 5
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.Status = 0
					return nil
				}
				var v UserStatus
				if d.IsString() {
					s, err := d.ReadStringBytes()
					if err != nil {
						return err
					}
					if protojsonxgen.MatchStringBytes(s, "STATUS_UNSPECIFIED") {
						v = UserStatus_STATUS_UNSPECIFIED
					} else if protojsonxgen.MatchStringBytes(s, "STATUS_ACTIVE") {
						v = UserStatus_STATUS_ACTIVE
					} else if protojsonxgen.MatchStringBytes(s, "STATUS_INACTIVE") {
						v = UserStatus_STATUS_INACTIVE
					} else if protojsonxgen.MatchStringBytes(s, "STATUS_SUSPENDED") {
						v = UserStatus_STATUS_SUSPENDED
					} else {
						return protojsonxgen.UnknownEnumValue(string(s))
					}
				} else {
					n, err := d.ReadInt32()
					if err != nil {
						return err
					}
					v = UserStatus(n)
				}
				x.Status = v
				continue
			}
		case 6:
			if key == "tags" {
				expected = 7
				const bit = uint64(1) << 6
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.Tags = nil
					return nil
				}
				values := x.Tags[:0]
				if values == nil {
					values = make([]string, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					v, err := d.ReadString()
					if err != nil {
						return err
					}
					values = append(values, v)
				}
				x.Tags = values
				continue
			}
		case 7:
			if key == "metadata" {
				expected = 8
				const bit = uint64(1) << 7
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.Metadata = nil
					return nil
				}
				m := make(map[string]string)
				if err := d.BeginObject(); err != nil {
					return err
				}
				mapFirst := true
				for {
					k, mapOK, err := d.NextObjectKey(&mapFirst)
					if err != nil {
						return err
					}
					if !mapOK {
						break
					}
					v, err := d.ReadString()
					if err != nil {
						return err
					}
					m[k] = v
				}
				x.Metadata = m
				continue
			}
		case 8:
			if key == "address" {
				expected = 9
				const bit = uint64(1) << 8
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.Address = nil
					return nil
				}
				x.Address = &Address{}
				if err := x.Address.unmarshalProtoJSONXFrom(d); err != nil {
					return err
				}
				continue
			}
		case 9:
			if key == "sessions" {
				expected = 10
				const bit = uint64(1) << 9
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.Sessions = nil
					return nil
				}
				values := x.Sessions[:0]
				if values == nil {
					values = make([]*Session, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					if d.ReadNull() {
						return protojsonxgen.NullRepeatedMessage()
					}
					v := &Session{}
					if err := v.unmarshalProtoJSONXFrom(d); err != nil {
						return err
					}
					values = append(values, v)
				}
				x.Sessions = values
				continue
			}
		}
		switch key {
		case "id":
			const bit = uint64(1) << 0
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.Id = ""
				return nil
			}
			v, err := d.ReadString()
			if err != nil {
				return err
			}
			x.Id = v
			continue
		case "email":
			const bit = uint64(1) << 1
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.Email = ""
				return nil
			}
			v, err := d.ReadString()
			if err != nil {
				return err
			}
			x.Email = v
			continue
		case "name":
			const bit = uint64(1) << 2
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.Name = ""
				return nil
			}
			v, err := d.ReadString()
			if err != nil {
				return err
			}
			x.Name = v
			continue
		case "age":
			const bit = uint64(1) << 3
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.Age = 0
				return nil
			}
			v, err := d.ReadInt32()
			if err != nil {
				return err
			}
			x.Age = v
			continue
		case "isActive", "is_active":
			const bit = uint64(1) << 4
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.IsActive = false
				return nil
			}
			v, err := d.ReadBool()
			if err != nil {
				return err
			}
			x.IsActive = v
			continue
		case "status":
			const bit = uint64(1) << 5
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.Status = 0
				return nil
			}
			var v UserStatus
			if d.IsString() {
				s, err := d.ReadStringBytes()
				if err != nil {
					return err
				}
				if protojsonxgen.MatchStringBytes(s, "STATUS_UNSPECIFIED") {
					v = UserStatus_STATUS_UNSPECIFIED
				} else if protojsonxgen.MatchStringBytes(s, "STATUS_ACTIVE") {
					v = UserStatus_STATUS_ACTIVE
				} else if protojsonxgen.MatchStringBytes(s, "STATUS_INACTIVE") {
					v = UserStatus_STATUS_INACTIVE
				} else if protojsonxgen.MatchStringBytes(s, "STATUS_SUSPENDED") {
					v = UserStatus_STATUS_SUSPENDED
				} else {
					return protojsonxgen.UnknownEnumValue(string(s))
				}
			} else {
				n, err := d.ReadInt32()
				if err != nil {
					return err
				}
				v = UserStatus(n)
			}
			x.Status = v
			continue
		case "tags":
			const bit = uint64(1) << 6
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.Tags = nil
				return nil
			}
			values := x.Tags[:0]
			if values == nil {
				values = make([]string, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				values = append(values, v)
			}
			x.Tags = values
			continue
		case "metadata":
			const bit = uint64(1) << 7
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.Metadata = nil
				return nil
			}
			m := make(map[string]string)
			if err := d.BeginObject(); err != nil {
				return err
			}
			mapFirst := true
			for {
				k, mapOK, err := d.NextObjectKey(&mapFirst)
				if err != nil {
					return err
				}
				if !mapOK {
					break
				}
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				m[k] = v
			}
			x.Metadata = m
			continue
		case "address":
			const bit = uint64(1) << 8
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.Address = nil
				return nil
			}
			x.Address = &Address{}
			if err := x.Address.unmarshalProtoJSONXFrom(d); err != nil {
				return err
			}
			continue
		case "sessions":
			const bit = uint64(1) << 9
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.Sessions = nil
				return nil
			}
			values := x.Sessions[:0]
			if values == nil {
				values = make([]*Session, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return err
				}
				if !elemOK {
					break
				}
				if d.ReadNull() {
					return protojsonxgen.NullRepeatedMessage()
				}
				v := &Session{}
				if err := v.unmarshalProtoJSONXFrom(d); err != nil {
					return err
				}
				values = append(values, v)
			}
			x.Sessions = values
			continue
		default:
			return protojsonxgen.UnknownField(key)
		}
	}
}

func (x *Address) MarshalProtoJSONX() ([]byte, error) {
	e := protojsonxgen.NewEncoder()
	if err := x.marshalProtoJSONXTo(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (x *Address) UnmarshalProtoJSONX(data []byte) error {
	d := protojsonxgen.NewDecoder(data)
	*x = Address{}
	firstKey, savedOff, savedDepth, _, peekErr := d.PeekObjectFieldName()
	if peekErr != nil {
		return peekErr
	}
	if firstKey == "street" || firstKey == "" {
		d.Reset(savedOff, savedDepth)
		if ok, err := x.unmarshalProtoJSONXFast(d); err != nil {
			return err
		} else if ok {
			return d.Finish()
		}
		*x = Address{}
	}
	d.Reset(savedOff, savedDepth)
	if err := x.unmarshalProtoJSONXFrom(d); err != nil {
		return err
	}
	return d.Finish()
}

func (x *Address) marshalProtoJSONXTo(e *protojsonxgen.Encoder) error {
	e.Byte('{')
	wrote := false
	if x.Street != "" {
		e.FieldPrefix(&wrote, "street")
		e.String(x.Street)
	}
	if x.City != "" {
		e.FieldPrefix(&wrote, "city")
		e.String(x.City)
	}
	if x.State != "" {
		e.FieldPrefix(&wrote, "state")
		e.String(x.State)
	}
	if x.Zip != "" {
		e.FieldPrefix(&wrote, "zip")
		e.String(x.Zip)
	}
	if x.Country != "" {
		e.FieldPrefix(&wrote, "country")
		e.String(x.Country)
	}
	e.Byte('}')
	return nil
}

func (x *Address) unmarshalProtoJSONXFast(d *protojsonxgen.Decoder) (bool, error) {
	if err := d.BeginObject(); err != nil {
		return false, err
	}
	fastFirst := true
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "street")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.Street = ""
		} else {
			v, err := d.ReadString()
			if err != nil {
				return false, err
			}
			x.Street = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "city")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.City = ""
		} else {
			v, err := d.ReadString()
			if err != nil {
				return false, err
			}
			x.City = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "state")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.State = ""
		} else {
			v, err := d.ReadString()
			if err != nil {
				return false, err
			}
			x.State = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "zip")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.Zip = ""
		} else {
			v, err := d.ReadString()
			if err != nil {
				return false, err
			}
			x.Zip = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "country")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.Country = ""
		} else {
			v, err := d.ReadString()
			if err != nil {
				return false, err
			}
			x.Country = v
		}
	}
	done, err := d.TryEndObject()
	if err != nil {
		return false, err
	}
	if !done {
		return false, nil
	}
	return true, nil
}

func (x *Address) unmarshalProtoJSONXFrom(d *protojsonxgen.Decoder) error {
	if err := d.BeginObject(); err != nil {
		return err
	}
	var seen uint64
	first := true
	for {
		key, ok, err := d.NextObjectKey(&first)
		if err != nil {
			return err
		}
		if !ok {
			return nil
		}
		expected := 0
		switch expected {
		case 0:
			if key == "street" {
				expected = 1
				const bit = uint64(1) << 0
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.Street = ""
					return nil
				}
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				x.Street = v
				continue
			}
		case 1:
			if key == "city" {
				expected = 2
				const bit = uint64(1) << 1
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.City = ""
					return nil
				}
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				x.City = v
				continue
			}
		case 2:
			if key == "state" {
				expected = 3
				const bit = uint64(1) << 2
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.State = ""
					return nil
				}
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				x.State = v
				continue
			}
		case 3:
			if key == "zip" {
				expected = 4
				const bit = uint64(1) << 3
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.Zip = ""
					return nil
				}
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				x.Zip = v
				continue
			}
		case 4:
			if key == "country" {
				expected = 5
				const bit = uint64(1) << 4
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.Country = ""
					return nil
				}
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				x.Country = v
				continue
			}
		}
		switch key {
		case "street":
			const bit = uint64(1) << 0
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.Street = ""
				return nil
			}
			v, err := d.ReadString()
			if err != nil {
				return err
			}
			x.Street = v
			continue
		case "city":
			const bit = uint64(1) << 1
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.City = ""
				return nil
			}
			v, err := d.ReadString()
			if err != nil {
				return err
			}
			x.City = v
			continue
		case "state":
			const bit = uint64(1) << 2
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.State = ""
				return nil
			}
			v, err := d.ReadString()
			if err != nil {
				return err
			}
			x.State = v
			continue
		case "zip":
			const bit = uint64(1) << 3
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.Zip = ""
				return nil
			}
			v, err := d.ReadString()
			if err != nil {
				return err
			}
			x.Zip = v
			continue
		case "country":
			const bit = uint64(1) << 4
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.Country = ""
				return nil
			}
			v, err := d.ReadString()
			if err != nil {
				return err
			}
			x.Country = v
			continue
		default:
			return protojsonxgen.UnknownField(key)
		}
	}
}

func (x *Session) MarshalProtoJSONX() ([]byte, error) {
	e := protojsonxgen.NewEncoder()
	if err := x.marshalProtoJSONXTo(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (x *Session) UnmarshalProtoJSONX(data []byte) error {
	d := protojsonxgen.NewDecoder(data)
	*x = Session{}
	firstKey, savedOff, savedDepth, _, peekErr := d.PeekObjectFieldName()
	if peekErr != nil {
		return peekErr
	}
	if firstKey == "sessionId" || firstKey == "" {
		d.Reset(savedOff, savedDepth)
		if ok, err := x.unmarshalProtoJSONXFast(d); err != nil {
			return err
		} else if ok {
			return d.Finish()
		}
		*x = Session{}
	}
	d.Reset(savedOff, savedDepth)
	if err := x.unmarshalProtoJSONXFrom(d); err != nil {
		return err
	}
	return d.Finish()
}

func (x *Session) marshalProtoJSONXTo(e *protojsonxgen.Encoder) error {
	e.Byte('{')
	wrote := false
	if x.SessionId != "" {
		e.FieldPrefix(&wrote, "sessionId")
		e.String(x.SessionId)
	}
	if x.LoginTimestamp != 0 {
		e.FieldPrefix(&wrote, "loginTimestamp")
		e.Int64String(x.LoginTimestamp)
	}
	if x.IpAddress != "" {
		e.FieldPrefix(&wrote, "ipAddress")
		e.String(x.IpAddress)
	}
	e.Byte('}')
	return nil
}

func (x *Session) unmarshalProtoJSONXFast(d *protojsonxgen.Decoder) (bool, error) {
	if err := d.BeginObject(); err != nil {
		return false, err
	}
	fastFirst := true
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "sessionId")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.SessionId = ""
		} else {
			v, err := d.ReadString()
			if err != nil {
				return false, err
			}
			x.SessionId = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "loginTimestamp")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.LoginTimestamp = 0
		} else {
			v, err := d.ReadInt64()
			if err != nil {
				return false, err
			}
			x.LoginTimestamp = v
		}
	}
	{
		matched, done, err := d.TryObjectFieldFast(&fastFirst, "ipAddress")
		if err != nil {
			return false, err
		}
		if done {
			return true, nil
		}
		if !matched {
			return false, nil
		}
		if d.ReadNull() {
			x.IpAddress = ""
		} else {
			v, err := d.ReadString()
			if err != nil {
				return false, err
			}
			x.IpAddress = v
		}
	}
	done, err := d.TryEndObject()
	if err != nil {
		return false, err
	}
	if !done {
		return false, nil
	}
	return true, nil
}

func (x *Session) unmarshalProtoJSONXFrom(d *protojsonxgen.Decoder) error {
	if err := d.BeginObject(); err != nil {
		return err
	}
	var seen uint64
	first := true
	for {
		key, ok, err := d.NextObjectKey(&first)
		if err != nil {
			return err
		}
		if !ok {
			return nil
		}
		expected := 0
		switch expected {
		case 0:
			if key == "sessionId" {
				expected = 1
				const bit = uint64(1) << 0
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.SessionId = ""
					return nil
				}
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				x.SessionId = v
				continue
			}
		case 1:
			if key == "loginTimestamp" {
				expected = 2
				const bit = uint64(1) << 1
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.LoginTimestamp = 0
					return nil
				}
				v, err := d.ReadInt64()
				if err != nil {
					return err
				}
				x.LoginTimestamp = v
				continue
			}
		case 2:
			if key == "ipAddress" {
				expected = 3
				const bit = uint64(1) << 2
				if seen&bit != 0 {
					return protojsonxgen.DuplicateField(key)
				}
				seen |= bit
				if d.ReadNull() {
					x.IpAddress = ""
					return nil
				}
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				x.IpAddress = v
				continue
			}
		}
		switch key {
		case "sessionId", "session_id":
			const bit = uint64(1) << 0
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.SessionId = ""
				return nil
			}
			v, err := d.ReadString()
			if err != nil {
				return err
			}
			x.SessionId = v
			continue
		case "loginTimestamp", "login_timestamp":
			const bit = uint64(1) << 1
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.LoginTimestamp = 0
				return nil
			}
			v, err := d.ReadInt64()
			if err != nil {
				return err
			}
			x.LoginTimestamp = v
			continue
		case "ipAddress", "ip_address":
			const bit = uint64(1) << 2
			if seen&bit != 0 {
				return protojsonxgen.DuplicateField(key)
			}
			seen |= bit
			if d.ReadNull() {
				x.IpAddress = ""
				return nil
			}
			v, err := d.ReadString()
			if err != nil {
				return err
			}
			x.IpAddress = v
			continue
		default:
			return protojsonxgen.UnknownField(key)
		}
	}
}
