// Code generated by protoc-gen-go-protojsonx. DO NOT EDIT.
// versions:
// 	protoc-gen-go-protojsonx v0.1.0
// source: user.proto

package testpb

import (
	protojsonxgen "github.com/sudorandom/protojsonx/protojsonxgen"
)

// This file is a placeholder for schema-specific protojsonx code.
// The generator is wired through protogen.Options so it follows the same
// module= and import-path behavior as protoc-gen-go.
const _ = "protojsonx generated scaffold 0.1.0"

func (x *UserProfile) ProtoJSONXFastPath() {}

func (x *UserProfile) MarshalProtoJSONX() ([]byte, error) {
	e := protojsonxgen.NewEncoder()
	if err := x.marshalProtoJSONXTo(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (x *UserProfile) UnmarshalProtoJSONX(data []byte) error {
	return x.UnmarshalProtoJSONXWithOptions(data, false)
}

func (x *UserProfile) UnmarshalProtoJSONXWithOptions(data []byte, discardUnknown bool) error {
	d := protojsonxgen.NewDecoder(data)
	*x = UserProfile{}
	firstKey, savedOff, savedDepth, _, peekErr := d.PeekObjectFieldName()
	if peekErr != nil {
		return peekErr
	}
	if firstKey == "id" || firstKey == "" {
		d.Reset(savedOff, savedDepth)
		if ok, err := x.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
			return err
		} else if ok {
			return d.Finish()
		}
		*x = UserProfile{}
	}
	d.Reset(savedOff, savedDepth)
	if err := x.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
		return err
	}
	return d.Finish()
}

func (x *UserProfile) marshalProtoJSONXTo(e *protojsonxgen.Encoder) error {
	e.Byte('{')
	wrote := false
	if x.Id != "" {
		e.FieldPrefix(&wrote, "id")
		e.String(x.Id)
	}
	if x.Email != "" {
		e.FieldPrefix(&wrote, "email")
		e.String(x.Email)
	}
	if x.Name != "" {
		e.FieldPrefix(&wrote, "name")
		e.String(x.Name)
	}
	if x.Age != 0 {
		e.FieldPrefix(&wrote, "age")
		e.Int32(x.Age)
	}
	if x.IsActive {
		e.FieldPrefix(&wrote, "isActive")
		e.Bool(x.IsActive)
	}
	if x.Status != 0 {
		e.FieldPrefix(&wrote, "status")
		switch x.Status {
		case UserStatus_STATUS_UNSPECIFIED:
			e.String("STATUS_UNSPECIFIED")
		case UserStatus_STATUS_ACTIVE:
			e.String("STATUS_ACTIVE")
		case UserStatus_STATUS_INACTIVE:
			e.String("STATUS_INACTIVE")
		case UserStatus_STATUS_SUSPENDED:
			e.String("STATUS_SUSPENDED")
		default:
			e.Int32(int32(x.Status))
		}
	}
	if len(x.Tags) > 0 {
		e.FieldPrefix(&wrote, "tags")
		e.Byte('[')
		for i, v := range x.Tags {
			if i > 0 {
				e.Byte(',')
			}
			e.String(v)
		}
		e.Byte(']')
	}
	if len(x.Metadata) > 0 {
		e.FieldPrefix(&wrote, "metadata")
		e.StringMap(x.Metadata)
	}
	if x.Address != nil {
		e.FieldPrefix(&wrote, "address")
		if fast, ok := any(x.Address).(interface {
			marshalProtoJSONXTo(*protojsonxgen.Encoder) error
		}); ok {
			if err := fast.marshalProtoJSONXTo(e); err != nil {
				return err
			}
		} else {
			if err := protojsonxgen.MarshalField(e, x.Address); err != nil {
				return err
			}
		}
	}
	if len(x.Sessions) > 0 {
		e.FieldPrefix(&wrote, "sessions")
		e.Byte('[')
		for i, v := range x.Sessions {
			if i > 0 {
				e.Byte(',')
			}
			if v == nil {
				e.Raw("null")
			} else {
				if fast, ok := any(v).(interface {
					marshalProtoJSONXTo(*protojsonxgen.Encoder) error
				}); ok {
					if err := fast.marshalProtoJSONXTo(e); err != nil {
						return err
					}
				} else {
					if err := protojsonxgen.MarshalField(e, v); err != nil {
						return err
					}
				}
			}
		}
		e.Byte(']')
	}
	e.Byte('}')
	return nil
}

func (x *UserProfile) unmarshalProtoJSONXFast(d *protojsonxgen.Decoder, discardUnknown bool) (bool, error) {
	if err := d.BeginObject(); err != nil {
		return false, err
	}
	fastFirst := true
	{
		status, err := d.MatchFast(&fastFirst, "id")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Id = ""
		} else {
			v, err := d.ReadString()
			if err != nil {
				return false, err
			}
			x.Id = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "email")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Email = ""
		} else {
			v, err := d.ReadString()
			if err != nil {
				return false, err
			}
			x.Email = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "name")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Name = ""
		} else {
			v, err := d.ReadString()
			if err != nil {
				return false, err
			}
			x.Name = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "age")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Age = 0
		} else {
			v, err := d.ReadInt32()
			if err != nil {
				return false, err
			}
			x.Age = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "isActive")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.IsActive = false
		} else {
			v, err := d.ReadBool()
			if err != nil {
				return false, err
			}
			x.IsActive = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "status")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Status = 0
		} else {
			var v UserStatus
			val, err := unmarshalEnum_UserStatus(d)
			if err != nil {
				if err == protojsonxgen.ErrUnknownEnum && discardUnknown {
				} else {
					return false, err
				}
			} else {
				v = val
			}
			x.Status = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "tags")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Tags = nil
		} else {
			values := x.Tags[:0]
			if values == nil {
				values = make([]string, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				v, err := d.ReadString()
				if err != nil {
					return false, err
				}
				values = append(values, v)
			}
			x.Tags = values
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "metadata")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Metadata = nil
		} else {
			m := make(map[string]string)
			if err := d.BeginObject(); err != nil {
				return false, err
			}
			mapFirst := true
			for {
				k, mapOK, err := d.NextObjectKey(&mapFirst)
				if err != nil {
					return false, err
				}
				if !mapOK {
					break
				}
				v, err := d.ReadString()
				if err != nil {
					return false, err
				}
				if _, exists := m[k]; exists {
					return false, protojsonxgen.DuplicateField(k)
				}
				m[k] = v
			}
			x.Metadata = m
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "address")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Address = nil
		} else {
			x.Address = &Address{}
			if fast, ok := any(x.Address).(interface {
				unmarshalProtoJSONXFast(*protojsonxgen.Decoder, bool) (bool, error)
			}); ok {
				if ok, err := fast.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
					return false, err
				} else if !ok {
					return false, nil
				}
			} else {
				if err := protojsonxgen.UnmarshalField(d, x.Address, discardUnknown); err != nil {
					return false, err
				}
			}
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "sessions")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Sessions = nil
		} else {
			values := x.Sessions[:0]
			if values == nil {
				values = make([]*Session, 0, 4)
			}
			if err := d.BeginArray(); err != nil {
				return false, err
			}
			arrayFirst := true
			for {
				elemOK, err := d.NextArrayElement(&arrayFirst)
				if err != nil {
					return false, err
				}
				if !elemOK {
					break
				}
				if d.ReadNull() {
					return false, protojsonxgen.NullRepeatedMessage()
				}
				v := &Session{}
				if fast, ok := any(v).(interface {
					unmarshalProtoJSONXFast(*protojsonxgen.Decoder, bool) (bool, error)
				}); ok {
					if ok, err := fast.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
						return false, err
					} else if !ok {
						return false, nil
					}
				} else {
					if err := protojsonxgen.UnmarshalField(d, v, discardUnknown); err != nil {
						return false, err
					}
				}
				values = append(values, v)
			}
			x.Sessions = values
		}
	}
	done, err := d.TryEndObject()
	if err != nil {
		return false, err
	}
	if !done {
		return false, nil
	}
	return true, nil
}

func (x *UserProfile) unmarshalProtoJSONXFrom(d *protojsonxgen.Decoder, discardUnknown bool) error {
	if err := d.BeginObject(); err != nil {
		return err
	}
	var seen [10]bool
	first := true
	for {
		key, ok, err := d.NextObjectKey(&first)
		if err != nil {
			return err
		}
		if !ok {
			return nil
		}
		switch key {
		case "id":
			if seen[0] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[0] = true
			if d.ReadNull() {
				x.Id = ""
			} else {
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				x.Id = v
			}
			continue
		case "email":
			if seen[1] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[1] = true
			if d.ReadNull() {
				x.Email = ""
			} else {
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				x.Email = v
			}
			continue
		case "name":
			if seen[2] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[2] = true
			if d.ReadNull() {
				x.Name = ""
			} else {
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				x.Name = v
			}
			continue
		case "age":
			if seen[3] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[3] = true
			if d.ReadNull() {
				x.Age = 0
			} else {
				v, err := d.ReadInt32()
				if err != nil {
					return err
				}
				x.Age = v
			}
			continue
		case "isActive", "is_active":
			if seen[4] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[4] = true
			if d.ReadNull() {
				x.IsActive = false
			} else {
				v, err := d.ReadBool()
				if err != nil {
					return err
				}
				x.IsActive = v
			}
			continue
		case "status":
			if seen[5] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[5] = true
			if d.ReadNull() {
				x.Status = 0
			} else {
				var v UserStatus
				val, err := unmarshalEnum_UserStatus(d)
				if err != nil {
					if err == protojsonxgen.ErrUnknownEnum && discardUnknown {
					} else {
						return err
					}
				} else {
					v = val
				}
				x.Status = v
			}
			continue
		case "tags":
			if seen[6] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[6] = true
			if d.ReadNull() {
				x.Tags = nil
			} else {
				values := x.Tags[:0]
				if values == nil {
					values = make([]string, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					v, err := d.ReadString()
					if err != nil {
						return err
					}
					values = append(values, v)
				}
				x.Tags = values
			}
			continue
		case "metadata":
			if seen[7] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[7] = true
			if d.ReadNull() {
				x.Metadata = nil
			} else {
				m := make(map[string]string)
				if err := d.BeginObject(); err != nil {
					return err
				}
				mapFirst := true
				for {
					k, mapOK, err := d.NextObjectKey(&mapFirst)
					if err != nil {
						return err
					}
					if !mapOK {
						break
					}
					v, err := d.ReadString()
					if err != nil {
						return err
					}
					if _, exists := m[k]; exists {
						return protojsonxgen.DuplicateField(k)
					}
					m[k] = v
				}
				x.Metadata = m
			}
			continue
		case "address":
			if seen[8] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[8] = true
			if d.ReadNull() {
				x.Address = nil
			} else {
				x.Address = &Address{}
				if slow, ok := any(x.Address).(interface {
					unmarshalProtoJSONXFrom(*protojsonxgen.Decoder, bool) error
				}); ok {
					if err := slow.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
						return err
					}
				} else {
					if err := protojsonxgen.UnmarshalField(d, x.Address, discardUnknown); err != nil {
						return err
					}
				}
			}
			continue
		case "sessions":
			if seen[9] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[9] = true
			if d.ReadNull() {
				x.Sessions = nil
			} else {
				values := x.Sessions[:0]
				if values == nil {
					values = make([]*Session, 0, 4)
				}
				if err := d.BeginArray(); err != nil {
					return err
				}
				arrayFirst := true
				for {
					elemOK, err := d.NextArrayElement(&arrayFirst)
					if err != nil {
						return err
					}
					if !elemOK {
						break
					}
					if d.ReadNull() {
						return protojsonxgen.NullRepeatedMessage()
					}
					v := &Session{}
					if slow, ok := any(v).(interface {
						unmarshalProtoJSONXFrom(*protojsonxgen.Decoder, bool) error
					}); ok {
						if err := slow.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
							return err
						}
					} else {
						if err := protojsonxgen.UnmarshalField(d, v, discardUnknown); err != nil {
							return err
						}
					}
					values = append(values, v)
				}
				x.Sessions = values
			}
			continue
		default:
			if discardUnknown {
				if err := d.SkipValue(); err != nil {
					return err
				}
			} else {
				return protojsonxgen.UnknownField(key)
			}
		}
	}
}

func (x *Address) ProtoJSONXFastPath() {}

func (x *Address) MarshalProtoJSONX() ([]byte, error) {
	e := protojsonxgen.NewEncoder()
	if err := x.marshalProtoJSONXTo(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (x *Address) UnmarshalProtoJSONX(data []byte) error {
	return x.UnmarshalProtoJSONXWithOptions(data, false)
}

func (x *Address) UnmarshalProtoJSONXWithOptions(data []byte, discardUnknown bool) error {
	d := protojsonxgen.NewDecoder(data)
	*x = Address{}
	firstKey, savedOff, savedDepth, _, peekErr := d.PeekObjectFieldName()
	if peekErr != nil {
		return peekErr
	}
	if firstKey == "street" || firstKey == "" {
		d.Reset(savedOff, savedDepth)
		if ok, err := x.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
			return err
		} else if ok {
			return d.Finish()
		}
		*x = Address{}
	}
	d.Reset(savedOff, savedDepth)
	if err := x.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
		return err
	}
	return d.Finish()
}

func (x *Address) marshalProtoJSONXTo(e *protojsonxgen.Encoder) error {
	e.Byte('{')
	wrote := false
	if x.Street != "" {
		e.FieldPrefix(&wrote, "street")
		e.String(x.Street)
	}
	if x.City != "" {
		e.FieldPrefix(&wrote, "city")
		e.String(x.City)
	}
	if x.State != "" {
		e.FieldPrefix(&wrote, "state")
		e.String(x.State)
	}
	if x.Zip != "" {
		e.FieldPrefix(&wrote, "zip")
		e.String(x.Zip)
	}
	if x.Country != "" {
		e.FieldPrefix(&wrote, "country")
		e.String(x.Country)
	}
	e.Byte('}')
	return nil
}

func (x *Address) unmarshalProtoJSONXFast(d *protojsonxgen.Decoder, discardUnknown bool) (bool, error) {
	if err := d.BeginObject(); err != nil {
		return false, err
	}
	fastFirst := true
	{
		status, err := d.MatchFast(&fastFirst, "street")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Street = ""
		} else {
			v, err := d.ReadString()
			if err != nil {
				return false, err
			}
			x.Street = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "city")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.City = ""
		} else {
			v, err := d.ReadString()
			if err != nil {
				return false, err
			}
			x.City = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "state")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.State = ""
		} else {
			v, err := d.ReadString()
			if err != nil {
				return false, err
			}
			x.State = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "zip")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Zip = ""
		} else {
			v, err := d.ReadString()
			if err != nil {
				return false, err
			}
			x.Zip = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "country")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.Country = ""
		} else {
			v, err := d.ReadString()
			if err != nil {
				return false, err
			}
			x.Country = v
		}
	}
	done, err := d.TryEndObject()
	if err != nil {
		return false, err
	}
	if !done {
		return false, nil
	}
	return true, nil
}

func (x *Address) unmarshalProtoJSONXFrom(d *protojsonxgen.Decoder, discardUnknown bool) error {
	if err := d.BeginObject(); err != nil {
		return err
	}
	var seen [5]bool
	first := true
	for {
		key, ok, err := d.NextObjectKey(&first)
		if err != nil {
			return err
		}
		if !ok {
			return nil
		}
		switch key {
		case "street":
			if seen[0] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[0] = true
			if d.ReadNull() {
				x.Street = ""
			} else {
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				x.Street = v
			}
			continue
		case "city":
			if seen[1] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[1] = true
			if d.ReadNull() {
				x.City = ""
			} else {
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				x.City = v
			}
			continue
		case "state":
			if seen[2] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[2] = true
			if d.ReadNull() {
				x.State = ""
			} else {
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				x.State = v
			}
			continue
		case "zip":
			if seen[3] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[3] = true
			if d.ReadNull() {
				x.Zip = ""
			} else {
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				x.Zip = v
			}
			continue
		case "country":
			if seen[4] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[4] = true
			if d.ReadNull() {
				x.Country = ""
			} else {
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				x.Country = v
			}
			continue
		default:
			if discardUnknown {
				if err := d.SkipValue(); err != nil {
					return err
				}
			} else {
				return protojsonxgen.UnknownField(key)
			}
		}
	}
}

func (x *Session) ProtoJSONXFastPath() {}

func (x *Session) MarshalProtoJSONX() ([]byte, error) {
	e := protojsonxgen.NewEncoder()
	if err := x.marshalProtoJSONXTo(e); err != nil {
		return nil, err
	}
	return e.Bytes(), nil
}

func (x *Session) UnmarshalProtoJSONX(data []byte) error {
	return x.UnmarshalProtoJSONXWithOptions(data, false)
}

func (x *Session) UnmarshalProtoJSONXWithOptions(data []byte, discardUnknown bool) error {
	d := protojsonxgen.NewDecoder(data)
	*x = Session{}
	firstKey, savedOff, savedDepth, _, peekErr := d.PeekObjectFieldName()
	if peekErr != nil {
		return peekErr
	}
	if firstKey == "sessionId" || firstKey == "" {
		d.Reset(savedOff, savedDepth)
		if ok, err := x.unmarshalProtoJSONXFast(d, discardUnknown); err != nil {
			return err
		} else if ok {
			return d.Finish()
		}
		*x = Session{}
	}
	d.Reset(savedOff, savedDepth)
	if err := x.unmarshalProtoJSONXFrom(d, discardUnknown); err != nil {
		return err
	}
	return d.Finish()
}

func (x *Session) marshalProtoJSONXTo(e *protojsonxgen.Encoder) error {
	e.Byte('{')
	wrote := false
	if x.SessionId != "" {
		e.FieldPrefix(&wrote, "sessionId")
		e.String(x.SessionId)
	}
	if x.LoginTimestamp != 0 {
		e.FieldPrefix(&wrote, "loginTimestamp")
		e.Int64String(x.LoginTimestamp)
	}
	if x.IpAddress != "" {
		e.FieldPrefix(&wrote, "ipAddress")
		e.String(x.IpAddress)
	}
	e.Byte('}')
	return nil
}

func (x *Session) unmarshalProtoJSONXFast(d *protojsonxgen.Decoder, discardUnknown bool) (bool, error) {
	if err := d.BeginObject(); err != nil {
		return false, err
	}
	fastFirst := true
	{
		status, err := d.MatchFast(&fastFirst, "sessionId")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.SessionId = ""
		} else {
			v, err := d.ReadString()
			if err != nil {
				return false, err
			}
			x.SessionId = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "loginTimestamp")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.LoginTimestamp = 0
		} else {
			v, err := d.ReadInt64()
			if err != nil {
				return false, err
			}
			x.LoginTimestamp = v
		}
	}
	{
		status, err := d.MatchFast(&fastFirst, "ipAddress")
		if err != nil {
			return false, err
		}
		if status == 0 {
			return true, nil
		}
		if status < 0 {
			return false, nil
		}
		if d.ReadNull() {
			x.IpAddress = ""
		} else {
			v, err := d.ReadString()
			if err != nil {
				return false, err
			}
			x.IpAddress = v
		}
	}
	done, err := d.TryEndObject()
	if err != nil {
		return false, err
	}
	if !done {
		return false, nil
	}
	return true, nil
}

func (x *Session) unmarshalProtoJSONXFrom(d *protojsonxgen.Decoder, discardUnknown bool) error {
	if err := d.BeginObject(); err != nil {
		return err
	}
	var seen [3]bool
	first := true
	for {
		key, ok, err := d.NextObjectKey(&first)
		if err != nil {
			return err
		}
		if !ok {
			return nil
		}
		switch key {
		case "sessionId", "session_id":
			if seen[0] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[0] = true
			if d.ReadNull() {
				x.SessionId = ""
			} else {
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				x.SessionId = v
			}
			continue
		case "loginTimestamp", "login_timestamp":
			if seen[1] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[1] = true
			if d.ReadNull() {
				x.LoginTimestamp = 0
			} else {
				v, err := d.ReadInt64()
				if err != nil {
					return err
				}
				x.LoginTimestamp = v
			}
			continue
		case "ipAddress", "ip_address":
			if seen[2] {
				return protojsonxgen.DuplicateField(key)
			}
			seen[2] = true
			if d.ReadNull() {
				x.IpAddress = ""
			} else {
				v, err := d.ReadString()
				if err != nil {
					return err
				}
				x.IpAddress = v
			}
			continue
		default:
			if discardUnknown {
				if err := d.SkipValue(); err != nil {
					return err
				}
			} else {
				return protojsonxgen.UnknownField(key)
			}
		}
	}
}

func unmarshalEnum_UserStatus(d *protojsonxgen.Decoder) (UserStatus, error) {
	var v UserStatus
	if d.IsString() {
		s, err := d.ReadStringBytes()
		if err != nil {
			return 0, err
		}
		if protojsonxgen.MatchStringBytes(s, "STATUS_UNSPECIFIED") {
			v = UserStatus_STATUS_UNSPECIFIED
		} else if protojsonxgen.MatchStringBytes(s, "STATUS_ACTIVE") {
			v = UserStatus_STATUS_ACTIVE
		} else if protojsonxgen.MatchStringBytes(s, "STATUS_INACTIVE") {
			v = UserStatus_STATUS_INACTIVE
		} else if protojsonxgen.MatchStringBytes(s, "STATUS_SUSPENDED") {
			v = UserStatus_STATUS_SUSPENDED
		} else {
			return 0, protojsonxgen.ErrUnknownEnum
		}
	} else {
		n, err := d.ReadInt32()
		if err != nil {
			return 0, err
		}
		v = UserStatus(n)
	}
	return v, nil
}
